// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/okx/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// OKX real-time kline/candlestick WebSocket message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://www.okx.com/docs-v5/en/#websocket-api-public-channel-candlesticks-channel>
/// ```json
/// {
/// "arg": {"channel": "candle1m", "instId": "BTC-USDT"},
/// "data": [
/// ["1672502400000","16850","16860","16845","16855.5","12.345","208000","208000","1"]
/// ]
/// }
/// ```
pub struct OkxKline {
    pub arg: OkxKlineArg,
    pub data: Vec<Vec<String>>,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// The `"arg"` field from an OKX kline WebSocket message, containing
/// the channel name and instrument ID.
pub struct OkxKlineArg {
    pub channel: String,
    #[serde(rename = "instId")]
    pub inst_id: String,
}

