// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/okx/subscription.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
#[serde(tag = "event", rename_all = "lowercase")]
#[non_exhaustive]
/// [`Okx`](super::Okx) WebSocket subscription response.
/// 
/// ### Raw Payload Examples
/// #### Subscription Trades Ok Response
/// ```json
/// {
/// "event": "subscribe",
/// "args": {
/// "channel": "trades",
/// "instId": "BTC-USD-191227"
/// }
/// }
/// ```
/// 
/// #### Subscription Trades Error Response
/// ```json
/// {
/// "event": "error",
/// "code": "60012",
/// "msg": "Invalid request: {\"op\": \"subscribe\", \"args\":[{ \"channel\" : \"trades\", \"instId\" : \"BTC-USD-191227\"}]}"
/// }
/// ```
/// 
/// See docs: <https://www.okx.com/docs-v5/en/#websocket-api-subscribe>
pub enum OkxSubResponse {
    #[serde(rename = "subscribe")]
    Subscribed,
    Error {
        code: String,
        #[serde(rename = "msg")]
        message: String,
    },
}

