// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/rest/klines.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone)]
/// REST request to fetch kline/candlestick data from the Bybit API.
/// 
/// The `path` field stores the endpoint path (always `/v5/market/kline`).
pub struct GetBybitKlines {
    /// Endpoint path (e.g., "/v5/market/kline").
    pub path: &'static str,
    /// Query parameters for the klines request.
    pub params: GetBybitKlinesParams,
}

#[derive(Debug, Clone, Serialize)]
/// Query parameters for a Bybit klines REST request.
pub struct GetBybitKlinesParams {
    /// Market category: "spot" or "linear".
    pub category: String,
    /// Trading pair symbol (e.g., "BTCUSDT").
    pub symbol: String,
    /// Kline interval (e.g., "1", "60", "D").
    pub interval: String,
    /// Optional start time in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Optional end time in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end: Option<i64>,
    /// Optional limit on the number of klines to return (max 1000).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

#[non_exhaustive]
#[derive(Debug, Clone, serde::Deserialize)]
/// Top-level Bybit klines API response wrapper.
/// 
/// Bybit returns klines nested inside `result.list`:
/// ```json
/// {
/// "retCode": 0,
/// "retMsg": "OK",
/// "result": {
/// "symbol": "BTCUSDT",
/// "category": "spot",
/// "list": [...]
/// }
/// }
/// ```
pub struct BybitKlinesResponse {
    #[serde(rename = "retCode")]
    pub ret_code: i64,
    #[serde(rename = "retMsg")]
    pub ret_msg: String,
    pub result: BybitKlinesResult,
}

#[derive(Debug, Clone, serde::Deserialize)]
/// Inner result containing the list of raw kline arrays.
pub struct BybitKlinesResult {
    pub list: Vec<BybitKlineRaw>,
}

#[derive(Debug, Clone)]
/// Raw kline/candlestick data returned by the Bybit REST API.
/// 
/// Bybit returns klines as arrays of strings:
/// `[startTime, open, high, low, close, volume, turnover]`
/// 
/// This struct uses a custom [`Deserialize`] implementation with a sequence
/// visitor to parse each positional element.
pub struct BybitKlineRaw {
    pub start_time: i64,
    pub open: String,
    pub high: String,
    pub low: String,
    pub close: String,
    pub volume: String,
    pub turnover: String,
}

