// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/rest/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// Bybit REST API error payload.
/// 
/// Returned by the Bybit API when a request fails, e.g.:
/// ```json
/// { "retCode": 10001, "retMsg": "Invalid symbol." }
/// ```
pub struct BybitApiError {
    #[serde(rename = "retCode")]
    pub(crate) ret_code: i64,
    #[serde(rename = "retMsg")]
    pub(crate) ret_msg: String,
}

#[derive(Debug)]
/// HTTP response parser for Bybit REST API responses.
pub struct BybitHttpParser;

/// Trait providing the Bybit-specific `category` parameter for REST requests.
/// 
/// Bybit requires a `category` query parameter ("spot" or "linear") to
/// distinguish between spot and perpetual futures markets.
pub trait BybitCategory {
    /// Return the Bybit market category string.
    fn category() -> &'static str;
}

#[non_exhaustive]
#[derive(Clone)]
/// Generic REST client for Bybit exchange variants.
/// 
/// The `Server` type parameter determines which Bybit server variant
/// (spot or perpetuals) this client connects to, via the
/// [`RestExchangeServer`] trait.
/// 
/// Includes a rate limiter configured for Bybit rate limits
/// (10 requests per second).
pub struct BybitRestClient<Server> {
    pub(crate) client: Arc<RestClient<'static, PublicNoHeaders, BybitHttpParser>>,
    pub(crate) rate_limiter: Arc<ExchangeRateLimiter>,
    _server: PhantomData<Server>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl BybitRestClient {
    /// Construct a new [`BybitRestClient`] using the base URL from
    /// [`Server::rest_base_url()`](RestExchangeServer::rest_base_url).
    /// 
    /// Initialises a rate limiter with a quota of 10 requests per second,
    /// matching the Bybit rate limit.
    pub fn new() -> Self { /* ... */ }
    /// Construct a new [`BybitRestClient`] with a caller-provided rate limiter.
    /// 
    /// This allows sharing a single [`ExchangeRateLimiter`] across multiple
    /// clients so they draw from the same token bucket.
    pub fn with_rate_limiter(rate_limiter: Arc<ExchangeRateLimiter>) -> Self { /* ... */ }
    /// Construct a [`BybitRestClient`] with a custom base URL.
    /// 
    /// Useful for testing with a mock server where the URL is not known at
    /// compile time. Does not require the `Server` type to implement
    /// [`RestExchangeServer`] since the URL is provided directly.
    pub fn with_base_url(base_url: String) -> Self { /* ... */ }
    /// Return a reference to the inner HTTP client.
    pub fn http_client(&self) -> &Arc<RestClient<'static, PublicNoHeaders, BybitHttpParser>> { /* ... */ }
    /// Wait until the rate limiter permits the next request.
    /// 
    /// This method is for **standalone/direct usage** — call it before each
    /// REST API request when driving the client yourself (outside of a
    /// `barter-collector` pipeline). When using `barter-collector`, rate
    /// limiting is managed by the collector's orchestration layer.
    /// 
    /// Blocks asynchronously until a permit is available.
    pub async fn wait_for_rate_limit(&self) { /* ... */ }
}

