// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/rest/trades.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Deserialize)]
/// Top-level response from `GET /v5/market/recent-trade`.
/// 
/// Bybit returns trades nested inside `result.list`:
/// ```json
/// {
/// "retCode": 0,
/// "retMsg": "OK",
/// "result": {
/// "category": "spot",
/// "list": [...]
/// }
/// }
/// ```
pub struct BybitTradesResponse {
    #[serde(rename = "retCode")]
    pub ret_code: i64,
    #[serde(rename = "retMsg")]
    pub ret_msg: String,
    pub result: BybitTradesResult,
}

#[derive(Debug, Clone, Deserialize)]
/// Inner result containing the list of trades.
pub struct BybitTradesResult {
    pub list: Vec<BybitRestTrade>,
}

#[derive(Debug, Clone, Deserialize)]
/// A single trade from the Bybit REST API.
/// 
/// See: <https://bybit-exchange.github.io/docs/v5/market/recent-trade>
pub struct BybitRestTrade {
    /// Execution ID.
    #[serde(rename = "execId")]
    pub exec_id: String,
    /// Trade price as a string.
    pub price: String,
    /// Trade size as a string.
    pub size: String,
    /// Trade side: "Buy" or "Sell".
    pub side: String,
    /// Timestamp in milliseconds as a string.
    pub time: String,
}

#[derive(Debug, Clone)]
/// REST request to fetch recent trades from the Bybit API.
/// 
/// The `path` field stores the endpoint path (always `/v5/market/recent-trade`).
pub struct GetBybitTrades {
    /// Endpoint path (e.g., "/v5/market/recent-trade").
    pub path: &'static str,
    /// Query parameters for the trades request.
    pub params: GetBybitTradesParams,
}

#[derive(Debug, Clone, Serialize)]
/// Query parameters for a Bybit recent trades REST request.
pub struct GetBybitTradesParams {
    /// Market category: "spot" or "linear".
    pub category: String,
    /// Trading pair symbol (e.g., "BTCUSDT").
    pub symbol: String,
    /// Max trades per request.
    /// Note: Bybit spot max is 60, linear/inverse max is 1000.
    /// If a larger limit is requested, the API silently clamps it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

