// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/order/id.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct ClientOrderId<T = SmolStr>(pub T);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct OrderId<T = SmolStr>(pub T);

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct StrategyId(pub SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ClientOrderId {
    /// Construct a `ClientOrderId` from the specified string.
    /// 
    /// Use [`Self::random`] to generate a random stack-allocated `ClientOrderId`.
    pub fn new<S: Into<SmolStr>>(id: S) -> Self { /* ... */ }
    /// Construct a stack-allocated `ClientOrderId` backed by a 23 byte [`SmolStr`].
    pub fn random() -> Self { /* ... */ }
}

impl StrategyId {
    pub fn new<S: AsRef<str>>(id: S) -> Self { /* ... */ }
    pub fn unknown() -> Self { /* ... */ }
}

impl OrderId {
    pub fn new<S: AsRef<str>>(id: S) -> Self { /* ... */ }
}

