// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/audit/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Interface that defines how a component (eg/ `Engine`) generates [`AuditTick`]s.
pub trait Auditor<AuditKind> {
    /// Full state snapshot.
    type Snapshot;

    /// `AuditTick` context.
    ///
    /// For example, the `Engine` uses [`EngineContext`].
    type Context;

    /// Build an `AuditTick` containing a full state snapshot.
    fn audit_snapshot(&mut self) -> AuditTick<Self::Snapshot, Self::Context>;

    /// Build an `AuditTick` from the provided `Kind`.
    fn audit<Kind>(&mut self, kind: Kind) -> AuditTick<AuditKind, Self::Context>
    where
        AuditKind: From<Kind>;
}

#[derive(
    Debug,
    Copy,
    Clone,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Default,
    Deserialize,
    Serialize,
    Constructor,
)]
/// `Engine` audit event & it's associated context. Sent via the AuditStream.
pub struct AuditTick<Kind, Context = EngineContext> {
    pub event: Kind,
    pub context: Context,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// Represents [`AuditTick`] types that are generated by the `Engine` and sent via the AuditStream.
pub enum EngineAudit<Event, Output> {
    /// Input event feed ended.
    FeedEnded,
    /// `Engine` processed an `Event`.
    Process(ProcessAudit<Event, Output>),
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
/// Represents [`AuditTick`] types that are generated when an `Engine` processes an `Event`.
pub struct ProcessAudit<Event, Output> {
    pub event: Event,
    pub outputs: NoneOneOrMany<Output>,
    pub errors: NoneOneOrMany<UnrecoverableEngineError>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl EngineAudit {
    pub fn process<E>(event: E) -> Self
        where
            E: Into<Event>,
        { /* ... */ }
    pub fn process_with_output<E, O>(event: E, output: O) -> Self
        where
            E: Into<Event>,
            O: Into<Output>,
        { /* ... */ }
    pub fn process_with_output_and_errs<E, ErrIter, O>(
            event: E,
            unrecoverable: ErrIter,
            output: O,
        ) -> Self
        where
            E: Into<Event>,
            ErrIter: IntoIterator<Item = UnrecoverableEngineError>,
            O: Into<Output>,
        { /* ... */ }
    pub fn with_process_and_err<ErrIter>(
            process: ProcessAudit<Event, Output>,
            unrecoverable: ErrIter,
        ) -> Self
        where
            ErrIter: IntoIterator<Item = UnrecoverableEngineError>,
        { /* ... */ }
}

impl ProcessAudit {
    pub fn with_event<E>(event: E) -> Self
        where
            E: Into<Event>,
        { /* ... */ }
    pub fn with_output<E, O>(event: E, output: O) -> Self
        where
            E: Into<Event>,
            O: Into<Output>,
        { /* ... */ }
    pub fn with_trading_state_update<E>(event: E, disabled: Option<OnTradingDisabled>) -> Self
        where
            E: Into<Event>,
        { /* ... */ }
    pub fn with_account_update<E>(event: E, account: UpdateFromAccountOutput<OnDisconnect>) -> Self
        where
            E: Into<Event>,
        { /* ... */ }
    pub fn with_market_update<E>(event: E, account: UpdateFromMarketOutput<OnDisconnect>) -> Self
        where
            E: Into<Event>,
        { /* ... */ }
    pub fn add_output<O>(self, output: O) -> Self
        where
            O: Into<Output>,
        { /* ... */ }
    pub fn add_errors<ErrIter>(self, errs: ErrIter) -> Self
        where
            ErrIter: IntoIterator<Item = UnrecoverableEngineError>,
        { /* ... */ }
}

