// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/stream/indexed.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait Indexer {
    type Unindexed;
    type Indexed;
    fn index(&self, item: Self::Unindexed) -> Result<Self::Indexed, IndexError>;
}

#[derive(Debug, Constructor)]
#[pin_project]
pub struct IndexedStream<Indexer, Stream> {
    #[pin]
    pub stream: Stream,
    pub indexer: Indexer,
}

