// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/stream/merge.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Merge two Streams and terminate when either Stream terminates. Merged Stream is fused, so will
/// end after the first `None`.
pub fn merge<L, R>(left: L, right: R) -> impl Stream<Item = L::Item>
where
    L: Stream,
    R: Stream<Item = L::Item>,
{ /* ... */ }

