// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/scheduling.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Generate an inclusive sequence of dates from `start` to `end`.
pub fn date_range(start: NaiveDate, end: NaiveDate) -> Vec<NaiveDate> { /* ... */ }

/// Choose monthly archives for complete months, daily for partial months.
/// 
/// Given an inclusive date range `[start, end]`, returns:
/// - `complete_months`: `Vec<(year, month)>` for months entirely within the range.
/// - `remaining_days`: `Vec<NaiveDate>` for days in partial months at the boundaries.
/// 
/// A month is "complete" if both its first and last day fall within `[start, end]`.
pub fn partition_date_range(start: NaiveDate, end: NaiveDate) -> (Vec<(i32, u32)>, Vec<NaiveDate>) { /* ... */ }

/// Return the last day of the given month.
/// 
/// # Panics
/// 
/// Panics if `month` is not 1..=12 or if `year` overflows the calendar.
pub fn last_day_of_month(year: i32, month: u32) -> NaiveDate { /* ... */ }

