// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/streams.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Stream data by driving a [`PaginationStrategy`] in a loop.
/// 
/// Uses `stream::unfold` with the strategy as state. Acquires the rate
/// limiter and retries on each page fetch (fixes the
/// rate-limiter-outside-retry bug from barter-data).
pub fn stream_paginated<S: PaginationStrategy + 'static>(
    strategy: S,
    rate_limiter: Arc<ExchangeRateLimiter>,
) -> Pin<Box<dyn Stream<Item = Result<Vec<S::Item>, DataError>> + Send>> { /* ... */ }

/// Stream bulk data by fanning out over dates with bounded concurrency.
/// 
/// Generic over any async function that fetches a single day's data.
/// 404 dates (returning `Ok(None)`) are silently skipped.
pub fn stream_bulk<'a, T, Fut>(
    dates: Vec<chrono::NaiveDate>,
    concurrency: usize,
    fetch_day: impl Fn(chrono::NaiveDate) -> Fut + Send + 'a,
) -> Pin<Box<dyn Stream<Item = Result<Vec<T>, DataError>> + Send + 'a>>
where
    T: Send + 'a,
    Fut: std::future::Future<Output = Result<Option<Vec<T>>, DataError>> + Send + 'a,
{ /* ... */ }

