// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Terse type alias for a [`BybitKlineData`] real-time kline/candlestick WebSocket message.
/// 
/// Uses the generic [`BybitPayload`] wrapper which handles topic-based subscription ID extraction.
pub type BybitKline = BybitPayload<Vec<BybitKlineData>>;

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Inner kline data from the Bybit `"data"` array.
/// 
/// ### Raw Payload Examples
/// See docs: <https://bybit-exchange.github.io/docs/v5/websocket/public/kline>
/// ```json
/// {
/// "start": 1672502400000,
/// "end": 1672502459999,
/// "interval": "1",
/// "open": "16850",
/// "close": "16855.5",
/// "high": "16860",
/// "low": "16845",
/// "volume": "12.345",
/// "turnover": "208000",
/// "confirm": true,
/// "timestamp": 1672502458000
/// }
/// ```
pub struct BybitKlineData {
    /// Kline open time (epoch ms).
    #[serde(deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc")]
    pub start: DateTime<Utc>,

    /// Kline close time (epoch ms).
    #[serde(deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc")]
    pub end: DateTime<Utc>,

    /// Interval (e.g., "1", "60", "D").
    pub interval: String,

    /// Open price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub open: f64,

    /// High price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub high: f64,

    /// Low price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub low: f64,

    /// Close price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub close: f64,

    /// Base asset volume.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub volume: f64,

    /// Quote asset volume (turnover).
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub turnover: f64,

    /// Whether the candle is confirmed/closed.
    pub confirm: bool,

    /// Timestamp (epoch ms).
    #[serde(deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc")]
    pub timestamp: DateTime<Utc>,
}

