// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/channel.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Serialize)]
/// Type that defines how to translate a Barter [`Subscription`] into a [`Bybit`]
/// channel to be subscribed to.
/// 
/// See docs: <https://bybit-exchange.github.io/docs/v5/ws/connect>
pub struct BybitChannel(pub(crate) SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl BybitChannel {
    /// [`Bybit`] real-time trades channel name.
    /// 
    /// See docs: <https://bybit-exchange.github.io/docs/v5/websocket/public/trade>
    pub const TRADES: Self = todo!();
    /// [`Bybit`] real-time OrderBook Level1 (top of books) channel name.
    /// 
    /// See docs: <https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook>
    pub const ORDER_BOOK_L1: Self = todo!();
    /// [`Bybit`] OrderBook Level2 channel name (50-level, 20ms delta updates).
    /// 
    /// See docs: <https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook>
    pub const ORDER_BOOK_L2: Self = todo!();
}

