// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/consumer.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Default [`ReconnectionBackoffPolicy`] for a [`reconnecting`](`ReconnectingStream`) [`MarketStream`].
pub const STREAM_RECONNECTION_POLICY: ReconnectionBackoffPolicy = todo!();

/// Convenient type alias for a [`MarketEvent`] [`Result`] consumed via a
/// [`reconnecting`](`ReconnectingStream`) [`MarketStream`].
pub type MarketStreamResult<InstrumentKey, Kind> =
    reconnect::Event<ExchangeId, Result<MarketEvent<InstrumentKey, Kind>, DataError>>;

/// Convenient type alias for a [`MarketEvent`] consumed via a
/// [`reconnecting`](`ReconnectingStream`) [`MarketStream`].
pub type MarketStreamEvent<InstrumentKey, Kind> =
    reconnect::Event<ExchangeId, MarketEvent<InstrumentKey, Kind>>;

#[tracing::instrument(skip_all)]
/// Initialises a market stream with a connection task using a collection
/// of [`Subscription`]s.
/// 
/// The provided [`ReconnectionBackoffPolicy`] dictates how the exponential backoff scales
/// between reconnections.
/// 
/// Returns an `mpsc::UnboundedReceiver` of market events and a [`TypedHandle`] for
/// dynamic subscribe/unsubscribe on the live connection.
pub async fn init_market_stream<Exchange, Instrument, Kind>(
    policy: ReconnectionBackoffPolicy,
    subscriptions: Vec<Subscription<Exchange, Instrument, Kind>>,
) -> Result<
    (
        mpsc::UnboundedReceiver<MarketStreamResult<Instrument::Key, Kind::Event>>,
        TypedHandle<Exchange, Instrument::Key, Kind>,
    ),
    DataError,
>
where
    Exchange: StreamSelector<Instrument, Kind> + Send + Sync + 'static,
    Instrument: InstrumentData + Display + 'static,
    Instrument::Key: Clone + Send + Sync + 'static,
    Kind: SubscriptionKind + Display + Send + Sync + 'static,
    Kind::Event: Send + 'static,
    Subscription<Exchange, Instrument, Kind>: Identifier<Exchange::Channel> + 'static,
    // 'static required here (not on Connector trait) because tokio::spawn
    // captures Command<Channel, Market, IK> via the mpsc receiver.
    Exchange::Channel: 'static,
    Exchange::Market: 'static,
{ /* ... */ }

#[derive(
    Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct StreamKey<Kind = &'static str> {
    pub stream: &'static str,
    pub exchange: ExchangeId,
    pub kind: Option<Kind>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl StreamKey {
    pub fn new_general(stream: &'static str, exchange: ExchangeId) -> Self { /* ... */ }
}

