// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/handle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone)]
/// A single resolved subscription entry for the connection task.
pub struct SubEntry<Channel, Market, InstrumentKey> {
    pub id: SubscriptionId,
    pub exchange_sub: ExchangeSub<Channel, Market>,
    pub instrument_key: InstrumentKey,
}

#[derive(Debug, Clone)]
#[non_exhaustive]
/// Command sent from a [`TypedHandle`] to the connection task.
pub enum Command<Channel, Market, InstrumentKey> {
    Subscribe {
        /// Resolved subscription entries per instrument.
        /// SubscriptionId is pre-derived from ExchangeSub::id() by the handle.
        entries: Vec<SubEntry<Channel, Market, InstrumentKey>>,
    },
    Unsubscribe {
        /// SubscriptionIds to remove. The task looks up ExchangeSubs from ActiveSubs
        /// to call Connector::unsubscribe_requests().
        subscription_ids: Vec<SubscriptionId>,
    },
}

#[derive(Debug, Clone)]
/// Type-safe handle for dynamically subscribing/unsubscribing on a live WebSocket connection.
/// 
/// Provides compile-time safety: a `TypedHandle<BinanceSpot, _, PublicTrades>` cannot
/// accidentally send commands to a Kraken connection.
/// 
/// Internally converts `Subscription` → `ExchangeSub` → `SubscriptionId` using the same
/// path as static init.
pub struct TypedHandle<Exchange, InstrumentKey, Kind>
where
    Exchange: Connector,
    Kind: SubscriptionKind,
{
    command_tx: mpsc::UnboundedSender<Command<Exchange::Channel, Exchange::Market, InstrumentKey>>,
    _phantom: PhantomData<Kind>,
}

/// Type-erased handle for dynamic subscribe/unsubscribe operations.
/// 
/// Stored in `DynamicStreamHandles` as `Box<dyn DynHandle<Instrument>>`.
/// Eliminates the need for `Box<dyn Any>` and `downcast_ref`.
pub trait DynHandle<Instrument>: Send + Sync {
    fn subscribe_erased(
        &self,
        subscriptions: Vec<Subscription<ExchangeId, Instrument, SubKind>>,
    ) -> Result<Vec<SubscriptionId>, DataError>;

    fn unsubscribe_erased(&self, subscription_ids: Vec<SubscriptionId>) -> Result<(), DataError>;
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl TypedHandle {
    /// Create a new `TypedHandle`.
    pub fn new(
            command_tx: mpsc::UnboundedSender<
                Command<Exchange::Channel, Exchange::Market, InstrumentKey>,
            >,
        ) -> Self { /* ... */ }
    /// Subscribe to new instruments on the live WebSocket connection.
    /// 
    /// Accepts the same `Subscription` type used for static init. Internally converts
    /// each subscription to an `ExchangeSub`, derives a `SubscriptionId`, and sends a
    /// `Command::Subscribe` to the connection task.
    /// 
    /// Returns the `SubscriptionId`s for later unsubscription.
    pub fn subscribe<Instrument>(
            &self,
            subscriptions: Vec<Subscription<Exchange, Instrument, Kind>>,
        ) -> Result<Vec<SubscriptionId>, DataError>
        where
            Instrument: InstrumentData<Key = InstrumentKey>,
            Subscription<Exchange, Instrument, Kind>: Identifier<Exchange::Channel>,
        { /* ... */ }
    /// Unsubscribe from instruments by their `SubscriptionId`s (returned from `subscribe`).
    pub fn unsubscribe(&self, subscription_ids: Vec<SubscriptionId>) -> Result<(), DataError> { /* ... */ }
    /// Subscribe to a single instrument. Convenience wrapper around `subscribe`.
    pub fn subscribe_one<Instrument>(
            &self,
            subscription: Subscription<Exchange, Instrument, Kind>,
        ) -> Result<SubscriptionId, DataError>
        where
            Instrument: InstrumentData<Key = InstrumentKey>,
            Subscription<Exchange, Instrument, Kind>: Identifier<Exchange::Channel>,
        { /* ... */ }
    /// Unsubscribe from a single instrument. Convenience wrapper around `unsubscribe`.
    pub fn unsubscribe_one(&self, subscription_id: SubscriptionId) -> Result<(), DataError> { /* ... */ }
}

