// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
/// Ergonomic collection of exchange market event receivers.
pub struct Streams<T> {
    pub streams: FnvHashMap<ExchangeId, UnboundedRx<T>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Streams {
    /// Construct a [`StreamBuilder`] for configuring new market event [`Streams`].
    pub fn builder<InstrumentKey, Kind>() -> StreamBuilder<InstrumentKey, Kind>
        where
            Kind: SubscriptionKind,
        { /* ... */ }
    /// Construct a [`MultiStreamBuilder`] for configuring new
    /// [`MarketEvent<T>`](crate::event::MarketEvent) [`Streams`].
    pub fn builder_multi() -> MultiStreamBuilder<T> { /* ... */ }
    /// Remove an exchange market event [`Stream`] from the [`Streams`] `HashMap`.
    pub fn select(&mut self, exchange: ExchangeId) -> Option<impl Stream<Item = T> + '_> { /* ... */ }
    /// Select and merge every exchange `Stream` using
    /// [`select_all`](futures_util::stream::select_all::select_all).
    pub fn select_all(self) -> impl Stream<Item = T> { /* ... */ }
}

