// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/task.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[allow(clippy::cognitive_complexity)]
/// Spawned connection task that owns the WebSocket stream and transformer.
/// 
/// Outer loop handles reconnection with exponential backoff.
/// Inner loop uses `tokio::select!` to multiplex command processing and frame reading.
pub(crate) async fn connection_task<Exchange, Instrument, Kind, TransformerT, Parser, SnapFetcher>(
    subscriptions: Vec<Subscription<Exchange, Instrument, Kind>>,
    mut command_rx: mpsc::UnboundedReceiver<
        Command<Exchange::Channel, Exchange::Market, Instrument::Key>,
    >,
    event_tx: mpsc::UnboundedSender<MarketStreamResult<Instrument::Key, Kind::Event>>,
    policy: crate::streams::reconnect::stream::ReconnectionBackoffPolicy,
    init_result_tx: oneshot::Sender<Result<(), DataError>>,
) where
    Exchange: Connector + Send + Sync,
    Instrument: InstrumentData,
    Instrument::Key: Clone + Send + Sync,
    Kind: SubscriptionKind + Send + Sync,
    Kind::Event: Send,
    TransformerT: ExchangeTransformer<Exchange, Instrument::Key, Kind> + Send,
    Parser: StreamParser<TransformerT::Input, Message = WsMessage, Error = WsError> + Send,
    SnapFetcher: SnapshotFetcher<Exchange, Kind>,
    Subscription<Exchange, Instrument, Kind>: Identifier<Exchange::Channel>,
{ /* ... */ }

