// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitmex/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Terse type alias for a [`BitmexKline`](BitmexKlineInner) real-time kline WebSocket message.
pub type BitmexKline = BitmexMessage<BitmexKlineInner>;

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// ### Raw Payload Examples
/// See docs: <https://www.bitmex.com/app/wsAPI>
/// #### Kline payload
/// ```json
/// {
/// "table": "tradeBin1m",
/// "action": "insert",
/// "data": [
/// {
/// "timestamp": "2023-01-01T00:01:00.000Z",
/// "symbol": "XBTUSD",
/// "open": 16850,
/// "close": 16855.5,
/// "high": 16860,
/// "low": 16845,
/// "trades": 150,
/// "volume": 123450,
/// "vwap": 16852.5,
/// "lastSize": 5,
/// "turnover": 733000000,
/// "homeNotional": 12.345,
/// "foreignNotional": 208000
/// }
/// ]
/// }
/// ```
pub struct BitmexKlineInner {
    pub timestamp: DateTime<Utc>,
    pub symbol: String,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub trades: u64,
    pub volume: f64,
    #[serde(rename = "foreignNotional")]
    pub foreign_notional: f64,
}

