// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitmex/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Terse type alias for an [`BitmexTrade`](BitmexTradeInner) real-time trades WebSocket message.
pub type BitmexTrade = BitmexMessage<BitmexTradeInner>;

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// ### Raw Payload Examples
/// See docs: <https://www.bitmex.com/app/wsAPI#Response-Format>
/// #### Trade payload
/// ```json
/// {
/// "table": "trade",
/// "action": "insert",
/// "data": [
/// {
/// "timestamp": "2023-02-18T09:27:59.701Z",
/// "symbol": "XBTUSD",
/// "side": "Sell",
/// "size": 200,
/// "price": 24564.5,
/// "tickDirection": "MinusTick",
/// "trdMatchID": "31e50cb7-e005-a44e-f354-86e88dff52eb",
/// "grossValue": 814184,
/// "homeNotional": 0.00814184,
/// "foreignNotional": 200,
/// "trdType": "Regular"
/// }
/// ]
/// }
/// ```
pub struct BitmexTradeInner {
    pub timestamp: DateTime<Utc>,
    pub symbol: String,
    pub side: Side,
    #[serde(rename = "size")]
    pub amount: f64,
    pub price: f64,

    #[serde(rename = "trdMatchID")]
    pub id: String,
}

