// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/error.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// All errors generated in `barter-data`.
pub enum DataError {
    #[error("failed to index market data Subscriptions: {0}")]
    Index(#[from] IndexError),

    #[error("failed to initialise reconnecting MarketStream due to empty subscriptions")]
    SubscriptionsEmpty,

    #[error("connection task terminated before signaling init result")]
    ConnectionTaskTerminated,

    #[error("unsupported DynamicStreams Subscription SubKind: {0}")]
    UnsupportedSubKind(SubKind),

    #[error("initial snapshot missing for: {0}")]
    InitialSnapshotMissing(SubscriptionId),

    #[error("initial snapshot invalid: {0}")]
    InitialSnapshotInvalid(String),

    #[error("command channel closed")]
    CommandChannelClosed,

    #[error("SocketError: {0}")]
    Socket(String),

    #[error("unsupported dynamic Subscription for exchange: {exchange}, kind: {sub_kind}")]
    Unsupported {
        exchange: ExchangeId,
        sub_kind: SubKind,
    },

    #[error("no connection for {exchange} {sub_kind}")]
    NoConnection {
        exchange: ExchangeId,
        sub_kind: SubKind,
    },

    #[error(
        "subscription batch mismatch: expected ({expected_exchange}, {expected_sub_kind}), got ({actual_exchange}, {actual_sub_kind})"
    )]
    SubscriptionMismatch {
        expected_exchange: ExchangeId,
        expected_sub_kind: SubKind,
        actual_exchange: ExchangeId,
        actual_sub_kind: SubKind,
    },

    #[error(
        "\
        InvalidSequence: first_update_id {first_update_id} does not follow on from the \
        prev_last_update_id {prev_last_update_id} \
    "
    )]
    InvalidSequence {
        prev_last_update_id: u64,
        first_update_id: u64,
    },

    /// HTTP transport error (request send failure, body read failure, non-2xx status).
    /// `status` is `Some` when an HTTP response was received; `None` for
    /// connection-level failures where no response arrived.
    /// `url` captures which endpoint failed.
    #[error("HTTP error (status={}) for {url}: {message}", status.map_or("none".to_string(), |s| s.to_string()))]
    Http {
        status: Option<u16>,
        url: String,
        message: String,
    },

    /// Exchange API returned a structured error response (HTTP 200 with error payload).
    #[error("{exchange} API error (code {code}): {message}")]
    ExchangeApi {
        exchange: String,
        code: String,
        message: String,
    },

    /// Data parsing failure (CSV, JSON, timestamp, numeric conversion).
    #[error("data parse error: {0}")]
    DataParse(String),

    /// Archive decompression or extraction failure (ZIP, LZ4, gzip).
    #[error("bulk archive error: {0}")]
    BulkArchive(String),

    /// SHA-256 checksum mismatch on a downloaded archive.
    #[error("checksum mismatch: expected {expected}, actual {actual}")]
    ChecksumMismatch { expected: String, actual: String },

    /// Exchange does not support the requested interval.
    #[error("{exchange} does not support interval: {interval}")]
    UnsupportedInterval { exchange: String, interval: String },

    /// Exchange does not support the requested instrument kind.
    #[error("{exchange} does not support instrument kind: {instrument}")]
    UnsupportedInstrument {
        exchange: String,
        instrument: String,
    },

    /// Local filesystem I/O error (distinct from archive decompression).
    #[error("I/O error: {0}")]
    Io(String),

    /// Pagination safety limit exceeded.
    #[error("{exchange} pagination limit exceeded ({limit}) for {market}")]
    PaginationLimit {
        exchange: String,
        market: String,
        limit: usize,
    },
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl DataError {
    #[allow(clippy::match_like_matches_macro)]
    /// Determine if an error requires a [`MarketStream`](super::MarketStream) to re-initialise.
    pub fn is_terminal(&self) -> bool { /* ... */ }
}

