// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/channel.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait Tx
where
    Self: Debug + Clone + Send,
{
    type Item;
    type Error: Unrecoverable + Debug;
    fn send<Item: Into<Self::Item>>(&self, item: Item) -> Result<(), Self::Error>;
}

#[derive(Debug)]
/// Convenience type that holds the [`UnboundedTx`] and [`UnboundedRx`].
pub struct Channel<T> {
    pub tx: UnboundedTx<T>,
    pub rx: UnboundedRx<T>,
}

#[derive(Debug, Clone)]
pub struct UnboundedTx<T> {
    pub tx: tokio::sync::mpsc::UnboundedSender<T>,
}

#[derive(Debug, Constructor)]
pub struct UnboundedRx<T> {
    pub rx: tokio::sync::mpsc::UnboundedReceiver<T>,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Deserialize, Serialize)]
pub struct ChannelTxDroppable<ChannelTx> {
    pub state: ChannelState<ChannelTx>,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Deserialize, Serialize, Display)]
pub enum ChannelState<Tx> {
    Active(Tx),
    Disabled,
}

pub fn mpsc_unbounded<T>() -> (UnboundedTx<T>, UnboundedRx<T>) { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ChannelTxDroppable {
    pub fn new(tx: ChannelTx) -> Self { /* ... */ }
    pub fn new_disabled() -> Self { /* ... */ }
    pub fn disable(&mut self) { /* ... */ }
    pub fn send(&mut self, item: ChannelTx::Item) { /* ... */ }
}

impl UnboundedTx {
    pub fn new(tx: tokio::sync::mpsc::UnboundedSender<T>) -> Self { /* ... */ }
}

impl UnboundedRx {
    pub fn into_stream(self) -> tokio_stream::wrappers::UnboundedReceiverStream<T> { /* ... */ }
}

impl Channel {
    /// Construct a new unbounded [`Channel`].
    pub fn new() -> Self { /* ... */ }
}

