// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/metric.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialOrd, PartialEq, Serialize)]
pub struct Metric {
    /// Metric name.
    pub name: &'static str,

    /// Milliseconds since the Unix epoch.
    pub time: u64,

    /// Key-Value pairs to categorise the Metric.
    pub tags: Vec<Tag>,

    /// Observed measurements.
    pub fields: Vec<Field>,
}

#[derive(Debug, Clone, Serialize, Ord, PartialOrd, Eq, PartialEq)]
pub struct Tag {
    pub key: &'static str,
    pub value: String,
}

#[derive(Debug, Clone, PartialOrd, PartialEq, Serialize)]
pub struct Field {
    pub key: &'static str,
    pub value: Value,
}

#[derive(Debug, Clone, PartialOrd, PartialEq, Deserialize, Serialize)]
pub enum Value {
    Float(f64),
    Int(i64),
    UInt(u64),
    Bool(bool),
    String(String),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Tag {
    pub fn new<S>(key: &'static str, value: S) -> Self
        where
            S: Into<String>,
        { /* ... */ }
}

impl Field {
    pub fn new<S>(key: &'static str, value: S) -> Self
        where
            S: Into<Value>,
        { /* ... */ }
}

