// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/snapshot.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug,
    Clone,
    Copy,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Deserialize,
    Serialize,
    Constructor,
    From,
)]
pub struct Snapshot<T>(pub T);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct SnapUpdates<Snapshot, Updates> {
    pub snapshot: Snapshot,
    pub updates: Updates,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Snapshot {
    pub fn value(&self) -> &T { /* ... */ }
    pub fn as_ref(&self) -> Snapshot<&T> { /* ... */ }
    pub fn map<F, N>(self, op: F) -> Snapshot<N>
        where
            F: Fn(T) -> N,
        { /* ... */ }
}

