// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/action/cancel_orders.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Trait that defines how the [`Engine`] cancels open order requests.
/// 
/// # Type Parameters
/// * `ExchangeKey` - Type used to identify an exchange (defaults to [`ExchangeIndex`]).
/// * `AssetKey` - Type used to identify an asset (defaults to [`AssetIndex`]).
/// * `InstrumentKey` - Type used to identify an instrument (defaults to [`InstrumentIndex`]).
pub trait CancelOrders<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
>
{
    /// Generates cancel order requests.
    ///
    /// Uses the provided [`InstrumentFilter`] to determine which orders to cancel.
    fn cancel_orders(
        &mut self,
        filter: &InstrumentFilter<ExchangeKey, AssetKey, InstrumentKey>,
    ) -> SendRequestsOutput<RequestCancel, ExchangeKey, InstrumentKey>;
}

