// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/book/l1.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// [`Binance`](super::super::Binance) real-time OrderBook Level1 (top of books) message.
/// 
/// ### Raw Payload Examples
/// #### BinanceSpot OrderBookL1
/// See docs: <https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-book-ticker-streams>
/// ```json
/// {
/// "u":22606535573,
/// "s":"ETHUSDT",
/// "b":"1215.27000000",
/// "B":"32.49110000",
/// "a":"1215.28000000",
/// "A":"13.93900000"
/// }
/// ```
/// 
/// #### BinanceFuturesUsd OrderBookL1
/// See docs: <https://binance-docs.github.io/apidocs/futures/en/#individual-symbol-book-ticker-streams>
/// ```json
/// {
/// "u":22606535573,
/// "s":"ETHUSDT",
/// "b":"1215.27000000",
/// "B":"32.49110000",
/// "a":"1215.28000000",
/// "A":"13.93900000"
/// }
/// ```
pub struct BinanceOrderBookL1 {
    #[serde(alias = "s", deserialize_with = "de_ob_l1_subscription_id")]
    pub subscription_id: SubscriptionId,
    #[serde(
        alias = "T",
        deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc",
        default = "Utc::now"
    )]
    pub time: DateTime<Utc>,
    #[serde(alias = "b", with = "rust_decimal::serde::str")]
    pub best_bid_price: Decimal,
    #[serde(alias = "B", with = "rust_decimal::serde::str")]
    pub best_bid_amount: Decimal,
    #[serde(alias = "a", with = "rust_decimal::serde::str")]
    pub best_ask_price: Decimal,
    #[serde(alias = "A", with = "rust_decimal::serde::str")]
    pub best_ask_amount: Decimal,
}

/// Deserialize a [`BinanceOrderBookL1`] "s" (eg/ "BTCUSDT") as the associated [`SubscriptionId`].
/// 
/// eg/ "@bookTicker|BTCUSDT"
pub fn de_ob_l1_subscription_id<'de, D>(deserializer: D) -> Result<SubscriptionId, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

