// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/rest/client.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
/// Configurable REST client capable of executing signed [`RestRequest`]s. Use this when
/// integrating APIs that require Http in order to interact with resources. Each API will require
/// a specific combination of [`Signer`](super::super::private::Signer), [`Mac`](hmac::Mac),
/// signature [`Encoder`](super::super::private::encoder::Encoder), and
/// [`HttpParser`].
pub struct RestClient<'a, Strategy, Parser> {
    /// HTTP [`reqwest::Client`] for executing signed [`reqwest::Request`]s.
    pub http_client: reqwest::Client,

    /// Base Url of the API being interacted with.
    pub base_url: Cow<'a, str>,

    /// [`RestRequest`] build strategy for the API being interacted with that implements
    /// [`BuildStrategy`].
    ///
    /// An authenticated [`RestClient`] will utilise API specific
    /// [`Signer`](super::super::private::Signer) logic, a hashable [`Mac`](hmac::Mac), and a
    /// signature [`Encoder`](super::super::private::encoder::Encoder). Where as a non authorised
    /// [`RestRequest`] may add any mandatory `reqwest` headers that are required.
    pub strategy: Strategy,

    /// [`HttpParser`] that deserialises [`RestRequest::Response`]s, and upon failure parses
    /// API errors returned from the server.
    pub parser: Parser,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl RestClient {
    /// Execute the provided [`RestRequest`].
    pub async fn execute<Request>(
            &self,
            request: Request,
        ) -> Result<(Request::Response, Metric), Parser::OutputError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Use the provided [`RestRequest`] to construct a signed Http [`reqwest::Request`].
    pub fn build<Request>(&self, request: Request) -> Result<reqwest::Request, SocketError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Execute the built [`reqwest::Request`] using the [`reqwest::Client`].
    /// 
    /// Measures and returns the Http request round trip duration.
    pub async fn measured_execution<Request>(
            &self,
            request: reqwest::Request,
        ) -> Result<(reqwest::StatusCode, Bytes, Metric), SocketError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Construct a new [`Self`] using the provided configuration.
    pub fn new<Url: Into<Cow<'a, str>>>(base_url: Url, strategy: Strategy, parser: Parser) -> Self { /* ... */ }
    /// Construct a new [`Self`] using the provided configuration and a pre-built
    /// [`reqwest::Client`].
    /// 
    /// Use this when you need custom client configuration (timeouts, connection
    /// pooling, TLS settings, etc.) instead of the defaults from
    /// [`reqwest::Client::new()`].
    pub fn with_http_client<Url: Into<Cow<'a, str>>>(
            base_url: Url,
            strategy: Strategy,
            parser: Parser,
            http_client: reqwest::Client,
        ) -> Self { /* ... */ }
}

