// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/state/builder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone)]
/// Builder utility for an [`EngineState`] instance.
pub struct EngineStateBuilder<'a, GlobalData, FnInstrumentData> {
    instruments: &'a IndexedInstruments,
    trading_state: Option<TradingState>,
    time_engine_start: Option<DateTime<Utc>>,
    global: GlobalData,
    balances: FnvHashMap<ExchangeAsset<AssetNameInternal>, Balance>,
    instrument_data_init: FnInstrumentData,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl EngineStateBuilder {
    /// Construct a new `EngineStateBuilder` with a layout derived from [`IndexedInstruments`].
    /// 
    /// Note that the rest of the [`EngineState`] data can be generated from defaults if that
    /// is all that is needed.
    /// 
    /// Note that `ConnectivityStates` will be generated with
    /// [`generate_empty_indexed_connectivity_states`], defaulting to `Health::Reconnecting`.
    pub fn new(
            instruments: &'a IndexedInstruments,
            global: GlobalData,
            instrument_data_init: FnInstrumentData,
        ) -> Self { /* ... */ }
    /// Optionally provide the initial `TradingState`.
    /// 
    /// Defaults to `TradingState::Disabled`.
    pub fn trading_state(self, value: TradingState) -> Self { /* ... */ }
    /// Optionally provide the `time_engine_start`.
    /// 
    /// Providing this is useful for back-test scenarios where the time should be seeded with a
    /// "historical" clock time (eg/ from first historical `MarketEvent`).
    /// 
    /// Defaults to `Utc::now`
    pub fn time_engine_start(self, value: DateTime<Utc>) -> Self { /* ... */ }
    /// Optionally provide initial exchange asset `Balance`s.
    /// 
    /// Useful for back-test scenarios where seeding EngineState with initial `Balance`s is
    /// required.
    /// 
    /// Note the internal implementation uses a `HashMap`, so duplicate
    /// `ExchangeAsset<AssetNameInternal>` keys are overwritten.
    pub fn balances<BalanceIter, KeyedBalance>(mut self, balances: BalanceIter) -> Self
        where
            BalanceIter: IntoIterator<Item = KeyedBalance>,
            KeyedBalance: Into<Keyed<ExchangeAsset<AssetNameInternal>, Balance>>,
        { /* ... */ }
    /// Use the builder data to generate the associated [`EngineState`].
    /// 
    /// If optional data is not provided (eg/ Balances), default values are used (eg/ zero Balance).
    pub fn build<InstrumentData>(self) -> EngineState<GlobalData, InstrumentData>
        where
            FnInstrumentData: Fn(
                &'a Keyed<InstrumentIndex, Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>,
            ) -> InstrumentData,
        { /* ... */ }
}

