// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/metric/drawdown/max.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize, Constructor)]
/// [`MaxDrawdown`] is the largest peak-to-trough decline of PnL (Portfolio, Strategy, Instrument),
/// or asset balance.
/// 
/// Max Drawdown is a measure of downside risk, with larger values indicating downside movements
/// could be volatile.
/// 
/// See documentation: <https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp>
pub struct MaxDrawdown(pub Drawdown);

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize, Constructor)]
/// [`MaxDrawdown`] generator.
pub struct MaxDrawdownGenerator {
    pub max: Option<MaxDrawdown>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MaxDrawdownGenerator {
    /// Initialise a [`MaxDrawdownGenerator`] from an initial [`Drawdown`].
    pub fn init(drawdown: Drawdown) -> Self { /* ... */ }
    /// Updates the internal [`MaxDrawdown`] using the latest next [`Drawdown`]. If the next
    /// drawdown is larger than the current [`MaxDrawdown`], it supersedes it.
    pub fn update(&mut self, next_drawdown: &Drawdown) { /* ... */ }
    /// Generate the current [`MaxDrawdown`], if one exists.
    pub fn generate(&self) -> Option<MaxDrawdown> { /* ... */ }
}

