// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/metric/drawdown/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize, Constructor)]
/// [`Drawdown`] is the peak-to-trough decline of a value during a specific period. Drawdown is
/// a measure of downside volatility.
/// 
/// Example use cases are:
/// - Portfolio PnL
/// - Strategy PnL
/// - Instrument PnL
/// - Asset equity
/// 
/// See documentation: <https://www.investopedia.com/terms/d/drawdown.asp>
pub struct Drawdown {
    pub value: Decimal,
    pub time_start: DateTime<Utc>,
    pub time_end: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize, Constructor)]
/// [`Drawdown`] generator.
/// 
/// See documentation: <https://www.investopedia.com/terms/d/drawdown.asp>
pub struct DrawdownGenerator {
    pub peak: Option<Decimal>,
    pub drawdown_max: Decimal,
    pub time_peak: Option<DateTime<Utc>>,
    pub time_now: DateTime<Utc>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl DrawdownGenerator {
    /// Initialise a [`DrawdownGenerator`] from an initial [`Timed`] value.
    pub fn init(point: Timed<Decimal>) -> Self { /* ... */ }
    /// Updates the internal [`DrawdownGenerator`] state using the latest [`Timed`] value.
    /// 
    /// If the drawdown period has ended (ie/ investment recovers from a trough back above the
    /// previous peak), the functions returns Some(Drawdown), else None is returned.
    pub fn update(&mut self, point: Timed<Decimal>) -> Option<Drawdown> { /* ... */ }
    /// Generates the current [`Drawdown`] at this instant, if it is non-zero.
    pub fn generate(&mut self) -> Option<Drawdown> { /* ... */ }
}

impl Drawdown {
    /// Time period of the [`Drawdown`].
    pub fn duration(&self) -> TimeDelta { /* ... */ }
}

