// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/map.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq)]
/// Indexed instrument map used to associate the internal Barter representation of instruments and
/// assets with the [`ExecutionClient`](super::client::ExecutionClient) representation.
/// 
/// Similarly, when the execution manager received an [`AccountEvent`](super::AccountEvent)
/// from the execution API, it needs to determine the internal representation of the associated
/// assets and instruments.
/// 
/// eg/ `InstrumentNameExchange("XBT-USDT")` <--> `InstrumentIndex(1)` <br>
/// eg/ `AssetNameExchange("XBT")` <--> `AssetIndex(1)`
pub struct ExecutionInstrumentMap {
    /// The exchange associated with this execution map.
    pub exchange: Keyed<ExchangeIndex, ExchangeId>,
    /// Collection of assets available by the engine with their
    /// exchange-specific representations. This holds all indexed assets.
    pub assets: FnvIndexSet<ExchangeAsset<Asset>>,
    /// Collection of instruments available by the engine. This holds all
    /// indexed instruments.
    pub instruments: FnvIndexSet<Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>,
    /// Map from exchange-specific asset names to internal asset indices for
    /// fast lookups.
    pub asset_names: FnvHashMap<AssetNameExchange, AssetIndex>,
    /// Map from exchange-specific instrument names to internal instrument
    /// indices for fast lookups.
    pub instrument_names: FnvHashMap<InstrumentNameExchange, InstrumentIndex>,
}

pub fn generate_execution_instrument_map(
    instruments: &IndexedInstruments,
    exchange: ExchangeId,
) -> Result<ExecutionInstrumentMap, IndexError> { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExecutionInstrumentMap {
    /// Construct a new [`Self`] using the provided indexed assets and instruments.
    pub fn new(
            exchange: Keyed<ExchangeIndex, ExchangeId>,
            instruments: &IndexedInstruments,
        ) -> Self { /* ... */ }
    pub fn exchange_assets(&self) -> impl Iterator<Item = &AssetNameExchange> { /* ... */ }
    pub fn exchange_instruments(&self) -> impl Iterator<Item = &InstrumentNameExchange> { /* ... */ }
    pub fn find_exchange_id(&self, exchange: ExchangeIndex) -> Result<ExchangeId, KeyError> { /* ... */ }
    pub fn find_exchange_index(&self, exchange: ExchangeId) -> Result<ExchangeIndex, IndexError> { /* ... */ }
    pub fn find_asset_name_exchange(
            &self,
            asset: AssetIndex,
        ) -> Result<&AssetNameExchange, KeyError> { /* ... */ }
    pub fn find_asset_index(&self, asset: &AssetNameExchange) -> Result<AssetIndex, IndexError> { /* ... */ }
    pub fn find_instrument_name_exchange(
            &self,
            instrument: InstrumentIndex,
        ) -> Result<&InstrumentNameExchange, KeyError> { /* ... */ }
    pub fn find_instrument_index(
            &self,
            instrument: &InstrumentNameExchange,
        ) -> Result<InstrumentIndex, IndexError> { /* ... */ }
}

