// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/gateio/spot/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// [`GateioSpot`] WebSocket server base url.
/// 
/// See docs: <https://www.gate.io/docs/developers/apiv4/ws/en/>
pub const WEBSOCKET_BASE_URL_GATEIO_SPOT: &str = todo!();

/// [`Gateio`] spot exchange.
pub type GateioSpot = Gateio<GateioServerSpot>;

#[derive(
    Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default, DeExchange, SerExchange,
)]
/// [`Gateio`] spot [`ExchangeServer`].
pub struct GateioServerSpot;

