// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/bulk/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug)]
/// Bulk archive download client for Hyperliquid perpetuals.
/// 
/// Downloads hourly LZ4-compressed JSON fill data from the public S3 bucket.
/// Requires the `x-amz-request-payer: requester` header (requester-pays bucket).
/// AWS credentials are loaded from environment variables for SigV4 signing.
pub struct HyperliquidBulkClient {
    pub(crate) client: reqwest::Client,
    pub(crate) config: BulkConfig,
    credentials: Option<AwsCredentials>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl HyperliquidBulkClient {
    /// Return a reference to the bulk download configuration.
    pub fn config(&self) -> &BulkConfig { /* ... */ }
    pub fn new() -> Self { /* ... */ }
    pub fn with_config(config: BulkConfig) -> Self { /* ... */ }
    /// Build a signed S3 GET request for the given URL.
    fn signed_request(&self, url: &str) -> reqwest::RequestBuilder { /* ... */ }
    /// Download and parse a single hour using streaming LZ4 decompression.
    /// 
    /// The HTTP response is streamed through `Lz4Decoder` and parsed line
    /// by line — no intermediate compressed or decompressed buffers are held
    /// in memory. On failure the full download+parse is retried.
    /// 
    /// Returns `Ok(None)` if 404.
    async fn download_and_parse_hour(
            &self,
            market: &str,
            date: NaiveDate,
            hour: u8,
        ) -> Result<Option<Vec<RestTrade>>, DataError> { /* ... */ }
    /// Download and parse all 24 hours of fill data for one day.
    async fn download_and_parse_trades(
            &self,
            market: &str,
            date: NaiveDate,
        ) -> Result<Option<Vec<RestTrade>>, DataError> { /* ... */ }
    /// Download and parse a single hour's multi-coin fill data.
    /// 
    /// Returns `Ok(Some(map))` with trades grouped by coin, `Ok(None)` on 404.
    /// Retries transient errors. Shared by both `fetch_day_trades_multi` and
    /// `stream_day_trades_multi`.
    async fn download_hour_multi(
            &self,
            date_str: &str,
            hour: u8,
        ) -> Result<Option<HashMap<String, Vec<RestTrade>>>, DataError> { /* ... */ }
    /// Fetch all coins' trades for a single day from the Hyperliquid S3 archive.
    /// 
    /// Returns `Ok(Some(HashMap<coin, trades>))` on success, `Ok(None)` if the date
    /// is not available (404), or `Err` on failure. Each S3 hourly file contains all
    /// coins — this method downloads all 24 hours and groups trades by coin.
    /// 
    /// Hours are processed sequentially to avoid holding multiple hours'
    /// data in memory simultaneously.
    pub async fn fetch_day_trades_multi(
            &self,
            date: NaiveDate,
        ) -> Result<Option<HashMap<String, Vec<RestTrade>>>, DataError> { /* ... */ }
    /// Stream all coins' trades for a single day through a channel.
    /// 
    /// Each batch is a `(coin, Vec<RestTrade>)` tuple. Hours are processed
    /// sequentially to avoid holding multiple hours in memory. Each hour's
    /// trades are grouped by coin and sent as separate batches.
    /// 
    /// Returns `Ok(true)` if any hour had data, `Ok(false)` if all were 404.
    pub async fn stream_day_trades_multi(
            &self,
            date: NaiveDate,
            tx: &tokio::sync::mpsc::Sender<(String, Vec<RestTrade>)>,
        ) -> Result<bool, DataError> { /* ... */ }
    /// Stream trades for a single day through a channel in batches.
    /// 
    /// Downloads all 24 hourly LZ4 files concurrently (same as
    /// [`download_and_parse_trades`]), but instead of collecting into a single
    /// `Vec` the trades are sent through `tx` in batches of
    /// [`DEFAULT_BATCH_SIZE`].
    /// 
    /// Returns `Ok(true)` if any hour had data, `Ok(false)` if all were 404.
    async fn stream_and_parse_trades(
            &self,
            market: &str,
            date: NaiveDate,
            tx: &tokio::sync::mpsc::Sender<Vec<RestTrade>>,
        ) -> Result<bool, DataError> { /* ... */ }
}

