// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/bulk/s3_signer.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Clone)]
/// AWS credentials loaded from environment.
pub struct AwsCredentials {
    pub access_key: String,
    pub secret_key: String,
    pub session_token: Option<String>,
}

#[non_exhaustive]
#[derive(Debug)]
/// Headers produced by SigV4 signing that must be added to the request.
pub struct SignedHeaders {
    pub authorization: String,
    pub x_amz_date: String,
    pub x_amz_content_sha256: &'static str,
    pub x_amz_security_token: Option<String>,
}

/// Sign an S3 GET request using AWS SigV4.
/// 
/// `url` must be a full `https://bucket.s3.amazonaws.com/path` URL.
/// Region is extracted as `us-east-1` (Hyperliquid bucket location).
pub fn sign_s3_get(url: &str, creds: &AwsCredentials, region: &str) -> SignedHeaders { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AwsCredentials {
    /// Load credentials using the standard AWS resolution order:
    /// 1. Environment variables (`AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`)
    /// 2. Shared credentials file (`~/.aws/credentials`, `[default]` profile)
    pub fn from_env() -> Option<Self> { /* ... */ }
    fn from_env_vars() -> Option<Self> { /* ... */ }
    fn from_credentials_file() -> Option<Self> { /* ... */ }
}

