// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/summary/display.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl TradingSummary {
    pub fn print_summary(&self) { /* ... */ }
    fn title_table(&self) -> Table { /* ... */ }
    pub fn instrument_table(&self) -> Table { /* ... */ }
    fn add_instrument_metric_row<F>(&self, table: &mut Table, label: &str, format_value: F)
        where
            F: Fn(&TearSheet<Interval>) -> String,
        { /* ... */ }
    pub fn asset_table(&self) -> Table { /* ... */ }
    fn add_asset_metric_row<F>(&self, table: &mut Table, label: &str, format_value: F)
        where
            F: Fn(&TearSheetAsset) -> String,
        { /* ... */ }
}

