// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/summary/pnl.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize)]
/// Records Profit and Loss (PnL) data.
/// 
/// Includes tracking of:
/// - Raw PnL.
/// - Statistical summaries of returns for all closed positions (wins and losses combined)
/// - Statistical summaries of returns for all losing closed positions (useful for downside risk analysis).
/// 
/// # Asset Denomination
/// The raw PnL values can be denominated in different assets depending on the context:
/// - For Instrument PnL:
/// - Usually denominated in the quote asset (e.g., USDT for BTC-USDT spot)
/// - For derivatives, may be in the settlement asset if different from quote
/// - For Portfolio/Strategy PnL:
/// - Can be denominated in any chosen asset for cross-instrument aggregation
pub struct PnLReturns {
    /// Raw PnL.
    ///
    /// For Instrument PnL, this is most likely denominated in "quote asset" units. For example,
    /// btc_usdt  spot PnL would be in usdt. However, in some derivative cases the
    /// "settlement asset" could be different from the "quote asset.
    ///
    /// For Portfolio and Strategy PnL, this could be denominated in any asset chosen to aggregate
    /// PnL across different instruments.
    pub pnl_raw: Decimal,

    /// PnL returns statistical summary for wins and losses.
    pub total: DataSetSummary,

    /// PnL returns statistical summary for losses only.
    pub losses: DataSetSummary,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl PnLReturns {
    /// Update the `PnLReturns` from the next [`PositionExited`].
    pub fn update<AssetKey, InstrumentKey>(
            &mut self,
            position: &PositionExited<AssetKey, InstrumentKey>,
        ) { /* ... */ }
}

