// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/execution_tx.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Collection of [`ExecutionRequest`] [`Tx`]s for each
/// exchange [`ExecutionManager`](crate::execution::manager::ExecutionManager).
/// 
/// Facilitates the routing of execution requests in a multi or single exchange trading system.
pub trait ExecutionTxMap<ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex> {
    type ExecutionTx: Tx<Item = ExecutionRequest<ExchangeKey, InstrumentKey>>;

    /// Attempt to find the [`ExecutionRequest`] [`Tx`] for the provided `ExchangeKey`.
    fn find(&self, exchange: &ExchangeKey) -> Result<&Self::ExecutionTx, UnrecoverableEngineError>;

    /// Returns an `Iterator` of all active [`ExecutionRequest`] [`Tx`]s.
    fn iter<'a>(&'a self) -> impl Iterator<Item = &'a Self::ExecutionTx>
    where
        Self::ExecutionTx: 'a;
}

#[derive(Debug)]
/// A map of exchange transmitters that efficiently routes execution requests to exchange-specific
/// transmitter channels.
/// 
/// `FnvIndexMap` of [`ExecutionRequest`] [`Tx`]s for each exchange.
/// 
/// Facilitates the routing of execution requests in a multi exchange trading system.
/// 
/// Note that a transmitter for an exchange is optional. This handles the case where instruments
/// for an exchange may be tracked by the trading system, but not trading on.
/// 
/// **Without this optional transmitter the [`ExchangeIndex`]s would not be valid.**.
pub struct MultiExchangeTxMap<Tx = UnboundedTx<ExecutionRequest>>(
    FnvIndexMap<ExchangeId, Option<Tx>>,
);

