// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/backtest/summary.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
/// Container for multiple [`BacktestSummary`]s and associated multi backtest metadata.
pub struct MultiBacktestSummary<Interval> {
    /// Number of backtests run in this batch.
    pub num_backtests: usize,
    /// Total execution time for all backtests.
    pub duration: Duration,
    /// Collection of `BacktestSummary`s.
    pub summaries: Vec<BacktestSummary<Interval>>,
}

#[derive(Debug, PartialEq)]
/// Single backtest `TradingSummary` and associated metadata.
pub struct BacktestSummary<Interval> {
    /// [`BacktestArgsDynamic`](super::BacktestArgsDynamic) unique identifier that was input for the backtest.
    pub id: SmolStr,
    /// Risk-free return rate used for performance metrics.
    pub risk_free_return: Decimal,
    /// Performance metrics and statistics from the backtest simulated trading.
    pub trading_summary: TradingSummary<Interval>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MultiBacktestSummary {
    /// Create a new `MultiBacktestSummary` with the provided data.
    pub fn new<SummaryIter>(duration: Duration, summary_iter: SummaryIter) -> Self
        where
            SummaryIter: IntoIterator<Item = BacktestSummary<Interval>>,
        { /* ... */ }
}

