// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/gateio/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Type alias for a [`Gateio`](super::Gateio) candlestick/kline WebSocket message.
/// 
/// Used by all GateIO server variants (spot, futures, perpetuals, options).
pub type GateioKline = GateioMessage<GateioKlineInner>;

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// [`Gateio`](super::Gateio) candlestick/kline inner data.
/// 
/// ### Raw Payload Examples
/// #### Spot Candlestick
/// See docs: <https://www.gate.io/docs/developers/apiv4/ws/en/#candlesticks-channel>
/// ```json
/// {
/// "t": "1672502400",
/// "v": "12.345",
/// "c": "16855.5",
/// "h": "16860",
/// "l": "16845",
/// "o": "16850",
/// "n": "1m_BTC_USDT",
/// "a": "208000"
/// }
/// ```
pub struct GateioKlineInner {
    /// Timestamp in unix seconds (as string).
    #[serde(rename = "t", deserialize_with = "barter_integration::de::de_str")]
    pub timestamp: i64,

    /// Open price.
    #[serde(rename = "o", deserialize_with = "barter_integration::de::de_str")]
    pub open: f64,

    /// High price.
    #[serde(rename = "h", deserialize_with = "barter_integration::de::de_str")]
    pub high: f64,

    /// Low price.
    #[serde(rename = "l", deserialize_with = "barter_integration::de::de_str")]
    pub low: f64,

    /// Close price.
    #[serde(rename = "c", deserialize_with = "barter_integration::de::de_str")]
    pub close: f64,

    /// Base asset volume.
    #[serde(rename = "v", deserialize_with = "barter_integration::de::de_str")]
    pub volume: f64,

    /// Name identifier (e.g., "1m_BTC_USDT").
    #[serde(rename = "n")]
    pub name: String,

    /// Quote asset volume / amount.
    #[serde(rename = "a", deserialize_with = "barter_integration::de::de_str")]
    pub quote_volume: f64,
}

