// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/gateio/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convert a normalised [`Interval`] to the GateIO API interval string.
/// 
/// GateIO supports: 10s, 1m, 5m, 15m, 30m, 1h, 4h, 8h, 1d, 7d, 30d.
pub(crate) fn gateio_interval(interval: Interval) -> Result<&'static str, DataError> { /* ... */ }

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
/// Generic [`Gateio<Server>`](Gateio) exchange.
/// 
/// ### Notes
/// A `Server` [`ExchangeServer`] implementations exists for
/// [`GateioSpot`](spot::GateioSpot), [`GateioPerpetualUsdt`](perpetual::GateioPerpetualsUsd) and
/// [`GateioPerpetualBtc`](perpetual::GateioPerpetualsBtc).
pub struct Gateio<Server> {
    server: PhantomData<Server>,
}

