// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/execution/builder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[allow(missing_debug_implementations)]
/// Full execution infrastructure builder.
/// 
/// Add Mock and Live [`ExecutionClient`] configurations and let the builder set up the required
/// infrastructure.
/// 
/// Once you have added all the configurations, call [`ExecutionBuilder::build`] to return the
/// full [`ExecutionBuild`]. Then calling [`ExecutionBuild::init`] will then initialise
/// the built infrastructure.
/// 
/// Handles:
/// - Building mock execution managers (mocks a specific exchange internally via the [`MockExchange`]).
/// - Building live execution managers, setting up an external connection to each exchange.
/// - Constructs a [`MultiExchangeTxMap`] with an entry for each mock/live execution manager.
/// - Combines all exchange account streams into a unified [`AccountStreamEvent`] `Stream`.
pub struct ExecutionBuilder<'a> {
    instruments: &'a IndexedInstruments,
    execution_txs: FnvHashMap<ExchangeId, (ExchangeIndex, UnboundedTx<ExecutionRequest>)>,
    merged_channel: Channel<AccountStreamEvent<ExchangeIndex, AssetIndex, InstrumentIndex>>,
    mock_exchange_futures: Vec<RunFuture>,
    execution_init_futures: Vec<ExecutionInitFuture>,
}

#[allow(missing_debug_implementations)]
/// Container holding execution infrastructure components ready to be initialised.
/// 
/// Call [`ExecutionBuild::init`] to run all the required execution component futures on tokio
/// tasks - returns the [`MultiExchangeTxMap`] and multi-exchange [`AccountStreamEvent`] stream.
pub struct ExecutionBuild {
    pub execution_tx_map: MultiExchangeTxMap,
    pub account_channel: Channel<AccountStreamEvent>,
    pub futures: ExecutionBuildFutures,
}

#[allow(missing_debug_implementations)]
pub struct ExecutionBuildFutures {
    pub mock_exchange_run_futures: Vec<RunFuture>,
    pub execution_init_futures: Vec<ExecutionInitFuture>,
}

#[allow(missing_debug_implementations)]
pub struct ExecutionHandles {
    pub mock_exchanges: Vec<JoinHandle<()>>,
    pub managers: Vec<JoinHandle<()>>,
    pub account_to_engines: Vec<JoinHandle<()>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExecutionBuild {
    /// Initialises all execution components on the current tokio runtime.
    /// 
    /// This method:
    /// - Spawns [`MockExchange`] runners tokio tasks.
    /// - Initialises all [`ExecutionManager`]s and their AccountStreams.
    /// - Returns the `MultiExchangeTxMap` and multi-exchange AccountStream.
    pub async fn init(self) -> Result<Execution, BarterError> { /* ... */ }
    /// Initialises all execution components on the provided tokio runtime.
    /// 
    /// Use this method if you want more control over which tokio runtime handles running
    /// execution components.
    /// 
    /// This method:
    /// - Spawns [`MockExchange`] runners tokio tasks.
    /// - Initialises all [`ExecutionManager`]s and their AccountStreams.
    /// - Returns the `MultiExchangeTxMap` and multi-exchange AccountStream.
    pub async fn init_with_runtime(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<Execution, BarterError> { /* ... */ }
    async fn init_internal(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<Execution, BarterError> { /* ... */ }
}

impl ExecutionBuilder {
    /// Construct a new `ExecutionBuilder` using the provided `IndexedInstruments`.
    pub fn new(instruments: &'a IndexedInstruments) -> Self { /* ... */ }
    /// Adds an [`ExecutionManager`] for a mocked exchange, setting up a [`MockExchange`]
    /// internally.
    /// 
    /// The provided [`MockExecutionConfig`] is used to configure the [`MockExchange`] and provide
    /// the initial account state.
    pub fn add_mock<Clock>(
            mut self,
            config: MockExecutionConfig,
            clock: Clock,
        ) -> Result<Self, BarterError>
        where
            Clock: EngineClock + Clone + Send + Sync + 'static,
        { /* ... */ }
    fn init_mock_exchange(
            &self,
            config: MockExecutionConfig,
            request_rx: mpsc::UnboundedReceiver<MockExchangeRequest>,
            event_tx: broadcast::Sender<UnindexedAccountEvent>,
        ) -> RunFuture { /* ... */ }
    /// Adds an [`ExecutionManager`] for a live exchange.
    pub fn add_live<Client>(
            self,
            config: Client::Config,
            request_timeout: Duration,
        ) -> Result<Self, BarterError>
        where
            Client: ExecutionClient + Send + Sync + 'static,
            Client::AccountStream: Send,
            Client::Config: Send,
        { /* ... */ }
    fn add_execution<Client>(
            mut self,
            exchange: ExchangeId,
            config: Client::Config,
            request_timeout: Duration,
        ) -> Result<Self, BarterError>
        where
            Client: ExecutionClient + Send + Sync + 'static,
            Client::AccountStream: Send,
            Client::Config: Send,
        { /* ... */ }
    /// Consume this `ExecutionBuilder` and build a full [`ExecutionBuild`] containing all the
    /// [`ExecutionManager`] (mock & live) and [`MockExchange`] futures.
    /// 
    /// **For most users, calling [`ExecutionBuild::init`] after this is satisfactory.**
    /// 
    /// If you want more control over what runtime drives the futures to completion, you can
    /// call [`ExecutionBuild::init_with_runtime`].
    pub fn build(mut self) -> ExecutionBuild { /* ... */ }
}

impl ExecutionBuildFutures {
    /// Initialises all execution components on the current tokio runtime.
    /// 
    /// This method:
    /// - Spawns [`MockExchange`] runner tokio tasks.
    /// - Initialises all [`ExecutionManager`]s and their AccountStreams.
    /// - Spawns tokio tasks to forward AccountStreams to multi-exchange AccountStream
    pub async fn init(self) -> Result<ExecutionHandles, BarterError> { /* ... */ }
    /// Initialises all execution components on the provided tokio runtime.
    /// 
    /// Use this method if you want more control over which tokio runtime handles running
    /// execution components.
    /// 
    /// This method:
    /// - Spawns [`MockExchange`] runner tokio tasks.
    /// - Initialises all [`ExecutionManager`]s and their AccountStreams.
    /// - Spawns tokio tasks to forward AccountStreams to multi-exchange AccountStream
    pub async fn init_with_runtime(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<ExecutionHandles, BarterError> { /* ... */ }
    async fn init_internal(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<ExecutionHandles, BarterError> { /* ... */ }
}

