// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/execution/error.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all errors generated by the execution link.
pub enum ExecutionError {
    /// Indicates an invalid execution manager configuration.
    #[error("ExecutionManager config invalid: {0}")]
    Config(String),

    /// Represents an error that occurred whilst mapping exchange-centric data structures into
    /// their indexed counterparts.
    #[error("IndexError: {0}")]
    Index(#[from] IndexError),

    /// Represents all errors produced by an
    /// [`ExecutionClient`](barter_execution::client::ExecutionClient).
    #[error("{0}")]
    Client(#[from] ClientError),
}

