// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/execution/manager.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Constructor)]
/// Per-exchange execution manager that actions order requests from the Engine and forwards back
/// responses.
/// 
/// Processes indexed Engine [`ExecutionRequest`]s by:
/// - Transforming the requests to use the associated exchange's asset and instrument names.
/// - Issues the request via it's associated exchange [`ExecutionClient`],
/// - Tracks requests and returns timeouts to the Engine where necessary.
pub struct ExecutionManager<RequestStream, Client> {
    /// `Stream` of incoming Engine [`ExecutionRequest`]s.
    pub request_stream: RequestStream,

    /// Maximum `Duration` to wait for execution request responses from the [`ExecutionClient`].
    pub request_timeout: std::time::Duration,

    /// Transmitter for sending execution request responses back to the Engine.
    pub response_tx: UnboundedTx<AccountStreamEvent<ExchangeIndex, AssetIndex, InstrumentIndex>>,

    /// Exchange-specific [`ExecutionClient`] for executing orders.
    pub client: Arc<Client>,

    /// Mapper for converting between exchange-specific and index identifiers.
    ///
    /// For example, `InstrumentNameExchange` -> `InstrumentIndex`.
    pub indexer: AccountEventIndexer,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExecutionManager {
    /// Initialises a new `ExecutionManager` and it's associated AccountStream.
    /// 
    /// The first item of the AccountStream will be a full account snapshot.
    pub async fn init(
            request_stream: RequestStream,
            request_timeout: std::time::Duration,
            client: Arc<Client>,
            indexer: AccountEventIndexer,
            reconnect_policy: ReconnectionBackoffPolicy,
        ) -> Result<(Self, impl Stream<Item = AccountStreamEvent> + Send), ExecutionError> { /* ... */ }
    fn determine_account_stream_key(
            instrument_map: &Arc<ExecutionInstrumentMap>,
        ) -> Result<StreamKey, ExecutionError> { /* ... */ }
    async fn fetch_indexed_account_snapshot(
            client: &Arc<Client>,
            indexer: &AccountEventIndexer,
            assets: &[AssetNameExchange],
            instruments: &[InstrumentNameExchange],
        ) -> Result<AccountEvent, ExecutionError> { /* ... */ }
    async fn init_indexed_account_stream(
            client: &Arc<Client>,
            indexer: AccountEventIndexer,
            assets: &[AssetNameExchange],
            instruments: &[InstrumentNameExchange],
        ) -> Result<impl Stream<Item = AccountEvent> + use<RequestStream, Client>, ExecutionError> { /* ... */ }
    /// Run the `ExecutionManager`, processing execution requests and forwarding back responses via
    /// the AccountStream.
    pub async fn run(mut self) { /* ... */ }
    fn process_cancel_response(
            &self,
            order: UnindexedOrderResponseCancel,
        ) -> Result<AccountStreamEvent, IndexError> { /* ... */ }
    fn process_cancel_timeout(
            order: OrderRequestCancel<ExchangeIndex, InstrumentIndex>,
        ) -> AccountStreamEvent { /* ... */ }
    fn process_open_response(
            &self,
            order: Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
        ) -> Result<AccountStreamEvent, IndexError> { /* ... */ }
    fn process_open_timeout(
            order: OrderRequestOpen<ExchangeIndex, InstrumentIndex>,
        ) -> AccountStreamEvent { /* ... */ }
}

