// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/execution/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convenient type alias that represents a [`reconnect::Event`] produced by the [`AccountEvent`]
/// stream.
pub type AccountStreamEvent<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> = reconnect::Event<ExchangeId, AccountEvent<ExchangeKey, AssetKey, InstrumentKey>>;

#[allow(missing_debug_implementations)]
/// Initialised [`ExecutionBuild`](builder::ExecutionBuild).
/// 
/// Contains execution component task handles as well as
/// [`ExecutionRequest`](request::ExecutionRequest) and [`AccountStreamEvent`] channels.
pub struct Execution {
    pub execution_txs: MultiExchangeTxMap,
    pub account_channel: Channel<AccountStreamEvent>,
    pub handles: ExecutionHandles,
}

