// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/builder/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Communicative type alias representing the [`Future`] result of a [`Subscription`] validation
/// call generated whilst executing [`StreamBuilder::subscribe`].
pub type SubscribeFuture = Pin<Box<dyn Future<Output = Result<(), DataError>>>>;

#[derive(Default)]
/// Builder to configure and initialise a [`Streams<MarketEvent<SubscriptionKind::Event>`](Streams) instance
/// for a specific [`SubscriptionKind`].
pub struct StreamBuilder<InstrumentKey, Kind>
where
    Kind: SubscriptionKind,
{
    pub channels: HashMap<ExchangeId, Channel<MarketStreamResult<InstrumentKey, Kind::Event>>>,
    pub futures: Vec<SubscribeFuture>,
    /// Type-erased handles collected during `subscribe()` calls.
    ///
    /// `Box<dyn Any>` is required here (unlike `DynamicStreams` which uses `Box<dyn DynHandle>`)
    /// because each `subscribe()` call may introduce a different `Instrument` type, making it
    /// impossible to name a single `DynHandle<Instrument>` trait object for the collection.
    pub handles: Arc<Mutex<Vec<(ExchangeId, Box<dyn Any + Send + Sync>)>>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl StreamBuilder {
    /// Construct a new [`Self`].
    pub fn new() -> Self { /* ... */ }
    /// Add a collection of [`Subscription`]s to the [`StreamBuilder`] that will be actioned on
    /// a distinct [`WebSocket`](barter_integration::protocol::websocket::WebSocket) connection.
    /// 
    /// Note that [`Subscription`]s are not actioned until the
    /// [`init()`](StreamBuilder::init()) method is invoked.
    pub fn subscribe<SubIter, Sub, Exchange, Instrument>(mut self, subscriptions: SubIter) -> Self
        where
            SubIter: IntoIterator<Item = Sub>,
            Sub: Into<Subscription<Exchange, Instrument, Kind>>,
            Exchange: StreamSelector<Instrument, Kind> + Ord + Send + Sync + 'static,
            Instrument: InstrumentData<Key = InstrumentKey> + Ord + Display + 'static,
            Instrument::Key: Debug + Clone + Send + Sync + 'static,
            Kind: Ord + Display + Send + Sync + 'static,
            Kind::Event: Clone + Send + 'static,
            Subscription<Exchange, Instrument, Kind>: Identifier<Exchange::Channel> + 'static,
        { /* ... */ }
    #[tracing::instrument(skip_all)]
    /// Spawn a [`MarketStreamResult<SubscriptionKind::Event>`](MarketStreamResult) consumer loop
    /// for each collection of [`Subscription`]s added to [`StreamBuilder`] via the
    /// [`subscribe()`](StreamBuilder::subscribe()) method.
    /// 
    /// Each consumer loop distributes consumed [`MarketStreamResult`] to
    /// the [`Streams`] `HashMap` returned by this method.
    pub async fn init(
            self,
        ) -> Result<
            (
                Streams<MarketStreamResult<InstrumentKey, Kind::Event>>,
                Vec<(ExchangeId, Box<dyn Any + Send + Sync>)>,
            ),
            DataError,
        > { /* ... */ }
}

