// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Serialize)]
/// Hyperliquid real-time kline/candlestick message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
/// ```json
/// {
/// "channel": "candle",
/// "data": {
/// "t": 1672502400000, "T": 1672502459999,
/// "s": "ETH", "i": "1m",
/// "o": "1850.0", "h": "1860.0", "l": "1845.0", "c": "1855.5",
/// "v": "12.345", "n": 150
/// }
/// }
/// ```
pub struct HyperliquidKline {
    pub subscription_id: SubscriptionId,
    pub candle: HyperliquidCandle,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Inner candle data from the Hyperliquid `"data"` field.
pub struct HyperliquidCandle {
    /// Kline open time (epoch ms).
    #[serde(alias = "t")]
    pub open_time: u64,

    /// Kline close time (epoch ms).
    #[serde(alias = "T")]
    pub close_time: u64,

    /// Coin symbol (e.g., "ETH").
    #[serde(alias = "s")]
    pub coin: String,

    /// Candle interval (e.g., "1m", "1h").
    #[serde(alias = "i")]
    pub interval: String,

    /// Open price.
    #[serde(alias = "o")]
    pub open: String,

    /// High price.
    #[serde(alias = "h")]
    pub high: String,

    /// Low price.
    #[serde(alias = "l")]
    pub low: String,

    /// Close price.
    #[serde(alias = "c")]
    pub close: String,

    /// Base asset volume.
    #[serde(alias = "v")]
    pub volume: String,

    /// Number of trades.
    #[serde(alias = "n")]
    pub trade_count: u64,
}

