// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/channel.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Serialize)]
/// Type that defines how to translate a Barter [`Subscription`] into a
/// [`Hyperliquid`] channel to be subscribed to.
/// 
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
pub struct HyperliquidChannel(pub(crate) SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl HyperliquidChannel {
    /// [`Hyperliquid`] real-time trades channel.
    /// 
    /// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
    pub const TRADES: Self = todo!();
    /// [`Hyperliquid`] L2 orderbook channel.
    /// 
    /// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
    pub const L2_BOOK: Self = todo!();
    /// [`Hyperliquid`] real-time candles channel.
    /// 
    /// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
    pub fn candles(interval: Interval) -> Self { /* ... */ }
}

