// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convert a normalised [`Interval`] to the Hyperliquid API interval string.
/// 
/// Hyperliquid supports all standard intervals.
pub fn hyperliquid_interval(interval: Interval) -> Result<&'static str, DataError> { /* ... */ }

/// [`Hyperliquid`] server base url.
/// 
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
pub const BASE_URL_HYPERLIQUID: &str = todo!();

/// [`Hyperliquid`] server [`PingInterval`] duration.
pub const PING_INTERVAL_HYPERLIQUID: Duration = todo!();

#[derive(
    Copy,
    Clone,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Debug,
    Default,
    Display,
    DeExchange,
    SerExchange,
)]
/// [`Hyperliquid`] exchange.
/// 
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
pub struct Hyperliquid;

