// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/subscription.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Hyperliquid`](super::Hyperliquid) WebSocket subscription response.
/// 
/// ### Raw Payload Examples
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
/// #### Subscription Success
/// ```json
/// {
/// "channel": "subscriptionResponse",
/// "data": { "method": "subscribe", "subscription": { "type": "trades", "coin": "BTC" } }
/// }
/// ```
pub struct HyperliquidSubResponse {
    pub channel: String,
}

