// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Serialize)]
/// [`Hyperliquid`](super::Hyperliquid) real-time trades WebSocket message.
/// 
/// Wraps a batch of [`HyperliquidTrade`]s along with the derived [`SubscriptionId`].
/// 
/// ### Raw Payload Examples
/// See docs: <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket>
/// ```json
/// {
/// "channel": "trades",
/// "data": [
/// {
/// "coin": "ETH",
/// "side": "B",
/// "px": "1850.5",
/// "sz": "0.1",
/// "time": 1672502400000,
/// "tid": 12345
/// }
/// ]
/// }
/// ```
pub struct HyperliquidTrades {
    pub subscription_id: SubscriptionId,
    pub trades: Vec<HyperliquidTrade>,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Individual [`Hyperliquid`](super::Hyperliquid) trade within a [`HyperliquidTrades`] message.
pub struct HyperliquidTrade {
    pub coin: String,
    pub side: String,
    pub px: String,
    pub sz: String,
    pub time: u64,
    pub tid: u64,
}

