// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/okx/spot/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// [`OkxSpot`] WebSocket server base url.
/// 
/// See docs: <https://www.okx.com/docs-v5/en/#overview-api-resources-and-support>
pub const WEBSOCKET_BASE_URL_OKX_SPOT: &str = todo!();

/// [`Okx`] spot exchange.
pub type OkxSpot = Okx<OkxServerSpot>;

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
/// [`Okx`] spot [`ExchangeServer`].
pub struct OkxServerSpot;

