// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/index/builder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Default)]
pub struct IndexedInstrumentsBuilder {
    exchanges: Vec<ExchangeId>,
    instruments: Vec<Instrument<ExchangeId, Asset>>,
    assets: Vec<ExchangeAsset<Asset>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl IndexedInstrumentsBuilder {
    pub fn new() -> Self { /* ... */ }
    pub fn add_instrument(mut self, instrument: Instrument<ExchangeId, Asset>) -> Self { /* ... */ }
    pub fn build(mut self) -> IndexedInstruments { /* ... */ }
}

