// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/metric/rate_of_return.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize)]
/// Represents a Rate of Return value over a specific [`TimeInterval`].
/// 
/// Rate of Return measures the percentage change in value over a time period.
/// Unlike risk-adjusted metrics, returns scale linearly with time.
/// 
/// See docs: <https://www.investopedia.com/terms/r/rateofreturn.asp>
pub struct RateOfReturn<Interval> {
    pub value: Decimal,
    pub interval: Interval,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl RateOfReturn {
    /// Calculate the [`RateOfReturn`] over the provided [`TimeInterval`].
    pub fn calculate(mean_return: Decimal, returns_period: Interval) -> Self { /* ... */ }
    /// Scale the [`RateOfReturn`] from the current [`TimeInterval`] to the provided
    /// [`TimeInterval`].
    /// 
    /// Unlike risk metrics which use square root scaling, [`RateOfReturn`] scales linearly
    /// with time.
    /// 
    /// For example, a 1% daily return scales to approximately 252% annual return (not √252%).
    /// 
    /// This assumes simple interest rather than compound interest.
    pub fn scale<TargetInterval>(self, target: TargetInterval) -> RateOfReturn<TargetInterval>
        where
            TargetInterval: TimeInterval,
        { /* ... */ }
}

