// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/statistic/metric/sharpe.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Default, Deserialize, Serialize)]
/// Represents a Sharpe Ratio value over a specific [`TimeInterval`].
/// 
/// Sharpe Ratio measures the risk-adjusted return of an investment by comparing
/// its excess returns (over risk-free rate) to its standard deviation.
/// 
/// See docs: <https://www.investopedia.com/articles/07/sharpe_ratio.asp>
pub struct SharpeRatio<Interval> {
    pub value: Decimal,
    pub interval: Interval,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl SharpeRatio {
    /// Calculate the [`SharpeRatio`] over the provided [`TimeInterval`].
    pub fn calculate(
            risk_free_return: Decimal,
            mean_return: Decimal,
            std_dev_returns: Decimal,
            returns_period: Interval,
        ) -> Self { /* ... */ }
    /// Scale the [`SharpeRatio`] from the current [`TimeInterval`] to the provided [`TimeInterval`].
    /// 
    /// This scaling assumed the returns are independently and identically distributed (IID).
    pub fn scale<TargetInterval>(self, target: TargetInterval) -> SharpeRatio<TargetInterval>
        where
            TargetInterval: TimeInterval,
        { /* ... */ }
}

