// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/kraken/book/l1.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Terse type alias for a Kraken v2 ticker (L1 best bid/ask) WebSocket message.
pub type KrakenOrderBookL1 = KrakenMessage<KrakenTickerPayload>;

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// Kraken v2 ticker data message.
/// 
/// ### Raw Payload Example
/// ```json
/// {
/// "channel": "ticker",
/// "type": "update",
/// "data": [{
/// "symbol": "BTC/USD",
/// "bid": 66650.0,
/// "bid_qty": 740.0,
/// "ask": 66651.0,
/// "ask_qty": 1361.44,
/// "timestamp": "2026-03-27T09:04:31.742648Z"
/// }]
/// }
/// ```
pub struct KrakenTickerPayload {
    pub channel: String,
    #[serde(rename = "type")]
    pub msg_type: String,
    pub data: Vec<KrakenTickerData>,
}

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// A single Kraken v2 ticker snapshot.
pub struct KrakenTickerData {
    pub symbol: String,
    pub bid: f64,
    pub bid_qty: f64,
    pub ask: f64,
    pub ask_qty: f64,
    #[serde(default)]
    pub last: f64,
    pub timestamp: DateTime<Utc>,
}

