// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/asset/name.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Barter lowercase `SmolStr` representation for an [`Asset`](super::Asset) - not unique across
/// exchanges.
/// 
/// This may or may not be different from an execution's representation.
/// 
/// For example, some exchanges may refer to "btc" as "xbt".
pub struct AssetNameInternal(SmolStr);

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Exchange `SmolStr` representation for an [`Asset`](super::Asset) - not unique across exchanges.
/// 
/// For example: `AssetNameExchange("XBT")`, which is distinct from the internal representation
/// of the asset, such as `AssetIndex(1)` or `AssetNameInternal("btc")`.
pub struct AssetNameExchange(SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AssetNameInternal {
    /// Construct a new lowercase [`Self`] from the provided `Into<SmolStr>`.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Return the internal asset `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

impl AssetNameExchange {
    /// Construct a new [`Self`] from the provided `Into<SmolStr>`.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Return the execution asset `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

