// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Binance real-time kline/candlestick message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-streams>
/// ```json
/// {
/// "e":"kline","E":1672515782136,"s":"BTCUSDT",
/// "k":{
/// "t":1672515780000,"T":1672515839999,
/// "s":"BTCUSDT","i":"1m",
/// "o":"16850.00","c":"16855.50","h":"16860.00","l":"16845.00",
/// "v":"12.345","q":"208000.00","n":150,
/// "x":false
/// }
/// }
/// ```
pub struct BinanceKline {
    #[serde(alias = "k")]
    pub kline: BinanceKlineData,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Inner kline data from the Binance `"k"` field.
pub struct BinanceKlineData {
    /// Symbol (e.g., "BTCUSDT").
    #[serde(alias = "s")]
    pub symbol: String,

    /// Interval (e.g., "1m", "1h").
    #[serde(alias = "i")]
    pub interval: String,

    /// Kline open time (epoch ms).
    #[serde(
        alias = "t",
        deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc"
    )]
    pub open_time: DateTime<Utc>,

    /// Kline close time (epoch ms).
    #[serde(
        alias = "T",
        deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc"
    )]
    pub close_time: DateTime<Utc>,

    /// Open price.
    #[serde(alias = "o", deserialize_with = "barter_integration::de::de_str")]
    pub open: f64,

    /// High price.
    #[serde(alias = "h", deserialize_with = "barter_integration::de::de_str")]
    pub high: f64,

    /// Low price.
    #[serde(alias = "l", deserialize_with = "barter_integration::de::de_str")]
    pub low: f64,

    /// Close price.
    #[serde(alias = "c", deserialize_with = "barter_integration::de::de_str")]
    pub close: f64,

    /// Base asset volume.
    #[serde(alias = "v", deserialize_with = "barter_integration::de::de_str")]
    pub volume: f64,

    /// Quote asset volume.
    #[serde(alias = "q", deserialize_with = "barter_integration::de::de_str")]
    pub quote_volume: f64,

    /// Number of trades.
    #[serde(alias = "n")]
    pub trade_count: u64,

    /// Whether the candle is closed/final.
    #[serde(alias = "x")]
    pub is_closed: bool,
}

