// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Binance real-time trade message.
/// 
/// Note:
/// For [`BinanceFuturesUsd`](super::futures::BinanceFuturesUsd) this real-time stream is
/// undocumented.
/// 
/// See discord: <https://discord.com/channels/910237311332151317/923160222711812126/975712874582388757>
/// 
/// ### Raw Payload Examples
/// See docs: <https://binance-docs.github.io/apidocs/spot/en/#trade-streams>
/// #### Spot Side::Buy Trade
/// ```json
/// {
/// "e":"trade",
/// "E":1649324825173,
/// "s":"ETHUSDT",
/// "t":1000000000,
/// "p":"10000.19",
/// "q":"0.239000",
/// "b":10108767791,
/// "a":10108764858,
/// "T":1749354825200,
/// "m":false,
/// "M":true
/// }
/// ```
/// 
/// #### FuturePerpetual Side::Sell Trade
/// ```json
/// {
/// "e": "trade",
/// "E": 1649839266194,
/// "T": 1749354825200,
/// "s": "ETHUSDT",
/// "t": 1000000000,
/// "p":"10000.19",
/// "q":"0.239000",
/// "X": "MARKET",
/// "m": true
/// }
/// ```
pub struct BinanceTrade {
    #[serde(alias = "s", deserialize_with = "de_trade_subscription_id")]
    pub subscription_id: SubscriptionId,
    #[serde(
        alias = "T",
        deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc"
    )]
    pub time: DateTime<Utc>,
    #[serde(alias = "t")]
    pub id: u64,
    #[serde(alias = "p", deserialize_with = "barter_integration::de::de_str")]
    pub price: f64,
    #[serde(alias = "q", deserialize_with = "barter_integration::de::de_str")]
    pub amount: f64,
    #[serde(alias = "m", deserialize_with = "de_side_from_buyer_is_maker")]
    pub side: Side,
}

/// Deserialize a [`BinanceTrade`] "s" (eg/ "BTCUSDT") as the associated [`SubscriptionId`]
/// (eg/ "@trade|BTCUSDT").
pub fn de_trade_subscription_id<'de, D>(deserializer: D) -> Result<SubscriptionId, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

/// Deserialize a [`BinanceTrade`] "buyer_is_maker" boolean field to a Barter [`Side`].
/// 
/// Variants:
/// buyer_is_maker => Side::Sell
/// !buyer_is_maker => Side::Buy
pub fn de_side_from_buyer_is_maker<'de, D>(deserializer: D) -> Result<Side, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

