// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/rest/klines.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Hyperliquid REST API path for the info endpoint.
/// 
/// All public data queries use POST to `/info` with a JSON body.
pub const HYPERLIQUID_INFO_PATH: &str = todo!();

#[derive(Debug, Clone, Deserialize)]
/// Raw kline/candlestick data returned by the Hyperliquid REST API.
/// 
/// Hyperliquid returns klines as JSON objects with short field names:
/// ```json
/// {"t":1672531200000,"T":1672531259999,"s":"BTC","i":"1m","o":"16500.0","c":"16550.0","h":"16600.0","l":"16400.0","v":"1234.56","n":42}
/// ```
/// 
/// We only deserialize the fields we need; unknown fields are ignored via
/// serde's default behaviour.
pub struct HyperliquidKlineRaw {
    /// Open time in milliseconds since epoch.
    pub t: u64,
    /// Close time in milliseconds since epoch.
    #[serde(rename = "T")]
    pub close_time: u64,
    /// Open price (string).
    pub o: String,
    /// High price (string).
    pub h: String,
    /// Low price (string).
    pub l: String,
    /// Close price (string).
    pub c: String,
    /// Volume (string).
    pub v: String,
}

#[derive(Debug, Clone, Serialize)]
/// JSON body for the Hyperliquid candleSnapshot request.
/// 
/// Hyperliquid uses POST requests to `/info` with a JSON body like:
/// ```json
/// {
/// "type": "candleSnapshot",
/// "req": {
/// "coin": "BTC",
/// "interval": "1h",
/// "startTime": 1672531200000,
/// "endTime": 1672617600000
/// }
/// }
/// ```
pub struct PostHyperliquidKlines {
    /// Request type, always `"candleSnapshot"`.
    #[serde(rename = "type")]
    pub request_type: &'static str,
    /// The inner request parameters.
    pub req: HyperliquidKlineReq,
}

#[derive(Debug, Clone, Serialize)]
/// Inner request parameters for the Hyperliquid candleSnapshot query.
pub struct HyperliquidKlineReq {
    /// Coin symbol (e.g., "BTC", "ETH").
    pub coin: String,
    /// Candle interval (e.g., "1h", "4h", "1d").
    pub interval: String,
    /// Start time in milliseconds since epoch.
    #[serde(rename = "startTime")]
    pub start_time: i64,
    /// End time in milliseconds since epoch.
    #[serde(rename = "endTime")]
    pub end_time: i64,
}

#[derive(Debug, Clone)]
/// REST request wrapper for the Hyperliquid candleSnapshot endpoint.
/// 
/// This implements [`RestRequest`] with `Method::POST` and a JSON body,
/// unlike most other exchange clients which use GET with query parameters.
pub struct GetHyperliquidKlines {
    /// The JSON body payload.
    pub body: PostHyperliquidKlines,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl HyperliquidKlineRaw {
    /// Convert this raw kline into a normalised [`Candle`].
    /// 
    /// Hyperliquid provides both open and close timestamps, so no interval
    /// duration computation is needed.
    pub fn try_into_candle(self) -> Result<Candle, String> { /* ... */ }
}

