// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/hyperliquid/rest/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// Hyperliquid REST API error payload.
/// 
/// Hyperliquid returns errors as plain text or simple JSON. This captures the
/// common case where the API returns a string error message.
pub struct HyperliquidApiError {
    #[serde(default)]
    pub(crate) error: String,
}

#[derive(Debug)]
/// HTTP response parser for Hyperliquid REST API responses.
pub struct HyperliquidHttpParser;

#[non_exhaustive]
#[derive(Clone)]
/// REST client for the Hyperliquid exchange.
/// 
/// Hyperliquid is a single-variant exchange (no separate spot/futures servers
/// for REST klines), so this client is not generic over an `ExchangeServer`
/// type.
/// 
/// Includes a rate limiter configured conservatively at 600 requests per
/// minute (~10 req/sec). Hyperliquid's actual limits are more generous, but
/// we stay conservative to avoid rate limiting.
/// 
/// **Note:** Unlike most other exchange clients, Hyperliquid uses POST
/// requests to `/info` with a JSON body rather than GET with query
/// parameters. The [`RestClient`] framework supports this via the
/// [`RestRequest::body()`] and [`RestRequest::method()`] trait methods.
pub struct HyperliquidRestClient {
    pub(crate) client: Arc<RestClient<'static, PublicNoHeaders, HyperliquidHttpParser>>,
    pub(crate) rate_limiter: Arc<ExchangeRateLimiter>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl HyperliquidRestClient {
    /// Construct a new [`HyperliquidRestClient`] using the default Hyperliquid
    /// REST API base URL.
    /// 
    /// Initialises a rate limiter with a quota of 600 requests per minute.
    pub fn new() -> Self { /* ... */ }
    /// Construct a new [`HyperliquidRestClient`] with a caller-provided rate limiter.
    /// 
    /// This allows sharing a single [`ExchangeRateLimiter`] across multiple
    /// clients so they draw from the same token bucket.
    pub fn with_rate_limiter(rate_limiter: Arc<ExchangeRateLimiter>) -> Self { /* ... */ }
    /// Construct a [`HyperliquidRestClient`] with a custom base URL.
    /// 
    /// Useful for testing with a mock server where the URL is not known at
    /// compile time.
    pub fn with_base_url(base_url: String) -> Self { /* ... */ }
    /// Return a reference to the inner HTTP client.
    pub fn http_client(&self) -> &Arc<RestClient<'static, PublicNoHeaders, HyperliquidHttpParser>> { /* ... */ }
    /// Wait until the rate limiter permits the next request.
    /// 
    /// This method is for **standalone/direct usage** — call it before each
    /// REST API request when driving the client yourself (outside of a
    /// `barter-collector` pipeline). When using `barter-collector`, rate
    /// limiting is managed by the collector's orchestration layer.
    /// 
    /// Blocks asynchronously until a permit is available.
    pub async fn wait_for_rate_limit(&self) { /* ... */ }
}

