// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/quote.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// Instrument quote asset.
/// 
/// Note that all `Spot` instruments are quoted in the (underlying) quote asset.
pub enum InstrumentQuoteAsset {
    /// "In-kind" pricing (unusual) using the underlying base asset as the quote asset.
    ///
    /// For example, if some derivative for underlying=btc_usdt was quoted in btc.
    #[serde(alias = "underlying_base")]
    UnderlyingBase,

    /// Standard pricing using the underlying quote as the quote asset.
    ///
    /// For example, all spot instruments are quoted in the (underlying) quote asset.
    #[serde(alias = "underlying_quote")]
    UnderlyingQuote,
}

