// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/okx/bulk/trades.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// A single trade row from OKX's bulk CSV archive.
/// 
/// CSV columns: `instrument_name, trade_id, side, price, size, created_time`
pub struct OkxBulkTrade {
    pub instrument_name: String,
    pub trade_id: String,
    pub side: String,
    pub price: String,
    pub size: String,
    pub created_time: String,
}

/// Parse OKX bulk CSV data (with headers) into a vector of [`RestTrade`].
pub fn parse_trades(csv_data: &[u8]) -> Result<Vec<RestTrade>, DataError> { /* ... */ }

