// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/kraken/rest/trades.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Deserialize)]
/// Top-level Kraken Trades response.
/// 
/// Same dynamic-key pattern as klines: the `result` object contains
/// a key for the pair data and a `last` cursor for pagination.
/// 
/// ```json
/// {
/// "error": [],
/// "result": {
/// "XXBTZUSD": [[...], ...],
/// "last": "1679907066543200000"
/// }
/// }
/// ```
/// 
/// The `result` object contains a dynamic key for the pair data and a `last`
/// cursor (nanosecond nonce string) for forward pagination. We deserialize
/// `result` as a raw [`serde_json::Value`] and parse it manually.
pub struct KrakenTradesResponse {
    pub error: Vec<String>,
    pub result: serde_json::Value,
}

#[derive(Debug, Clone)]
/// Raw trade from Kraken REST API.
/// 
/// Kraken returns each trade as a 7-element positional array:
/// `[price, volume, time, buy_sell, market_limit, misc, trade_id]`
/// 
/// - `price`: String
/// - `volume`: String
/// - `time`: float (Unix timestamp with fractional seconds)
/// - `buy_sell`: "b" for buy, "s" for sell
/// - `market_limit`: "m" or "l" (ignored)
/// - `misc`: String (ignored)
/// - `trade_id`: integer (unquoted)
/// 
/// Uses a custom [`Deserialize`] implementation with a sequence visitor.
pub struct KrakenTradeRaw {
    pub price: String,
    pub volume: String,
    /// Unix timestamp with fractional seconds (e.g., 1679907065.2091).
    pub time: f64,
    /// "b" for buy, "s" for sell.
    pub buy_sell: String,
    /// Trade ID as integer.
    pub trade_id: u64,
}

#[derive(Debug, Clone)]
/// REST request to fetch trades from the Kraken API.
/// 
/// Endpoint: `GET /0/public/Trades`
pub struct GetKrakenTrades {
    /// Query parameters for the trades request.
    pub params: GetKrakenTradesParams,
}

#[derive(Debug, Clone, Serialize)]
/// Query parameters for a Kraken Trades REST request.
pub struct GetKrakenTradesParams {
    /// Trading pair (e.g., "XBTUSD").
    pub pair: String,
    /// Optional `since` cursor — nanosecond nonce string from previous
    /// response's `last`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since: Option<String>,
    /// Optional count (max 1000).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<u32>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl KrakenTradesResponse {
    /// Parse the raw `result` into a vector of [`KrakenTradeRaw`] and
    /// an optional `last` pagination cursor (nonce string).
    /// 
    /// Iterates the keys in `result`, treating `"last"` as the cursor and
    /// the remaining key as the trade data array. The pair key in the response
    /// may differ from the requested pair (e.g., `"XXBTZUSD"` vs `"XBTUSD"`).
    pub fn parse_trades(&self) -> Result<(Vec<KrakenTradeRaw>, Option<String>), DataError> { /* ... */ }
}

