// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/rest/klines.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone)]
/// REST request to fetch kline/candlestick data from a Binance API variant.
/// 
/// The `path` field stores the endpoint path, which differs between spot
/// (`/api/v3/klines`) and futures (`/fapi/v1/klines`).
pub struct GetKlines {
    /// Endpoint path (varies by server variant, e.g. spot vs futures).
    pub path: &'static str,
    /// Query parameters for the klines request.
    pub params: GetKlinesParams,
}

#[derive(Debug, Clone, Serialize)]
/// Query parameters for a Binance klines REST request.
pub struct GetKlinesParams {
    pub symbol: String,
    pub interval: String,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

#[non_exhaustive]
#[derive(Debug, Clone)]
/// Raw kline/candlestick data returned by the Binance REST API.
/// 
/// Binance returns klines as arrays of mixed types:
/// `[open_time, open, high, low, close, volume, close_time, quote_volume, trade_count, ...]`
/// 
/// This struct uses a custom [`Deserialize`] implementation with a sequence
/// visitor to parse each positional element.
pub struct BinanceKlineRaw {
    pub open_time: i64,
    pub open: String,
    pub high: String,
    pub low: String,
    pub close: String,
    pub volume: String,
    pub close_time: i64,
    pub quote_volume: String,
    pub trade_count: u64,
}

