// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/rest/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// Binance REST API error payload.
/// 
/// Returned by the Binance API when a request fails, e.g.:
/// ```json
/// { "code": -1121, "msg": "Invalid symbol." }
/// ```
pub struct BinanceApiError {
    pub(crate) code: i64,
    pub(crate) msg: String,
}

#[derive(Debug)]
/// HTTP response parser for Binance REST API responses.
pub struct BinanceHttpParser;

#[non_exhaustive]
#[derive(Clone)]
/// Generic REST client for Binance exchange variants.
/// 
/// The `Server` type parameter determines which Binance server variant
/// (spot or futures) this client connects to, via the
/// [`RestExchangeServer`] trait.
/// 
/// Includes a rate limiter configured for Binance weight-based limits
/// (6000 weight per minute, ~5 weight per klines request = 1200 req/min).
pub struct BinanceRestClient<Server> {
    pub(crate) client: Arc<RestClient<'static, PublicNoHeaders, BinanceHttpParser>>,
    pub(crate) rate_limiter: Arc<ExchangeRateLimiter>,
    _server: PhantomData<Server>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl BinanceRestClient {
    /// Construct a new [`BinanceRestClient`] using the base URL from
    /// [`Server::rest_base_url()`](RestExchangeServer::rest_base_url).
    /// 
    /// Initialises a rate limiter with a quota of 1200 requests per minute,
    /// modelling the Binance 6000 weight/min limit at ~5 weight per request.
    pub fn new() -> Self { /* ... */ }
    /// Construct a new [`BinanceRestClient`] with a shared rate limiter.
    /// 
    /// Uses the base URL from [`Server::rest_base_url()`](RestExchangeServer::rest_base_url)
    /// but accepts an externally-owned [`ExchangeRateLimiter`] instead of creating one.
    /// This is useful when multiple clients should share the same rate-limit budget.
    pub fn with_rate_limiter(rate_limiter: Arc<ExchangeRateLimiter>) -> Self { /* ... */ }
    /// Construct a [`BinanceRestClient`] with a custom base URL.
    /// 
    /// Useful for testing with a mock server where the URL is not known at
    /// compile time. Does not require the `Server` type to implement
    /// [`RestExchangeServer`] since the URL is provided directly.
    pub fn with_base_url(base_url: String) -> Self { /* ... */ }
    /// Return a reference to the inner HTTP client.
    pub fn http_client(&self) -> &Arc<RestClient<'static, PublicNoHeaders, BinanceHttpParser>> { /* ... */ }
    /// Wait until the rate limiter permits the next request.
    /// 
    /// This method is for **standalone/direct usage** — call it before each
    /// REST API request when driving the client yourself (outside of a
    /// `barter-collector` pipeline). When using `barter-collector`, rate
    /// limiting is managed by the collector's orchestration layer.
    /// 
    /// Blocks asynchronously until a permit is available.
    pub async fn wait_for_rate_limit(&self) { /* ... */ }
}

