// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/coinbase/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Coinbase real-time candle WebSocket message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.cloud.coinbase.com/advanced-trade/docs/ws-channels#candles-channel>
/// ```json
/// {
/// "channel":"candles",
/// "timestamp":"2023-06-09T20:19:35.396Z",
/// "sequence_num":0,
/// "events":[{
/// "type":"snapshot",
/// "candles":[{
/// "start":"1688998200",
/// "high":"1867.72",
/// "low":"1865.63",
/// "open":"1867.38",
/// "close":"1866.81",
/// "volume":"0.20269406",
/// "product_id":"ETH-USD"
/// }]
/// }]
/// }
/// ```
pub struct CoinbaseKline {
    pub events: Vec<CoinbaseKlineEvent>,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Inner event from the Coinbase candles `"events"` array.
pub struct CoinbaseKlineEvent {
    /// Event type: "snapshot" or "update".
    #[serde(alias = "type")]
    pub event_type: String,

    /// Array of candle data.
    pub candles: Vec<CoinbaseKlineData>,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Individual candle data from the Coinbase candles channel.
pub struct CoinbaseKlineData {
    /// Candle start time (unix seconds as string).
    #[serde(deserialize_with = "de_str_unix_seconds_as_datetime_utc")]
    pub start: DateTime<Utc>,

    /// High price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub high: f64,

    /// Low price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub low: f64,

    /// Open price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub open: f64,

    /// Close price.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub close: f64,

    /// Base asset volume.
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub volume: f64,

    /// Product identifier (e.g., "ETH-USD").
    pub product_id: String,
}

