// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/coinbase/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convert a normalised [`Interval`] to the Coinbase REST API granularity string.
/// 
/// Returns an error for intervals not supported by the Coinbase API
/// (3m, 4h, 12h, 3d, 1w, 1M).
pub fn coinbase_interval(interval: Interval) -> Result<&'static str, DataError> { /* ... */ }

/// [`Coinbase`] server base url.
/// 
/// See docs: <https://docs.cloud.coinbase.com/exchange/docs/websocket-overview>
pub const BASE_URL_COINBASE: &str = todo!();

#[derive(
    Copy,
    Clone,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Debug,
    Default,
    Display,
    DeExchange,
    SerExchange,
)]
/// [`Coinbase`] exchange.
/// 
/// See docs: <https://docs.cloud.coinbase.com/exchange/docs/websocket-overview>
pub struct Coinbase;

