// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/coinbase/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// Coinbase real-time trade WebSocket message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.cloud.coinbase.com/exchange/docs/websocket-channels#match>
/// ```json
/// {
/// "type": "match",
/// "trade_id": 10,
/// "sequence": 50,
/// "maker_order_id": "ac928c66-ca53-498f-9c13-a110027a60e8",
/// "taker_order_id": "132fb6ae-456b-4654-b4e0-d681ac05cea1",
/// "time": "2014-11-07T08:19:27.028459Z",
/// "product_id": "BTC-USD",
/// "size": "5.23512",
/// "price":
/// "400.23",
/// "side": "sell"
/// }
/// ```
pub struct CoinbaseTrade {
    #[serde(alias = "product_id", deserialize_with = "de_trade_subscription_id")]
    pub subscription_id: SubscriptionId,
    #[serde(alias = "trade_id")]
    pub id: u64,
    pub time: DateTime<Utc>,
    #[serde(alias = "size", deserialize_with = "barter_integration::de::de_str")]
    pub amount: f64,
    #[serde(deserialize_with = "barter_integration::de::de_str")]
    pub price: f64,
    pub side: Side,
}

/// Deserialize a [`CoinbaseTrade`] "product_id" (eg/ "BTC-USD") as the associated [`SubscriptionId`]
/// (eg/ SubscriptionId("matches|BTC-USD").
pub fn de_trade_subscription_id<'de, D>(deserializer: D) -> Result<SubscriptionId, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

