// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/reconnect/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
#[non_exhaustive]
/// [`ReconnectingStream`](stream::ReconnectingStream) `Event` that communicates either `Stream::Item`, or that the inner
/// `Stream` is currently reconnecting.
pub enum Event<Origin, T> {
    /// [`ReconnectingStream`](stream::ReconnectingStream) has disconnecting and is
    /// attempting to reconnect.
    Reconnecting(Origin),
    Item(T),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Event {
    pub fn map<F, O>(self, op: F) -> Event<Origin, O>
        where
            F: FnOnce(T) -> O,
        { /* ... */ }
    pub fn map_ok<F, O>(self, op: F) -> Event<Origin, Result<O, E>>
        where
            F: FnOnce(T) -> O,
        { /* ... */ }
    pub fn map_err<F, O>(self, op: F) -> Event<Origin, Result<T, O>>
        where
            F: FnOnce(E) -> O,
        { /* ... */ }
}

