// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/system/builder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Default)]
/// Defines how the `Engine` processes input events.
/// 
/// Use this to control whether the `Engine` runs in a synchronous blocking thread
/// with an `Iterator` or asynchronously with a `Stream`.
pub enum EngineFeedMode {
    /// Process events synchronously with an `Iterator` in a blocking thread (default).
    #[default]
    Iterator,

    /// Process events asynchronously with a `Stream` and tokio tasks.
    ///
    /// Useful when running concurrent backtests at scale.
    Stream,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Default)]
/// Defines if the `Engine` sends the audit events it produces on the audit channel.
pub enum AuditMode {
    /// Enable audit event sending.
    Enabled,

    /// Disable audit event sending (default).
    #[default]
    Disabled,
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Constructor)]
/// Arguments required for building a full Barter trading system.
/// 
/// Contains all the required components to build and initialise a full Barter trading system,
/// including the `Engine` and all supporting infrastructure.
pub struct SystemArgs<'a, Clock, Strategy, Risk, MarketStream, GlobalData, FnInstrumentData> {
    /// Indexed collection of instruments the system will track.
    pub instruments: &'a IndexedInstruments,

    /// Execution configurations for exchange execution links.
    pub executions: Vec<ExecutionConfig>,

    /// `EngineClock` implementation for time keeping.
    ///
    /// For example, `HistoricalClock` for backtesting and `LiveClock` for live/paper trading.
    pub clock: Clock,

    /// Engine `Strategy` implementation.
    pub strategy: Strategy,

    /// Engine `RiskManager` implementation.
    pub risk: Risk,

    /// `Stream` of `MarketStreamEvent`s.
    pub market_stream: MarketStream,

    /// `EngineState` `GlobalData`
    pub global_data: GlobalData,

    /// Closure used when building the `EngineState` to initialise every
    /// instrument's `InstrumentDataState`.
    pub instrument_data_init: FnInstrumentData,
}

#[derive(Debug)]
/// Builder for constructing a full Barter trading system.
pub struct SystemBuilder<'a, Clock, Strategy, Risk, MarketStream, GlobalData, FnInstrumentData> {
    args: SystemArgs<'a, Clock, Strategy, Risk, MarketStream, GlobalData, FnInstrumentData>,
    engine_feed_mode: Option<EngineFeedMode>,
    audit_mode: Option<AuditMode>,
    trading_state: Option<TradingState>,
    balances: FnvHashMap<ExchangeAsset<AssetNameInternal>, Balance>,
}

#[allow(missing_debug_implementations)]
/// Fully constructed `SystemBuild` ready to be initialised.
/// 
/// This is an intermediate step before spawning tasks and running the system.
pub struct SystemBuild<Engine, Event, MarketStream> {
    /// Constructed `Engine` instance.
    pub engine: Engine,

    /// Selected [`EngineFeedMode`].
    pub engine_feed_mode: EngineFeedMode,

    /// Selected [`AuditMode`].
    pub audit_mode: AuditMode,

    /// `Stream` of `MarketStreamEvent`s.
    pub market_stream: MarketStream,

    /// Channel for `AccountStreamEvent`.
    pub account_channel: Channel<AccountStreamEvent>,

    /// Futures for initialising `ExecutionBuild` components.
    pub execution_build_futures: ExecutionBuildFutures,

    phantom_event: PhantomData<Event>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl SystemBuilder {
    /// Create a new `SystemBuilder` with the provided `SystemArguments`.
    /// 
    /// Initialises a builder with default values for optional configurations.
    pub fn new(
            config: SystemArgs<'a, Clock, Strategy, Risk, MarketStream, GlobalData, FnInstrumentData>,
        ) -> Self { /* ... */ }
    /// Optionally configure the [`EngineFeedMode`] (`Iterator` or `Stream`).
    /// 
    /// Controls whether the engine processes events synchronously or asynchronously.
    pub fn engine_feed_mode(self, value: EngineFeedMode) -> Self { /* ... */ }
    /// Optionally configure the [`AuditMode`] (enabled or disabled).
    /// 
    /// Controls whether the engine sends the audit events it produces.
    pub fn audit_mode(self, value: AuditMode) -> Self { /* ... */ }
    /// Optionally configure the initial [`TradingState`] (enabled or disabled).
    /// 
    /// Sets whether algorithmic trading is initially enabled when the system starts.
    pub fn trading_state(self, value: TradingState) -> Self { /* ... */ }
    /// Optionally provide initial exchange asset `Balance`s.
    /// 
    /// Useful for back-test scenarios where seeding EngineState with initial `Balance`s is
    /// required.
    /// 
    /// Note the internal implementation uses a `HashMap`, so duplicate
    /// `ExchangeAsset<AssetNameInternal>` keys are overwritten.
    pub fn balances<BalanceIter, KeyedBalance>(mut self, balances: BalanceIter) -> Self
        where
            BalanceIter: IntoIterator<Item = KeyedBalance>,
            KeyedBalance: Into<Keyed<ExchangeAsset<AssetNameInternal>, Balance>>,
        { /* ... */ }
    /// Build the [`SystemBuild`] with the configured builder settings.
    /// 
    /// This constructs all the system components but does not start any tasks or streams.
    /// 
    /// Initialise the `SystemBuild` instance to start the system.
    pub fn build<Event, InstrumentData>(
            self,
        ) -> Result<
            SystemBuild<
                Engine<
                    Clock,
                    EngineState<GlobalData, InstrumentData>,
                    MultiExchangeTxMap,
                    Strategy,
                    Risk,
                >,
                Event,
                MarketStream,
            >,
            BarterError,
        >
        where
            Clock: EngineClock + Clone + Send + Sync + 'static,
            FnInstrumentData: Fn(
                &'a Keyed<InstrumentIndex, Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>,
            ) -> InstrumentData,
        { /* ... */ }
}

impl SystemBuild {
    /// Construct a new `SystemBuild` from the provided components.
    pub fn new(
            engine: Engine,
            engine_feed_mode: EngineFeedMode,
            audit_mode: AuditMode,
            market_stream: MarketStream,
            account_channel: Channel<AccountStreamEvent>,
            execution_build_futures: ExecutionBuildFutures,
        ) -> Self { /* ... */ }
    /// Initialise the system using the current tokio runtime.
    /// 
    /// Spawns all necessary tasks and returns the running `System` instance.
    pub async fn init(self) -> Result<System<Engine, Event>, BarterError> { /* ... */ }
    /// Initialise the system using the provided tokio runtime.
    /// 
    /// Allows specifying a custom runtime for spawning tasks.
    pub async fn init_with_runtime(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<System<Engine, Event>, BarterError> { /* ... */ }
    async fn init_internal(
            self,
            runtime: tokio::runtime::Handle,
        ) -> Result<System<Engine, Event>, BarterError> { /* ... */ }
}

