// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/system/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[allow(missing_debug_implementations)]
/// Initialised and running Barter trading system.
/// 
/// Contains handles for the `Engine` and all auxillary system tasks.
/// 
/// It provides methods for interacting with the system, such as sending `Engine` [`Command`]s,
/// managing [`TradingState`], and shutting down gracefully.
pub struct System<Engine, Event>
where
    Engine: Processor<Event> + Auditor<Engine::Audit, Context = EngineContext>,
{
    /// Task handle for the running `Engine`.
    pub engine: JoinHandle<(Engine, Engine::Audit)>,

    /// Handles to auxiliary system components (execution components, event forwarding, etc.).
    pub handles: SystemAuxillaryHandles,

    /// Transmitter for sending events to the `Engine`.
    pub feed_tx: UnboundedTx<Event>,

    /// Optional audit snapshot with updates (present when audit sending is enabled).
    pub audit:
        Option<SnapUpdates<AuditTick<Engine::Snapshot>, UnboundedRx<AuditTick<Engine::Audit>>>>,
}

#[allow(missing_debug_implementations)]
/// Collection of task handles for auxiliary system components that support the `Engine`.
/// 
/// Used by the [`System`] to shut down auxillary components.
pub struct SystemAuxillaryHandles {
    /// Handles for running execution components.
    pub execution: ExecutionHandles,

    /// Task that forwards market events to the engine.
    pub market_to_engine: JoinHandle<()>,

    /// Task that forwards account events to the engine.
    pub account_to_engine: JoinHandle<()>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl SystemAuxillaryHandles {
    pub fn abort(self) { /* ... */ }
}

impl System {
    /// Shutdown the `System` gracefully.
    pub async fn shutdown(mut self) -> Result<(Engine, Engine::Audit), JoinError>
        where
            Event: From<Shutdown>,
        { /* ... */ }
    /// Shutdown the `System` ungracefully.
    pub async fn abort(self) -> Result<(Engine, Engine::Audit), JoinError>
        where
            Event: From<Shutdown>,
        { /* ... */ }
    /// Shutdown a backtesting `System` gracefully after the `Stream` of `MarketStreamEvent`s has
    /// ended.
    /// 
    /// **Note that for live & paper-trading this market stream will never end, so use
    /// System::shutdown() for that use case**.
    pub async fn shutdown_after_backtest(self) -> Result<(Engine, Engine::Audit), JoinError>
        where
            Event: From<Shutdown>,
        { /* ... */ }
    /// Send [`OrderRequestCancel`]s to the `Engine` for execution.
    pub fn send_cancel_requests(&self, requests: OneOrMany<OrderRequestCancel>)
        where
            Event: From<Command>,
        { /* ... */ }
    /// Send [`OrderRequestOpen`]s to the `Engine` for execution.
    pub fn send_open_requests(&self, requests: OneOrMany<OrderRequestOpen>)
        where
            Event: From<Command>,
        { /* ... */ }
    /// Instruct the `Engine` to close open positions.
    /// 
    /// Use the `InstrumentFilter` to configure which positions are closed.
    pub fn close_positions(&self, filter: InstrumentFilter)
        where
            Event: From<Command>,
        { /* ... */ }
    /// Instruct the `Engine` to cancel open orders.
    /// 
    /// Use the `InstrumentFilter` to configure which orders are cancelled.
    pub fn cancel_orders(&self, filter: InstrumentFilter)
        where
            Event: From<Command>,
        { /* ... */ }
    /// Update the algorithmic `TradingState` of the `Engine`.
    pub fn trading_state(&self, trading_state: TradingState)
        where
            Event: From<TradingState>,
        { /* ... */ }
    /// Take ownership of the audit snapshot with updates if present.
    /// 
    /// Note that by this will not be present if the `System` was built in
    /// [`AuditMode::Disabled`](builder::AuditMode) (default).
    pub fn take_audit(
            &mut self,
        ) -> Option<SnapUpdates<AuditTick<Engine::Snapshot>, UnboundedRx<AuditTick<Engine::Audit>>>>
        { /* ... */ }
    /// Send an `Event` to the `Engine`.
    fn send<T>(&self, event: T)
        where
            T: Into<Event>,
        { /* ... */ }
}

