[package]
name = "barter-data"
version = "0.10.2"
edition = "2024"
authors = ["JustAStream <justastream.code@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/barter-data"
repository = "https://github.com/barter-rs/barter-rs"
readme = "README.md"
description = "High performance & normalised WebSocket intergration for leading cryptocurrency exchanges - batteries included."
keywords = ["trading", "backtesting", "crypto", "stocks", "investment"]
categories = ["accessibility", "simulation"]

[features]
default = []
rest = ["dep:rand"]
bulk = ["dep:zip", "dep:csv", "dep:csv-async", "dep:async_zip", "dep:lz4_flex", "dep:sha2", "dep:hmac", "dep:hex", "dep:async-compression", "dep:tokio-util", "dep:quick-xml", "dep:rand"]

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
rust_decimal_macros = { workspace = true }
wiremock = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }

[dependencies]
# Barter Ecosystem
barter-integration = { workspace = true }
barter-instrument = { workspace = true }
barter-macro = { workspace = true }

# Logging
tracing = { workspace = true }

# Async
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }
futures = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }

# Protocol
url = { workspace = true }
reqwest = { workspace = true }

# Error
thiserror = { workspace = true }

# SerDe
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Data Structures
parking_lot = { workspace = true }
rust_decimal = { workspace = true, features = ["serde-with-str"] }
smol_str = { workspace = true, features = ["serde"] }

# Misc
chrono = { workspace = true, features = ["serde"] }
derive_more = { workspace = true }
itertools = { workspace = true }
vecmap-rs = { workspace = true }
fnv = { workspace = true }

# Rate limiting
governor = { workspace = true }

# Optional (feature-gated)
rand = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
csv = { workspace = true, optional = true }
lz4_flex = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
async-compression = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
async_zip = { workspace = true, optional = true }
csv-async = { workspace = true, optional = true }
quick-xml = { workspace = true, optional = true }
