// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/streams/builder/dynamic/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
/// Discriminant-only version of [`SubKind`] for registry lookup keys.
/// Strips the [`Interval`] data from [`SubKind::Candles`] so that a single
/// factory handles all candle intervals for a given exchange.
pub(crate) enum SubKindVariant {
    PublicTrades,
    OrderBooksL1,
    OrderBooksL2,
    OrderBooksL3,
    Liquidations,
    Candles,
}

#[derive(Clone)]
/// Holds type-erased `TypedHandle`s for runtime subscribe/unsubscribe.
/// 
/// Each handle is keyed by `(ExchangeId, SubKind)` and stored as `Box<dyn DynHandle<Instrument>>`.
/// No turbofish or downcast needed: the `DynHandle` trait converts erased subscriptions
/// to concrete types internally.
pub struct DynamicStreamHandles<Instrument> {
    handles: Arc<FnvHashMap<HandleKey, Box<dyn DynHandle<Instrument>>>>,
}

#[derive(Debug)]
pub struct DynamicStreams<InstrumentKey> {
    pub trades:
        VecMap<ExchangeId, UnboundedReceiverStream<MarketStreamResult<InstrumentKey, PublicTrade>>>,
    pub l1s:
        VecMap<ExchangeId, UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookL1>>>,
    pub l2s: VecMap<
        ExchangeId,
        UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookEvent>>,
    >,
    pub liquidations:
        VecMap<ExchangeId, UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Liquidation>>>,
    pub candles:
        VecMap<ExchangeId, UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Candle>>>,
}

pub fn validate_batches<SubBatchIter, SubIter, Sub, Instrument>(
    batches: SubBatchIter,
) -> Result<Vec<Vec<Subscription<ExchangeId, Instrument, SubKind>>>, DataError>
where
    SubBatchIter: IntoIterator<Item = SubIter>,
    SubIter: IntoIterator<Item = Sub>,
    Sub: Into<Subscription<ExchangeId, Instrument, SubKind>>,
    Instrument: InstrumentData + Ord,
{ /* ... */ }

pub fn validate_subscriptions<SubIter, Sub, Instrument>(
    batch: SubIter,
) -> Result<Vec<Subscription<ExchangeId, Instrument, SubKind>>, DataError>
where
    SubIter: IntoIterator<Item = Sub>,
    Sub: Into<Subscription<ExchangeId, Instrument, SubKind>>,
    Instrument: InstrumentData + Ord,
{ /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl DynamicStreams {
    /// Initialise a set of `Streams` by providing one or more [`Subscription`] batches.
    /// 
    /// Each batch (ie/ `impl Iterator<Item = Subscription>`) will initialise at-least-one
    /// WebSocket `Stream` under the hood. If the batch contains more-than-one [`ExchangeId`] and/or
    /// [`SubKind`], it will be further split under the hood for compile-time reasons.
    /// 
    /// ## Examples
    /// Please see barter-data-rs/examples/dynamic_multi_stream_multi_exchange.rs for a
    /// comprehensive example of how to use this market data stream initialiser.
    pub async fn init<SubBatchIter, SubIter, Sub, Instrument>(
            subscription_batches: SubBatchIter,
        ) -> Result<(Self, DynamicStreamHandles<Instrument>), DataError>
        where
            SubBatchIter: IntoIterator<Item = SubIter>,
            SubIter: IntoIterator<Item = Sub>,
            Sub: Into<Subscription<ExchangeId, Instrument, SubKind>>,
            Instrument: InstrumentData<Key = InstrumentKey> + Ord + Display + Send + Sync + 'static,
            InstrumentKey: Debug + Clone + PartialEq + Send + Sync + 'static,
        { /* ... */ }
    /// Remove an exchange [`PublicTrade`] `Stream` from the [`DynamicStreams`] collection.
    /// 
    /// Note that calling this method will permanently remove this `Stream` from [`Self`].
    pub fn select_trades(
            &mut self,
            exchange: ExchangeId,
        ) -> Option<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, PublicTrade>>> { /* ... */ }
    /// Select and merge every exchange [`PublicTrade`] `Stream` using
    /// [`SelectAll`](futures_util::stream::select_all::select_all).
    pub fn select_all_trades(
            &mut self,
        ) -> SelectAll<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, PublicTrade>>> { /* ... */ }
    /// Remove an exchange [`OrderBookL1`] `Stream` from the [`DynamicStreams`] collection.
    /// 
    /// Note that calling this method will permanently remove this `Stream` from [`Self`].
    pub fn select_l1s(
            &mut self,
            exchange: ExchangeId,
        ) -> Option<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookL1>>> { /* ... */ }
    /// Select and merge every exchange [`OrderBookL1`] `Stream` using
    /// [`SelectAll`](futures_util::stream::select_all::select_all).
    pub fn select_all_l1s(
            &mut self,
        ) -> SelectAll<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookL1>>> { /* ... */ }
    /// Remove an exchange [`OrderBookEvent`] `Stream` from the [`DynamicStreams`] collection.
    /// 
    /// Note that calling this method will permanently remove this `Stream` from [`Self`].
    pub fn select_l2s(
            &mut self,
            exchange: ExchangeId,
        ) -> Option<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookEvent>>> { /* ... */ }
    /// Select and merge every exchange [`OrderBookEvent`] `Stream` using
    /// [`SelectAll`](futures_util::stream::select_all::select_all).
    pub fn select_all_l2s(
            &mut self,
        ) -> SelectAll<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, OrderBookEvent>>> { /* ... */ }
    /// Remove an exchange [`Liquidation`] `Stream` from the [`DynamicStreams`] collection.
    /// 
    /// Note that calling this method will permanently remove this `Stream` from [`Self`].
    pub fn select_liquidations(
            &mut self,
            exchange: ExchangeId,
        ) -> Option<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Liquidation>>> { /* ... */ }
    /// Select and merge every exchange [`Liquidation`] `Stream` using
    /// [`SelectAll`](futures_util::stream::select_all::select_all).
    pub fn select_all_liquidations(
            &mut self,
        ) -> SelectAll<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Liquidation>>> { /* ... */ }
    /// Remove an exchange [`Candle`] `Stream` from the [`DynamicStreams`] collection.
    /// 
    /// Note that calling this method will permanently remove this `Stream` from [`Self`].
    pub fn select_candles(
            &mut self,
            exchange: ExchangeId,
        ) -> Option<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Candle>>> { /* ... */ }
    /// Select and merge every exchange [`Candle`] `Stream` using
    /// [`SelectAll`](futures_util::stream::select_all::select_all).
    pub fn select_all_candles(
            &mut self,
        ) -> SelectAll<UnboundedReceiverStream<MarketStreamResult<InstrumentKey, Candle>>> { /* ... */ }
    /// Select and merge every exchange `Stream` for every data type using [`select_all`](futures_util::stream::select_all::select_all)
    /// 
    /// Note that using [`MarketStreamResult<Instrument, DataKind>`] as the `Output` is suitable for most
    /// use cases.
    pub fn select_all<Output>(self) -> impl Stream<Item = Output>
        where
            InstrumentKey: Send + Sync + 'static,
            Output: 'static,
            MarketStreamResult<InstrumentKey, PublicTrade>: Into<Output>,
            MarketStreamResult<InstrumentKey, OrderBookL1>: Into<Output>,
            MarketStreamResult<InstrumentKey, OrderBookEvent>: Into<Output>,
            MarketStreamResult<InstrumentKey, Liquidation>: Into<Output>,
            MarketStreamResult<InstrumentKey, Candle>: Into<Output>,
        { /* ... */ }
}

impl DynamicStreamHandles {
    /// Subscribe to new instruments on a live connection.
    /// 
    /// Derives the `(ExchangeId, SubKindVariant)` key from the first subscription.
    /// All subscriptions in the batch must share the same exchange and sub-kind variant.
    pub fn subscribe(
            &self,
            subscriptions: Vec<Subscription<ExchangeId, Instrument, SubKind>>,
        ) -> Result<Vec<barter_integration::subscription::SubscriptionId>, DataError> { /* ... */ }
    /// Unsubscribe from instruments on a live connection.
    pub fn unsubscribe(
            &self,
            exchange: ExchangeId,
            sub_kind: SubKind,
            subscription_ids: Vec<barter_integration::subscription::SubscriptionId>,
        ) -> Result<(), DataError> { /* ... */ }
}

