// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/shutdown.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait SyncShutdown {
    type Result;
    fn shutdown(&mut self) -> Self::Result;
}

pub trait AsyncShutdown {
    type Result;
    fn shutdown(&mut self) -> impl Future<Output = Self::Result>;
}

#[derive(
    Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Deserialize, Serialize,
)]
pub struct Shutdown;

