// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/binance/futures/liquidation.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// [`BinanceFuturesUsd`](super::BinanceFuturesUsd) Liquidation order message.
/// 
/// ### Raw Payload Examples
/// See docs: <https://binance-docs.github.io/apidocs/futures/en/#liquidation-order-streams>
/// ```json
/// {
/// "e": "forceOrder",
/// "E": 1665523974222,
/// "o": {
/// "s": "BTCUSDT",
/// "S": "SELL",
/// "o": "LIMIT",
/// "f": "IOC",
/// "q": "0.009",
/// "p": "18917.15",
/// "ap": "18990.00",
/// "X": "FILLED",
/// "l": "0.009",
/// "z": "0.009",
/// "T": 1665523974217
/// }
/// }
/// ```
pub struct BinanceLiquidation {
    #[serde(alias = "o")]
    pub order: BinanceLiquidationOrder,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Deserialize, Serialize)]
/// [`BinanceFuturesUsd`](super::BinanceFuturesUsd) Liquidation order.
/// 
/// ### Raw Payload Examples
/// ```json
/// {
/// "s": "BTCUSDT",
/// "S": "SELL",
/// "o": "LIMIT",
/// "f": "IOC",
/// "q": "0.009",
/// "p": "18917.15",
/// "ap": "18990.00",
/// "X": "FILLED",
/// "l": "0.009",
/// "z": "0.009",
/// "T": 1665523974217
/// }
/// ```
/// 
/// See docs: <https://binance-docs.github.io/apidocs/futures/en/#liquidation-order-streams>
pub struct BinanceLiquidationOrder {
    #[serde(alias = "s", deserialize_with = "de_liquidation_subscription_id")]
    pub subscription_id: SubscriptionId,
    #[serde(alias = "S")]
    pub side: Side,
    #[serde(alias = "p", deserialize_with = "barter_integration::de::de_str")]
    pub price: f64,
    #[serde(alias = "q", deserialize_with = "barter_integration::de::de_str")]
    pub quantity: f64,
    #[serde(
        alias = "T",
        deserialize_with = "barter_integration::de::de_u64_epoch_ms_as_datetime_utc"
    )]
    pub time: DateTime<Utc>,
}

/// Deserialize a [`BinanceLiquidationOrder`] "s" (eg/ "BTCUSDT") as the associated
/// [`SubscriptionId`].
/// 
/// eg/ "forceOrder|BTCUSDT"
pub fn de_liquidation_subscription_id<'de, D>(deserializer: D) -> Result<SubscriptionId, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

