// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/bulk/checksum.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Verify a SHA-256 checksum against data bytes.
/// 
/// The `expected` string should be the hex-encoded SHA-256 hash (lowercase),
/// matching the format used by Binance Vision `.CHECKSUM` files.
pub fn verify_sha256(data: &[u8], expected: &str) -> Result<(), DataError> { /* ... */ }

/// Compute the SHA-256 hex digest of the given data.
pub fn compute_sha256(data: &[u8]) -> String { /* ... */ }

/// Parse a Binance Vision `.CHECKSUM` file content.
/// 
/// Format: `<sha256_hex>  <filename>\n`
/// Returns the hex checksum string.
pub fn parse_binance_checksum(content: &str) -> Result<String, DataError> { /* ... */ }

/// Check whether a `.verified` marker file exists with a matching checksum.
/// 
/// The marker file format is: `<sha256hex>  <original_filename>\n`.
/// Returns `true` if the marker exists and its stored hash matches `expected_hash`.
pub fn should_skip(marker_path: &Path, expected_hash: &str) -> bool { /* ... */ }

/// Write a `.verified` marker file atomically (tmp + rename).
/// 
/// Format: `<sha256hex>  <original_filename>\n`.
/// Failures are non-fatal and logged as warnings.
pub fn write_verified_marker(marker_path: &Path, hash: &str, original_filename: &str) { /* ... */ }

