// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/bulk/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Debug, PartialEq)]
/// Date-range request for bulk trade archives.
pub struct BulkTradeRequest {
    /// Exchange-specific symbol (e.g., "BTCUSDT").
    pub market: String,
    /// Start date, inclusive.
    pub start: NaiveDate,
    /// End date, inclusive.
    pub end: NaiveDate,
}

#[derive(Clone, Debug, PartialEq)]
/// Date-range request for bulk kline archives.
pub struct BulkKlineRequest {
    /// Exchange-specific symbol (e.g., "BTCUSDT").
    pub market: String,
    /// Candlestick interval period.
    pub interval: Interval,
    /// Start date, inclusive.
    pub start: NaiveDate,
    /// End date, inclusive.
    pub end: NaiveDate,
}

#[non_exhaustive]
#[derive(Debug, Clone)]
/// Configuration for bulk downloads.
pub struct BulkConfig {
    /// Whether to verify checksums when available.
    pub verify_checksum: bool,
}

/// Fetch a single day's trades from a bulk archive.
/// 
/// Returns `Ok(Some(trades))` on success, `Ok(None)` if the date is not
/// available (e.g. HTTP 404), or `Err` on failure.
pub trait BulkDayTradeFetcher: Send + Sync {
    /// Fetch all trades for a single day, collected into a `Vec`.
    fn fetch_day_trades<'a>(
        &'a self,
        market: &'a str,
        date: NaiveDate,
    ) -> Pin<Box<dyn Future<Output = Result<Option<Vec<RestTrade>>, DataError>> + Send + 'a>>;

    /// Stream trades for a single day through a channel in batches.
    ///
    /// Returns `Ok(true)` if data was found, `Ok(false)` if 404, `Err` on
    /// failure. The default implementation calls [`Self::fetch_day_trades`]
    /// and sends the entire `Vec` as one batch.
    ///
    /// Implementations should override this to send smaller batches as
    /// records are parsed, keeping memory bounded regardless of day size.
    fn stream_day_trades<'a>(
        &'a self,
        market: &'a str,
        date: NaiveDate,
        tx: &'a tokio::sync::mpsc::Sender<Vec<RestTrade>>,
    ) -> Pin<Box<dyn Future<Output = Result<bool, DataError>> + Send + 'a>> { /* ... */ }
}

/// Fetch a single day's klines from a bulk archive.
/// 
/// Returns `Ok(Some(candles))` on success, `Ok(None)` if the date is not
/// available (e.g. HTTP 404), or `Err` on failure.
pub trait BulkDayKlineFetcher: Send + Sync {
    fn fetch_day_klines<'a>(
        &'a self,
        market: &'a str,
        interval: Interval,
        date: NaiveDate,
    ) -> Pin<Box<dyn Future<Output = Result<Option<Vec<Candle>>, DataError>> + Send + 'a>>;
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl BulkConfig {
    pub fn new(verify_checksum: bool) -> Self { /* ... */ }
}

