// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/bulk/streaming.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Default batch size for channel-based streaming parsers.
pub(crate) const DEFAULT_BATCH_SIZE: usize = todo!();

/// Convert a [`reqwest::Response`] into a buffered async reader suitable for
/// piping into a decompressor (`GzipDecoder`, `Lz4Decoder`, etc.).
/// 
/// The returned reader streams HTTP chunks on demand — no bytes are buffered
/// beyond tokio's internal `BufReader` window (default 8 KiB).
pub(crate) fn response_to_async_read(
    response: reqwest::Response,
) -> impl AsyncBufRead + Send + Unpin { /* ... */ }

/// Streaming CSV parser: deserialise records one at a time from any async
/// reader, convert each to [`RestTrade`], and collect into a `Vec`.
/// 
/// Parsing is streaming — only one CSV record is in flight at a time, so
/// the intermediate decompressed-bytes buffer is eliminated. The returned
/// `Vec<RestTrade>` still grows with the number of trades.
/// 
/// # Type parameters
/// - `R`: any async reader (e.g. a `GzipDecoder` wrapping a `StreamReader`)
/// - `T`: the CSV record type (e.g. `BybitBulkTrade`), must impl `DeserializeOwned`
/// - `F`: conversion closure `T -> Result<RestTrade, DataError>`
pub(crate) async fn parse_csv_stream<R, T, F>(
    reader: R,
    has_headers: bool,
    flexible: bool,
    convert: F,
) -> Result<Vec<RestTrade>, DataError>
where
    R: AsyncRead + Unpin + Send,
    T: DeserializeOwned + Send,
    F: Fn(T) -> Result<RestTrade, DataError>,
{ /* ... */ }

/// Streaming ZIP+CSV parser: open a ZIP stream, extract the first entry,
/// pipe it through [`parse_csv_stream`], and return the parsed trades.
/// 
/// Encapsulates the entire `async_zip` type-state lifecycle so callers
/// don't need to manage the `ZipFileReader` → `ZipEntryReader` transition.
/// 
/// # Type parameters
/// - `R`: any async buffered reader (e.g. an HTTP response stream)
/// - `T`: the CSV record type, must impl `DeserializeOwned`
/// - `F`: conversion closure `T -> Result<RestTrade, DataError>`
pub(crate) async fn parse_zip_csv_stream<R, T, F>(
    reader: R,
    has_headers: bool,
    flexible: bool,
    convert: F,
) -> Result<Vec<RestTrade>, DataError>
where
    R: AsyncBufRead + Unpin + Send,
    T: DeserializeOwned + Send,
    F: Fn(T) -> Result<RestTrade, DataError>,
{ /* ... */ }

/// Channel-based CSV parser: deserialise records one at a time, batch them,
/// and send each batch through the provided `mpsc::Sender`.
/// 
/// Eliminates the `Vec<RestTrade>` return — trades flow to the consumer as
/// they are parsed. Memory is bounded by `batch_size` regardless of file size.
/// 
/// Returns the total number of records sent.
pub(crate) async fn parse_csv_into_sender<R, T, F>(
    reader: R,
    has_headers: bool,
    flexible: bool,
    convert: F,
    tx: &mpsc::Sender<Vec<RestTrade>>,
    batch_size: usize,
) -> Result<u64, DataError>
where
    R: AsyncRead + Unpin + Send,
    T: DeserializeOwned + Send,
    F: Fn(T) -> Result<RestTrade, DataError>,
{ /* ... */ }

/// Channel-based ZIP+CSV parser: open a ZIP stream, extract the first entry,
/// pipe it through [`parse_csv_into_sender`].
/// 
/// Same lifecycle as [`parse_zip_csv_stream`] but sends batches through a
/// channel instead of collecting into a `Vec`.
/// 
/// Returns the total number of records sent.
pub(crate) async fn parse_zip_csv_into_sender<R, T, F>(
    reader: R,
    has_headers: bool,
    flexible: bool,
    convert: F,
    tx: &mpsc::Sender<Vec<RestTrade>>,
    batch_size: usize,
) -> Result<u64, DataError>
where
    R: AsyncBufRead + Unpin + Send,
    T: DeserializeOwned + Send,
    F: Fn(T) -> Result<RestTrade, DataError>,
{ /* ... */ }

