// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/bulk/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Marker trait for Bybit server variants used in bulk downloads.
pub trait BybitBulkServer: Send + Sync + 'static {
    /// URL path prefix: `"spot"` or `"trading"`.
    fn path_prefix() -> &'static str;
    /// Separator between market symbol and date in archive filenames.
    /// Spot uses `"_"` (e.g. `BTCUSDT_2025-12-09.csv.gz`),
    /// perpetuals use no separator (e.g. `BTCUSDT2025-12-09.csv.gz`).
    fn date_separator() -> &'static str;
    /// Parse CSV data into trades (sync fallback). Spot and perpetuals have
    /// different CSV schemas.
    fn parse_csv(data: &[u8]) -> Result<Vec<RestTrade>, DataError>;
    /// Parse CSV trades from an async reader (streaming). Records are
    /// deserialized one at a time — peak memory is bounded regardless of
    /// archive size.
    ///
    /// Default impl falls back to reading all bytes and calling [`Self::parse_csv`].
    /// Override with a streaming implementation for bounded memory usage.
    fn parse_csv_async(
        reader: impl AsyncRead + Unpin + Send,
    ) -> impl Future<Output = Result<Vec<RestTrade>, DataError>> + Send { /* ... */ }

    /// Parse CSV trades from an async reader, sending batches through a channel.
    ///
    /// Default impl falls back to reading all bytes, calling [`Self::parse_csv`],
    /// and sending the result as one batch. Override with a streaming
    /// implementation for bounded memory usage.
    fn parse_csv_async_into_sender(
        reader: impl AsyncRead + Unpin + Send,
        tx: &tokio::sync::mpsc::Sender<Vec<RestTrade>>,
        _batch_size: usize,
    ) -> impl Future<Output = Result<u64, DataError>> + Send { /* ... */ }
}

#[non_exhaustive]
#[derive(Debug)]
/// Bulk archive download client for Bybit exchange variants.
/// 
/// Downloads daily GZ-compressed CSV trade archives from
/// `https://public.bybit.com/{prefix}/{SYMBOL}/{SYMBOL}{YYYY-MM-DD}.csv.gz`.
/// 
/// Uses streaming gzip decompression via `async_compression` to avoid loading
/// the entire compressed file into memory before decompressing.
pub struct BybitBulkClient<Server> {
    pub(crate) client: reqwest::Client,
    pub(crate) config: BulkConfig,
    _server: PhantomData<Server>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl BybitBulkClient {
    /// Return a reference to the bulk download configuration.
    pub fn config(&self) -> &BulkConfig { /* ... */ }
    fn build_client() -> reqwest::Client { /* ... */ }
    pub fn new() -> Self { /* ... */ }
    pub fn with_config(config: BulkConfig) -> Self { /* ... */ }
    /// Download and parse trades using fully streaming gzip + CSV parsing.
    /// 
    /// The HTTP response body is streamed through `GzipDecoder` and then
    /// directly into `csv-async`'s async deserializer. Records are parsed
    /// one at a time — peak memory is bounded regardless of archive size.
    async fn download_and_parse_trades(
            &self,
            market: &str,
            date: NaiveDate,
        ) -> Result<Option<Vec<RestTrade>>, DataError> { /* ... */ }
    /// Stream trades for a single day through a channel in batches.
    /// 
    /// Same HTTP + gzip pipeline as [`download_and_parse_trades`](Self::download_and_parse_trades),
    /// but sends parsed records through `tx` in batches of `batch_size`
    /// instead of collecting into a `Vec`.
    /// 
    /// Returns `Ok(true)` if data was found, `Ok(false)` on 404.
    async fn stream_and_parse_trades(
            &self,
            market: &str,
            date: NaiveDate,
            tx: &tokio::sync::mpsc::Sender<Vec<RestTrade>>,
            batch_size: usize,
        ) -> Result<bool, DataError> { /* ... */ }
}

