// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bybit/bulk/trades.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// A single trade row from Bybit's bulk CSV archive.
/// 
/// CSV columns: `timestamp, symbol, side, size, price, tickDirection,
/// trdMatchID, grossValue, homeNotional, foreignNotional`
pub struct BybitBulkTrade {
    pub timestamp: f64,
    pub symbol: String,
    pub side: String,
    pub size: String,
    pub price: String,
    #[serde(rename = "tickDirection")]
    pub tick_direction: String,
    #[serde(rename = "trdMatchID")]
    pub trd_match_id: String,
    #[serde(rename = "grossValue")]
    pub gross_value: String,
    #[serde(rename = "homeNotional")]
    pub home_notional: String,
    #[serde(rename = "foreignNotional")]
    pub foreign_notional: String,
}

#[non_exhaustive]
#[derive(Debug, Deserialize)]
/// A single trade row from Bybit's spot bulk CSV archive.
/// 
/// CSV columns: `id, timestamp, price, volume, side[, rpi]`
/// Timestamp is in milliseconds (integer). Side is lowercase ("buy"/"sell").
/// The `rpi` column was added on 2025-03-13; older archives omit it.
pub struct BybitSpotBulkTrade {
    pub id: u64,
    pub timestamp: i64,
    pub price: String,
    pub volume: String,
    pub side: String,
    #[allow(dead_code)]
    #[serde(default)]
    pub rpi: i32,
}

/// Parse Bybit spot bulk CSV data into a vector of [`RestTrade`].
pub fn parse_spot_trades(csv_data: &[u8]) -> Result<Vec<RestTrade>, DataError> { /* ... */ }

/// Parse Bybit perpetuals bulk CSV data (with headers) into a vector of [`RestTrade`].
pub fn parse_trades(csv_data: &[u8]) -> Result<Vec<RestTrade>, DataError> { /* ... */ }

