// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/kraken/channel.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Serialize)]
/// Type that defines how to translate a Barter [`Subscription`] into a
/// [`Kraken`] v2 channel to be subscribed to.
/// 
/// See docs: <https://docs.kraken.com/api/docs/websocket-v2/>
pub struct KrakenChannel(pub(crate) SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl KrakenChannel {
    /// [`Kraken`] v2 real-time trades channel.
    /// 
    /// See docs: <https://docs.kraken.com/api/docs/websocket-v2/trade/>
    pub const TRADES: Self = todo!();
    /// [`Kraken`] v2 ticker channel (best bid/ask, replaces v1 "spread").
    /// 
    /// See docs: <https://docs.kraken.com/api/docs/websocket-v2/ticker/>
    pub const TICKER: Self = todo!();
    /// [`Kraken`] v2 L2 orderbook channel.
    /// 
    /// See docs: <https://docs.kraken.com/api/docs/websocket-v2/book/>
    pub const ORDER_BOOK_L2: Self = todo!();
}

