// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/kraken/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convert a normalised [`Interval`] to the Kraken API integer-minutes interval.
/// 
/// Kraken supports: 1, 5, 15, 30, 60, 240, 1440, 10080, 21600.
/// Returns a [`DataError`] for unsupported intervals (3m, 2h, 6h, 12h, 3d, 1M).
pub fn kraken_interval(interval: Interval) -> Result<u32, DataError> { /* ... */ }

/// [`Kraken`] WebSocket v2 server base url.
/// 
/// See docs: <https://docs.kraken.com/api/docs/websocket-v2/>
pub const BASE_URL_KRAKEN: &str = todo!();

#[derive(
    Copy,
    Clone,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Debug,
    Default,
    Display,
    DeExchange,
    SerExchange,
)]
/// [`Kraken`] exchange.
/// 
/// See docs: <https://docs.kraken.com/api/docs/websocket-v2/>
pub struct Kraken;

