// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/kraken/subscription.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// [`Kraken`](super::Kraken) v2 WebSocket subscription response.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.kraken.com/api/docs/websocket-v2/trade/>
/// 
/// #### Success
/// ```json
/// {
/// "method": "subscribe",
/// "result": {
/// "channel": "trade",
/// "snapshot": true,
/// "symbol": "BTC/USD"
/// },
/// "success": true,
/// "time_in": "2026-03-27T12:17:06.298588Z",
/// "time_out": "2026-03-27T12:17:06.298626Z"
/// }
/// ```
/// 
/// #### Failure
/// ```json
/// {
/// "error": "Currency pair not supported BTC/INVALID",
/// "method": "subscribe",
/// "success": false,
/// "time_in": "2026-03-27T12:17:06.298588Z",
/// "time_out": "2026-03-27T12:17:06.298626Z"
/// }
/// ```
pub struct KrakenSubResponse {
    pub method: String,
    pub success: bool,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub result: Option<KrakenSubResult>,
}

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// The `result` field of a successful v2 subscription response.
pub struct KrakenSubResult {
    pub channel: String,
    #[serde(default)]
    pub symbol: Option<String>,
}

