// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// aggregate: barter_integration.rs
// crates: barter_integration

// ---- source: barter-integration/src/channel.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/channel.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait Tx
where
    Self: Debug + Clone + Send,
{
    type Item;
    type Error: Unrecoverable + Debug;
    fn send<Item: Into<Self::Item>>(&self, item: Item) -> Result<(), Self::Error>;
}

#[derive(Debug)]
/// Convenience type that holds the [`UnboundedTx`] and [`UnboundedRx`].
pub struct Channel<T> {
    pub tx: UnboundedTx<T>,
    pub rx: UnboundedRx<T>,
}

#[derive(Debug, Clone)]
pub struct UnboundedTx<T> {
    pub tx: tokio::sync::mpsc::UnboundedSender<T>,
}

#[derive(Debug, Constructor)]
pub struct UnboundedRx<T> {
    pub rx: tokio::sync::mpsc::UnboundedReceiver<T>,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Deserialize, Serialize)]
pub struct ChannelTxDroppable<ChannelTx> {
    pub state: ChannelState<ChannelTx>,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Deserialize, Serialize, Display)]
pub enum ChannelState<Tx> {
    Active(Tx),
    Disabled,
}

pub fn mpsc_unbounded<T>() -> (UnboundedTx<T>, UnboundedRx<T>) { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ChannelTxDroppable {
    pub fn new(tx: ChannelTx) -> Self { /* ... */ }
    pub fn new_disabled() -> Self { /* ... */ }
    pub fn disable(&mut self) { /* ... */ }
    pub fn send(&mut self, item: ChannelTx::Item) { /* ... */ }
}

impl UnboundedTx {
    pub fn new(tx: tokio::sync::mpsc::UnboundedSender<T>) -> Self { /* ... */ }
}

impl UnboundedRx {
    pub fn into_stream(self) -> tokio_stream::wrappers::UnboundedReceiverStream<T> { /* ... */ }
}

impl Channel {
    /// Construct a new unbounded [`Channel`].
    pub fn new() -> Self { /* ... */ }
}

// ---- source: barter-integration/src/collection/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/collection/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub type FnvIndexMap<K, V> = indexmap::IndexMap<K, V, fnv::FnvBuildHasher>;

pub type FnvIndexSet<T> = indexmap::IndexSet<T, fnv::FnvBuildHasher>;

// ---- source: barter-integration/src/collection/none_one_or_many.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/collection/none_one_or_many.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Default, Deserialize, Serialize)]
pub enum NoneOneOrMany<T> {
    #[default]
    None,
    One(T),
    Many(Vec<T>),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl NoneOneOrMany {
    pub fn map<U, F>(self, f: F) -> NoneOneOrMany<U>
        where
            F: Fn(T) -> U,
        { /* ... */ }
    pub fn extend<Iter>(self, other: Iter) -> Self
        where
            Iter: IntoIterator<Item = T>,
        { /* ... */ }
    pub fn contains(&self, item: &T) -> bool
        where
            T: PartialEq,
        { /* ... */ }
    pub fn len(&self) -> usize { /* ... */ }
    pub fn is_empty(&self) -> bool { /* ... */ }
    pub fn is_none(&self) -> bool { /* ... */ }
    pub fn is_one(&self) -> bool { /* ... */ }
    pub fn is_many(&self) -> bool { /* ... */ }
    pub fn into_option(self) -> Option<OneOrMany<T>> { /* ... */ }
    pub fn into_vec(self) -> Vec<T> { /* ... */ }
    pub fn iter(&self) -> std::slice::Iter<'_, T> { /* ... */ }
}

// ---- source: barter-integration/src/collection/one_or_many.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/collection/one_or_many.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub enum OneOrMany<T> {
    One(T),
    Many(Vec<T>),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl OneOrMany {
    pub fn map<U, F>(self, f: F) -> OneOrMany<U>
        where
            F: Fn(T) -> U,
        { /* ... */ }
    pub fn extend<Iter>(self, other: Iter) -> Self
        where
            Iter: IntoIterator<Item = T>,
        { /* ... */ }
    pub fn contains(&self, item: &T) -> bool
        where
            T: PartialEq,
        { /* ... */ }
    #[allow(clippy::len_without_is_empty)]
    pub fn len(&self) -> usize { /* ... */ }
    pub fn is_one(&self) -> bool { /* ... */ }
    pub fn is_many(&self) -> bool { /* ... */ }
    pub fn into_vec(self) -> Vec<T> { /* ... */ }
    pub fn iter(&self) -> std::slice::Iter<'_, T> { /* ... */ }
}

// ---- source: barter-integration/src/de.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/de.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Determine the `DateTime<Utc>` from the provided `Duration` since the epoch.
pub fn datetime_utc_from_epoch_duration(
    duration: std::time::Duration,
) -> chrono::DateTime<chrono::Utc> { /* ... */ }

/// Deserialize a `String` as the desired type.
pub fn de_str<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::de::Deserializer<'de>,
    T: std::str::FromStr,
    T::Err: std::fmt::Display,
{ /* ... */ }

/// Deserialize a `u64` milliseconds value as `DateTime<Utc>`.
pub fn de_u64_epoch_ms_as_datetime_utc<'de, D>(
    deserializer: D,
) -> Result<chrono::DateTime<chrono::Utc>, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

/// Deserialize a &str "u64" milliseconds value as `DateTime<Utc>`.
pub fn de_str_u64_epoch_ms_as_datetime_utc<'de, D>(
    deserializer: D,
) -> Result<chrono::DateTime<chrono::Utc>, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

/// Deserialize a &str "f64" milliseconds value as `DateTime<Utc>`.
pub fn de_str_f64_epoch_ms_as_datetime_utc<'de, D>(
    deserializer: D,
) -> Result<chrono::DateTime<chrono::Utc>, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

/// Deserialize a &str "f64" seconds value as `DateTime<Utc>`.
pub fn de_str_f64_epoch_s_as_datetime_utc<'de, D>(
    deserializer: D,
) -> Result<chrono::DateTime<chrono::Utc>, D::Error>
where
    D: serde::de::Deserializer<'de>,
{ /* ... */ }

/// Assists deserialisation of sequences by attempting to extract & parse the next element in the
/// provided sequence.
/// 
/// A [`serde::de::Error`] is returned if the element does not exist, or it cannot
/// be deserialized into the `Target` type inferred.
/// 
/// Example sequence: ["20180.30000","0.00010000","1661978265.280067","s","l",""]
pub fn extract_next<'de, SeqAccessor, Target>(
    sequence: &mut SeqAccessor,
    name: &'static str,
) -> Result<Target, SeqAccessor::Error>
where
    SeqAccessor: serde::de::SeqAccess<'de>,
    Target: serde::de::DeserializeOwned,
{ /* ... */ }

/// Serialize a generic element T as a `Vec<T>`.
pub fn se_element_to_vector<T, S>(element: T, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
    T: serde::Serialize,
{ /* ... */ }

// ---- source: barter-integration/src/error.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/error.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Error)]
/// All socket IO related errors generated in `barter-integration`.
pub enum SocketError {
    #[error("Sink error")]
    Sink,

    #[error("Deserialising JSON error: {error} for payload: {payload}")]
    Deserialise {
        error: serde_json::Error,
        payload: String,
    },

    #[error("Deserialising JSON error: {error} for binary payload: {payload:?}")]
    DeserialiseBinary {
        error: serde_json::Error,
        payload: Vec<u8>,
    },

    #[error("Deserialising protobuf error: {error} for binary payload: {payload:?}")]
    DeserialiseProtobuf {
        error: DecodeError,
        payload: Vec<u8>,
    },

    #[error("Serialising JSON error: {0}")]
    Serialise(serde_json::Error),

    #[error("SerDe Query String serialisation error: {0}")]
    QueryParams(#[from] serde_qs::Error),

    #[error("SerDe url encoding serialisation error: {0}")]
    UrlEncoded(#[from] serde_urlencoded::ser::Error),

    #[error("error parsing Url: {0}")]
    UrlParse(#[from] url::ParseError),

    #[error("error subscribing to resources over the socket: {0}")]
    Subscribe(String),

    #[error("ExchangeStream terminated with closing frame: {0}")]
    Terminated(String),

    #[error("{entity} does not support: {item}")]
    Unsupported { entity: String, item: String },

    #[error("WebSocket error: {0}")]
    WebSocket(Box<tokio_tungstenite::tungstenite::Error>),

    #[error("HTTP error: {0}")]
    Http(reqwest::Error),

    #[error("HTTP request timed out")]
    HttpTimeout(reqwest::Error),

    /// REST http response error
    #[error("HTTP response (status={0}) error: {1}")]
    HttpResponse(reqwest::StatusCode, String),

    #[error("consumed unidentifiable message: {0}")]
    Unidentifiable(SubscriptionId),

    #[error("consumed error message from execution: {0}")]
    Exchange(String),
}

// ---- source: barter-integration/src/lib.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/lib.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// [`Validator`]s are capable of determining if their internal state is satisfactory to fulfill
/// some use case defined by the implementor.
pub trait Validator {
    /// Check if `Self` is valid for some use case.
    fn validate(self) -> Result<Self, SocketError>
    where
        Self: Sized;
}

/// [`Transformer`]s are capable of transforming any `Input` into an iterator of
/// `Result<Self::Output, Self::Error>`s.
pub trait Transformer {
    type Error;
    type Input;
    type Output;
    type OutputIter: IntoIterator<Item = Result<Self::Output, Self::Error>>;

    fn transform(&mut self, input: Self::Input) -> Self::OutputIter;
}

/// Determines if something is considered "unrecoverable", such as an unrecoverable error.
/// 
/// Note that the meaning of [`Unrecoverable`] may vary depending on the context.
pub trait Unrecoverable {
    fn is_unrecoverable(&self) -> bool;
}

/// Trait that communicates if something is terminal (eg/ requires shutdown or restart).
pub trait Terminal {
    fn is_terminal(&self) -> bool;
}

#[derive(
    Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Deserialize, Serialize,
)]
/// Indicates an `Iterator` or `Stream` has ended.
pub struct FeedEnded;

// ---- source: barter-integration/src/metric.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/metric.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialOrd, PartialEq, Serialize)]
pub struct Metric {
    /// Metric name.
    pub name: &'static str,

    /// Milliseconds since the Unix epoch.
    pub time: u64,

    /// Key-Value pairs to categorise the Metric.
    pub tags: Vec<Tag>,

    /// Observed measurements.
    pub fields: Vec<Field>,
}

#[derive(Debug, Clone, Serialize, Ord, PartialOrd, Eq, PartialEq)]
pub struct Tag {
    pub key: &'static str,
    pub value: String,
}

#[derive(Debug, Clone, PartialOrd, PartialEq, Serialize)]
pub struct Field {
    pub key: &'static str,
    pub value: Value,
}

#[derive(Debug, Clone, PartialOrd, PartialEq, Deserialize, Serialize)]
pub enum Value {
    Float(f64),
    Int(i64),
    UInt(u64),
    Bool(bool),
    String(String),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Tag {
    pub fn new<S>(key: &'static str, value: S) -> Self
        where
            S: Into<String>,
        { /* ... */ }
}

impl Field {
    pub fn new<S>(key: &'static str, value: S) -> Self
        where
            S: Into<Value>,
        { /* ... */ }
}

// ---- source: barter-integration/src/protocol/http/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// [`RestRequest`] build strategy for the API being interacted with.
/// 
/// An API that requires authenticated [`RestRequest`]s will likely utilise the configurable
/// [`RequestSigner`](private::RequestSigner) to sign the requests before building.
/// 
/// An API that requires no authentication may just add mandatory `reqwest` headers to the
/// [`RestRequest`] before building.
pub trait BuildStrategy {
    /// Use a [`RestRequest`] and [`reqwest::RequestBuilder`] to construct a [`reqwest::Request`]
    /// that is ready for executing.
    ///
    /// It is expected that any signing or performed during this method, or the addition of any
    /// `reqwest` headers.
    fn build<Request>(
        &self,
        request: Request,
        builder: reqwest::RequestBuilder,
    ) -> Result<reqwest::Request, SocketError>
    where
        Request: RestRequest;
}

/// Utilised by a [`RestClient`](rest::client::RestClient) to deserialise
/// [`RestRequest::Response`], and upon failure parses API errors
/// returned from the server.
pub trait HttpParser {
    type ApiError: DeserializeOwned;
    type OutputError: From<SocketError>;

    /// Attempt to parse a [`StatusCode`] & bytes payload into a deserialisable `Response`.
    fn parse<Response>(
        &self,
        status: StatusCode,
        payload: &[u8],
    ) -> Result<Response, Self::OutputError>
    where
        Response: DeserializeOwned,
    { /* ... */ }

    /// If [`parse`](Self::parse) fails to deserialise the `Ok(Response)`, this function parses
    /// to parse the API [`Self::ApiError`] associated with the response.
    fn parse_api_error(&self, status: StatusCode, error: Self::ApiError) -> Self::OutputError;
}

// ---- source: barter-integration/src/protocol/http/private/encoder.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/private/encoder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Encodes bytes data.
pub trait Encoder {
    /// Encodes the bytes data into some `String` format.
    fn encode<Bytes>(&self, data: Bytes) -> String
    where
        Bytes: AsRef<[u8]>;
}

#[derive(Debug, Copy, Clone)]
/// Encodes bytes data as a hex `String` using lowercase characters.
pub struct HexEncoder;

#[derive(Debug, Copy, Clone)]
/// Encodes bytes data as a base64 `String`.
pub struct Base64Encoder;

// ---- source: barter-integration/src/protocol/http/private/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/private/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[allow(clippy::needless_lifetimes)]
/// API specific signing logic used by a [`RequestSigner`].
pub trait Signer {
    /// Configuration required to sign the [`RestRequest`]s for this API server.
    type Config<'a>
    where
        Self: 'a;

    /// Generates a [`Self::Config`] for this [`RestRequest`] and
    /// [`RequestBuilder`](reqwest::RequestBuilder).
    ///
    /// # Examples
    ///
    /// ## Private REST Request: FTX
    /// ```rust,ignore
    /// fn config<Request>(&self, _: Request, _: &RequestBuilder) -> Self::Config
    /// where
    ///     Request: RestRequest
    /// {
    ///     FtxSignConfig {
    ///         api_key: self.api_key.as_str(),
    ///         time: Utc::now(),
    ///         method: Request::method(),
    ///         path: Request::path()
    ///     }
    /// }
    /// ```
    fn config<'a, Request>(
        &'a self,
        request: Request,
        builder: &reqwest::RequestBuilder,
    ) -> Result<Self::Config<'a>, SocketError>
    where
        Request: RestRequest;

    /// Generate the bytes to sign from the provided [`Self::Config`].
    ///
    /// # Examples
    ///
    /// ## Private REST Request: FTX
    /// ```rust,ignore
    /// fn add_bytes_to_sign<M>(mac: &mut M, config: &Self::Config) {
    ///     mac.update(config.time.to_string().as_bytes());
    ///     mac.update(config.method.as_str().as_bytes());
    ///     mac.update(config.path.as_bytes());
    /// }
    /// ```
    fn add_bytes_to_sign<M>(mac: &mut M, config: &Self::Config<'_>)
    where
        M: Mac;

    /// Build a signed [`reqwest::Request`] from the provided [`Self::Config`],
    /// [`RequestBuilder`](reqwest::RequestBuilder), and generated cryptographic signature `String`.
    ///
    /// # Examples
    ///
    /// ## Private REST Request: FTX
    /// ```rust,ignore
    /// fn build_signed_request(config: Self::Config, builder: RequestBuilder, signature: String) -> Result<reqwest::Request, SocketError> {
    ///     // Add Ftx required Headers & build reqwest::Request
    ///     builder
    ///         .header(HEADER_FTX_KEY, &self.api_key)
    ///         .header(HEADER_FTX_SIGN, &signature)
    ///         .header(HEADER_FTX_TS, &time)
    ///         .build()
    ///         .map_err(SocketError::from)
    /// }
    /// ```
    fn build_signed_request<'a>(
        config: Self::Config<'a>,
        builder: reqwest::RequestBuilder,
        signature: String,
    ) -> Result<reqwest::Request, SocketError>;
}

#[derive(Debug, Copy, Clone)]
/// Generically signs Http [`RestRequest`]s utilising API specific [`Signer`] logic, a hashable
/// [`Mac`], and a signature [`Encoder`].
pub struct RequestSigner<Sig, Hmac, SigEncoder> {
    signer: Sig,
    mac: Hmac,
    encoder: SigEncoder,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl RequestSigner {
    /// Construct a new [`Self`] using the provided API specific configuration.
    pub fn new(signer: Sig, mac: Hmac, encoder: SigEncoder) -> Self { /* ... */ }
}

// ---- source: barter-integration/src/protocol/http/public/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/public/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Copy, Clone)]
/// [`RestRequest`](super::RestRequest) [`BuildStrategy`] that builds a non-authenticated Http request with no headers.
pub struct PublicNoHeaders;

// ---- source: barter-integration/src/protocol/http/rest/client.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/rest/client.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
/// Configurable REST client capable of executing signed [`RestRequest`]s. Use this when
/// integrating APIs that require Http in order to interact with resources. Each API will require
/// a specific combination of [`Signer`](super::super::private::Signer), [`Mac`](hmac::Mac),
/// signature [`Encoder`](super::super::private::encoder::Encoder), and
/// [`HttpParser`].
pub struct RestClient<'a, Strategy, Parser> {
    /// HTTP [`reqwest::Client`] for executing signed [`reqwest::Request`]s.
    pub http_client: reqwest::Client,

    /// Base Url of the API being interacted with.
    pub base_url: Cow<'a, str>,

    /// [`RestRequest`] build strategy for the API being interacted with that implements
    /// [`BuildStrategy`].
    ///
    /// An authenticated [`RestClient`] will utilise API specific
    /// [`Signer`](super::super::private::Signer) logic, a hashable [`Mac`](hmac::Mac), and a
    /// signature [`Encoder`](super::super::private::encoder::Encoder). Where as a non authorised
    /// [`RestRequest`] may add any mandatory `reqwest` headers that are required.
    pub strategy: Strategy,

    /// [`HttpParser`] that deserialises [`RestRequest::Response`]s, and upon failure parses
    /// API errors returned from the server.
    pub parser: Parser,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl RestClient {
    /// Execute the provided [`RestRequest`].
    pub async fn execute<Request>(
            &self,
            request: Request,
        ) -> Result<(Request::Response, Metric), Parser::OutputError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Use the provided [`RestRequest`] to construct a signed Http [`reqwest::Request`].
    pub fn build<Request>(&self, request: Request) -> Result<reqwest::Request, SocketError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Execute the built [`reqwest::Request`] using the [`reqwest::Client`].
    /// 
    /// Measures and returns the Http request round trip duration.
    pub async fn measured_execution<Request>(
            &self,
            request: reqwest::Request,
        ) -> Result<(reqwest::StatusCode, Bytes, Metric), SocketError>
        where
            Request: RestRequest,
        { /* ... */ }
    /// Construct a new [`Self`] using the provided configuration.
    pub fn new<Url: Into<Cow<'a, str>>>(base_url: Url, strategy: Strategy, parser: Parser) -> Self { /* ... */ }
    /// Construct a new [`Self`] using the provided configuration and a pre-built
    /// [`reqwest::Client`].
    /// 
    /// Use this when you need custom client configuration (timeouts, connection
    /// pooling, TLS settings, etc.) instead of the defaults from
    /// [`reqwest::Client::new()`].
    pub fn with_http_client<Url: Into<Cow<'a, str>>>(
            base_url: Url,
            strategy: Strategy,
            parser: Parser,
            http_client: reqwest::Client,
        ) -> Self { /* ... */ }
}

// ---- source: barter-integration/src/protocol/http/rest/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/http/rest/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Http REST request that can be executed by a [`RestClient`](self::client::RestClient).
pub trait RestRequest {
    /// Expected response type if this request was successful.
    type Response: DeserializeOwned;

    /// Serialisable query parameters type - use unit struct () if not required for this request.
    type QueryParams: Serialize;

    /// Serialisable Body type - use unit struct () if not required for this request.
    type Body: Serialize;

    /// Additional [`Url`](url::Url) path to the resource.
    fn path(&self) -> std::borrow::Cow<'static, str>;

    /// Http [`reqwest::Method`] of this request.
    fn method() -> reqwest::Method;

    /// Optional query parameters for this request.
    fn query_params(&self) -> Option<&Self::QueryParams> { /* ... */ }

    /// Optional Body for this request.
    fn body(&self) -> Option<&Self::Body> { /* ... */ }

    /// Http request timeout [`Duration`].
    fn timeout() -> Duration { /* ... */ }
}

// ---- source: barter-integration/src/protocol/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// `StreamParser`s are capable of parsing the input messages from a given stream protocol
/// (eg/ WebSocket, Financial Information eXchange (FIX), etc.) and deserialising into an `Output`.
pub trait StreamParser<Output> {
    type Stream: Stream;
    type Message;
    type Error;

    fn parse(input: Result<Self::Message, Self::Error>) -> Option<Result<Output, SocketError>>;
}

// ---- source: barter-integration/src/protocol/websocket.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/protocol/websocket.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convenient type alias for a tungstenite `WebSocketStream`.
pub type WebSocket = tokio_tungstenite::WebSocketStream<MaybeTlsStream<TcpStream>>;

/// Convenient type alias for the `Sink` half of a tungstenite [`WebSocket`].
pub type WsSink = futures::stream::SplitSink<WebSocket, WsMessage>;

/// Convenient type alias for the `Stream` half of a tungstenite [`WebSocket`].
pub type WsStream = futures::stream::SplitStream<WebSocket>;

/// Communicative type alias for a tungstenite [`WebSocket`] `Message`.
pub type WsMessage = tokio_tungstenite::tungstenite::Message;

/// Communicative type alias for a tungstenite [`WebSocket`] `Error`.
pub type WsError = tokio_tungstenite::tungstenite::Error;

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// Default [`StreamParser`] implementation for a [`WebSocket`].
pub struct WebSocketSerdeParser;

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`StreamParser`] implementation for a [`WebSocket`] that decodes protobuf
/// binary payloads.
pub struct WebSocketProtobufParser;

/// Process a payload of `String` by deserialising into an `ExchangeMessage`.
pub fn process_text<ExchangeMessage>(
    payload: Utf8Bytes,
) -> Option<Result<ExchangeMessage, SocketError>>
where
    ExchangeMessage: for<'de> Deserialize<'de>,
{ /* ... */ }

/// Process a payload of `Vec<u8>` bytes by deserialising into an `ExchangeMessage`.
pub fn process_binary<ExchangeMessage>(
    payload: Bytes,
) -> Option<Result<ExchangeMessage, SocketError>>
where
    ExchangeMessage: for<'de> Deserialize<'de>,
{ /* ... */ }

/// Basic process for a [`WebSocket`] ping message. Logs the payload at `trace` level.
pub fn process_ping<ExchangeMessage>(ping: Bytes) -> Option<Result<ExchangeMessage, SocketError>> { /* ... */ }

/// Basic process for a [`WebSocket`] pong message. Logs the payload at `trace` level.
pub fn process_pong<ExchangeMessage>(pong: Bytes) -> Option<Result<ExchangeMessage, SocketError>> { /* ... */ }

/// Basic process for a [`WebSocket`] CloseFrame message. Logs the payload at `trace` level.
pub fn process_close_frame<ExchangeMessage>(
    close_frame: Option<CloseFrame>,
) -> Option<Result<ExchangeMessage, SocketError>> { /* ... */ }

/// Basic process for a [`WebSocket`] Frame message. Logs the payload at `trace` level.
pub fn process_frame<ExchangeMessage>(
    frame: Frame,
) -> Option<Result<ExchangeMessage, SocketError>> { /* ... */ }

/// Connect asynchronously to a [`WebSocket`] server.
pub async fn connect<R>(request: R) -> Result<WebSocket, SocketError>
where
    R: IntoClientRequest + Unpin + Debug,
{ /* ... */ }

/// Determine whether a [`WsError`] indicates the [`WebSocket`] has disconnected.
pub fn is_websocket_disconnected(error: &WsError) -> bool { /* ... */ }

// ---- source: barter-integration/src/snapshot.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/snapshot.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug,
    Clone,
    Copy,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Deserialize,
    Serialize,
    Constructor,
    From,
)]
pub struct Snapshot<T>(pub T);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct SnapUpdates<Snapshot, Updates> {
    pub snapshot: Snapshot,
    pub updates: Updates,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Snapshot {
    pub fn value(&self) -> &T { /* ... */ }
    pub fn as_ref(&self) -> Snapshot<&T> { /* ... */ }
    pub fn map<F, N>(self, op: F) -> Snapshot<N>
        where
            F: Fn(T) -> N,
        { /* ... */ }
}

// ---- source: barter-integration/src/stream/indexed.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/stream/indexed.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait Indexer {
    type Unindexed;
    type Indexed;
    fn index(&self, item: Self::Unindexed) -> Result<Self::Indexed, IndexError>;
}

#[derive(Debug, Constructor)]
#[pin_project]
pub struct IndexedStream<Indexer, Stream> {
    #[pin]
    pub stream: Stream,
    pub indexer: Indexer,
}

// ---- source: barter-integration/src/stream/merge.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/stream/merge.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Merge two Streams and terminate when either Stream terminates. Merged Stream is fused, so will
/// end after the first `None`.
pub fn merge<L, R>(left: L, right: R) -> impl Stream<Item = L::Item>
where
    L: Stream,
    R: Stream<Item = L::Item>,
{ /* ... */ }

// ---- source: barter-integration/src/stream/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/stream/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
#[pin_project]
/// An [`ExchangeStream`] is a communication protocol agnostic [`Stream`]. It polls protocol
/// messages from the inner [`Stream`], and transforms them into the desired output data structure.
pub struct ExchangeStream<Protocol, InnerStream, StreamTransformer>
where
    Protocol: StreamParser<StreamTransformer::Input>,
    InnerStream: Stream,
    StreamTransformer: Transformer,
{
    #[pin]
    pub stream: InnerStream,
    pub transformer: StreamTransformer,
    pub buffer: VecDeque<Result<StreamTransformer::Output, StreamTransformer::Error>>,
    pub protocol_marker: PhantomData<Protocol>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExchangeStream {
    pub fn new(
            stream: InnerStream,
            transformer: StreamTransformer,
            buffer: VecDeque<Result<StreamTransformer::Output, StreamTransformer::Error>>,
        ) -> Self { /* ... */ }
}

// ---- source: barter-integration/src/subscription.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/subscription.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// New type representing a unique `String` identifier for a stream that has been subscribed to.
/// This is used to identify data structures received over the socket.
/// 
/// For example, `Barter-Data` uses this identifier to associate received data structures from the
/// execution with the original `Barter-Data` `Subscription` that was actioned over the socket.
/// 
/// Note: Each execution will require the use of different `String` identifiers depending on the
/// data structures they send.
/// 
/// eg/ [`SubscriptionId`] of an `FtxTrade` is "{BASE}/{QUOTE}" (ie/ market).
/// eg/ [`SubscriptionId`] of a `BinanceTrade` is "{base}{symbol}@trade" (ie/ channel).
pub struct SubscriptionId(pub SmolStr);

