// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// aggregate: barter_collector.rs
// crates: barter_collector

// ---- source: barter-collector/src/caching.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/caching.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Compute the SHA-256 hex digest of the given data.
pub fn compute_sha256(data: &[u8]) -> String { /* ... */ }

/// Check whether a `.verified` marker file exists with a matching checksum.
/// 
/// The marker file format is: `<sha256hex>  <original_filename>\n`.
/// Returns `true` if the marker exists and its stored hash matches `expected_hash`.
pub fn should_skip(marker_path: &Path, expected_hash: &str) -> bool { /* ... */ }

/// Write a `.verified` marker file atomically (tmp + rename).
/// 
/// Format: `<sha256hex>  <original_filename>\n`.
/// Failures are non-fatal and logged as warnings.
pub fn write_verified_marker(marker_path: &Path, hash: &str, original_filename: &str) { /* ... */ }

/// Build the `.verified` marker path for a given archive URL and cache directory.
pub fn marker_path_for_url(cache_dir: &Path, url: &str) -> PathBuf { /* ... */ }

// ---- source: barter-collector/src/config.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/config.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone)]
#[non_exhaustive]
/// Central configuration for collector orchestration.
/// 
/// Owns concurrency, caching, retry, and pagination limits that were
/// previously scattered across `BulkConfig`, `RetryPolicy` fields on
/// individual clients, and `MAX_TRADE_PAGES` constants.
pub struct CollectorConfig {
    /// Maximum number of concurrent bulk downloads.
    pub concurrency: usize,
    /// Optional directory for caching downloaded files and `.verified` markers.
    pub cache_dir: Option<PathBuf>,
    /// Retry policy for all fetcher calls.
    pub retry: RetryPolicy,
    /// Maximum number of trade pagination pages before aborting (safety limit).
    pub max_trade_pages: u32,
}

// ---- source: barter-collector/src/filters.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/filters.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Filter trades to the `[start, end]` time range (inclusive on both bounds).
pub fn filter_trades_by_time(
    trades: Vec<RestTrade>,
    start: Option<DateTime<Utc>>,
    end: Option<DateTime<Utc>>,
) -> Vec<RestTrade> { /* ... */ }

// ---- source: barter-collector/src/pagination.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/pagination.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
#[non_exhaustive]
/// Outcome of one pagination step.
pub enum PageResult<T> {
    /// Yield this batch and continue with the next page.
    Continue(Vec<T>),
    /// Yield this batch and stop — no more pages.
    Done(Vec<T>),
    /// No more data — stop without yielding.
    Empty,
}

/// Strategy for paginating through a fetcher.
/// 
/// Each exchange provides its own implementation. The collector's
/// `stream::unfold` calls `fetch_page` in a loop until `Done`/`Empty`.
/// 
/// This replaces the 9 per-exchange `PaginationState` structs in
/// `barter-data` with one trait plus one impl per exchange x data-type
/// combination.
/// 
/// Implementations are stateful (carry cursor, page count, etc.).
pub trait PaginationStrategy: Send {
    /// The type of item yielded by each page (e.g., `Candle` or `RestTrade`).
    type Item: Send;

    /// Fetch one page of data. Advances internal cursor state.
    ///
    /// The collector wraps this call with retry + rate limiting.
    fn fetch_page(
        &mut self,
    ) -> Pin<Box<dyn Future<Output = Result<PageResult<Self::Item>, DataError>> + Send + '_>>;
}

// ---- source: barter-collector/src/scheduling.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/scheduling.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Generate an inclusive sequence of dates from `start` to `end`.
pub fn date_range(start: NaiveDate, end: NaiveDate) -> Vec<NaiveDate> { /* ... */ }

/// Choose monthly archives for complete months, daily for partial months.
/// 
/// Given an inclusive date range `[start, end]`, returns:
/// - `complete_months`: `Vec<(year, month)>` for months entirely within the range.
/// - `remaining_days`: `Vec<NaiveDate>` for days in partial months at the boundaries.
/// 
/// A month is "complete" if both its first and last day fall within `[start, end]`.
pub fn partition_date_range(start: NaiveDate, end: NaiveDate) -> (Vec<(i32, u32)>, Vec<NaiveDate>) { /* ... */ }

/// Return the last day of the given month.
/// 
/// # Panics
/// 
/// Panics if `month` is not 1..=12 or if `year` overflows the calendar.
pub fn last_day_of_month(year: i32, month: u32) -> NaiveDate { /* ... */ }

// ---- source: barter-collector/src/streams.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_collector
// source: barter-collector/src/streams.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Stream data by driving a [`PaginationStrategy`] in a loop.
/// 
/// Uses `stream::unfold` with the strategy as state. Acquires the rate
/// limiter and retries on each page fetch (fixes the
/// rate-limiter-outside-retry bug from barter-data).
pub fn stream_paginated<S: PaginationStrategy + 'static>(
    strategy: S,
    rate_limiter: Arc<ExchangeRateLimiter>,
) -> Pin<Box<dyn Stream<Item = Result<Vec<S::Item>, DataError>> + Send>> { /* ... */ }

/// Stream bulk data by fanning out over dates with bounded concurrency.
/// 
/// Generic over any async function that fetches a single day's data.
/// 404 dates (returning `Ok(None)`) are silently skipped.
pub fn stream_bulk<'a, T, Fut>(
    dates: Vec<chrono::NaiveDate>,
    concurrency: usize,
    fetch_day: impl Fn(chrono::NaiveDate) -> Fut + Send + 'a,
) -> Pin<Box<dyn Stream<Item = Result<Vec<T>, DataError>> + Send + 'a>>
where
    T: Send + 'a,
    Fut: std::future::Future<Output = Result<Option<Vec<T>>, DataError>> + Send + 'a,
{ /* ... */ }

