// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// aggregate: barter_instrument.rs
// crates: barter_instrument

// ---- source: barter-instrument/src/asset/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/asset/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display,
)]
/// Unique identifier for an [`Asset`].
pub struct AssetId(pub u64);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct AssetIndex(pub usize);

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub struct ExchangeAsset<Asset> {
    pub exchange: ExchangeId,
    pub asset: Asset,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub struct Asset {
    pub name_internal: AssetNameInternal,
    pub name_exchange: AssetNameExchange,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display)]
#[serde(rename_all = "snake_case")]
pub enum AssetKind {
    Crypto,
    Fiat,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display)]
/// Special type that represents a "base" [`Asset`].
/// 
/// Examples: <br>
/// a) Instrument = btc_usdt_spot, [`BaseAsset`] => btc <br>
/// b) Instrument = eth_btc_spot, [`BaseAsset`] => eth
pub struct BaseAsset;

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display)]
/// Special type that represents a "quote" [`Asset`].
/// 
/// Examples: <br>
/// a) Instrument = btc_usdt_spot, [`QuoteAsset`] => usdt <br>
/// b) Instrument = eth_btc_spot, [`QuoteAsset`] => btc
pub struct QuoteAsset;

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AssetIndex {
    pub fn index(&self) -> usize { /* ... */ }
}

impl Asset {
    pub fn new<Internal, Exchange>(name_internal: Internal, name_exchange: Exchange) -> Self
        where
            Internal: Into<AssetNameInternal>,
            Exchange: Into<AssetNameExchange>,
        { /* ... */ }
    pub fn new_from_exchange<S>(name_exchange: S) -> Self
        where
            S: Into<AssetNameExchange>,
        { /* ... */ }
}

impl ExchangeAsset {
    pub fn new<A>(exchange: ExchangeId, asset: A) -> Self
        where
            A: Into<Asset>,
        { /* ... */ }
}

// ---- source: barter-instrument/src/asset/name.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/asset/name.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Barter lowercase `SmolStr` representation for an [`Asset`](super::Asset) - not unique across
/// exchanges.
/// 
/// This may or may not be different from an execution's representation.
/// 
/// For example, some exchanges may refer to "btc" as "xbt".
pub struct AssetNameInternal(SmolStr);

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Exchange `SmolStr` representation for an [`Asset`](super::Asset) - not unique across exchanges.
/// 
/// For example: `AssetNameExchange("XBT")`, which is distinct from the internal representation
/// of the asset, such as `AssetIndex(1)` or `AssetNameInternal("btc")`.
pub struct AssetNameExchange(SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AssetNameInternal {
    /// Construct a new lowercase [`Self`] from the provided `Into<SmolStr>`.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Return the internal asset `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

impl AssetNameExchange {
    /// Construct a new [`Self`] from the provided `Into<SmolStr>`.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Return the execution asset `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

// ---- source: barter-instrument/src/exchange.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/exchange.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct ExchangeIndex(pub usize);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display,
)]
#[serde(rename = "execution", rename_all = "snake_case")]
/// Unique identifier for an execution server.
/// 
/// ### Notes
/// An execution may have a distinct server for different
/// [`InstrumentKinds`](super::instrument::kind::InstrumentKind).
/// 
/// For example, BinanceSpot and BinanceFuturesUsd have distinct APIs, and are therefore
/// represented as unique variants.
pub enum ExchangeId {
    Other,
    Simulated,
    Mock,
    BinanceFuturesCoin,
    BinanceFuturesUsd,
    BinanceOptions,
    BinancePortfolioMargin,
    BinanceSpot,
    BinanceUs,
    Bitazza,
    Bitfinex,
    Bitflyer,
    Bitget,
    Bitmart,
    BitmartFuturesUsd,
    Bitmex,
    Bitso,
    Bitstamp,
    Bitvavo,
    Bithumb,
    BybitPerpetualsUsd,
    BybitSpot,
    Cexio,
    Coinbase,
    CoinbaseInternational,
    Cryptocom,
    Deribit,
    GateioFuturesBtc,
    GateioFuturesUsd,
    GateioOptions,
    GateioPerpetualsBtc,
    GateioPerpetualsUsd,
    GateioSpot,
    Gemini,
    Hitbtc,
    #[serde(alias = "huobi")]
    Htx,
    Hyperliquid,
    Kraken,
    Kucoin,
    Liquid,
    Mexc,
    OkxPerpetualsUsd,
    OkxSpot,
    Poloniex,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExchangeIndex {
    pub fn index(&self) -> usize { /* ... */ }
}

impl ExchangeId {
    /// Return the &str representation of this [`ExchangeId`]
    pub fn as_str(&self) -> &'static str { /* ... */ }
}

// ---- source: barter-instrument/src/index/builder.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/index/builder.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Default)]
pub struct IndexedInstrumentsBuilder {
    exchanges: Vec<ExchangeId>,
    instruments: Vec<Instrument<ExchangeId, Asset>>,
    assets: Vec<ExchangeAsset<Asset>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl IndexedInstrumentsBuilder {
    pub fn new() -> Self { /* ... */ }
    pub fn add_instrument(mut self, instrument: Instrument<ExchangeId, Asset>) -> Self { /* ... */ }
    pub fn build(mut self) -> IndexedInstruments { /* ... */ }
}

// ---- source: barter-instrument/src/index/error.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/index/error.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all possible errors that can occur when searching for indexes in an
/// [`IndexedInstruments`](super::IndexedInstruments) collection.
pub enum IndexError {
    /// Indicates a failure to find an [`ExchangeIndex`](crate::exchange::ExchangeIndex) for a
    /// given exchange identifier.
    ///
    /// Contains a description of the failed lookup attempt.
    #[error("ExchangeIndex: {0}")]
    ExchangeIndex(String),

    /// Indicates a failure to find an [`AssetIndex`](crate::asset::AssetIndex) for a given
    /// asset identifier.
    ///
    /// Contains a description of the failed lookup attempt.
    #[error("AssetIndex: {0}")]
    AssetIndex(String),

    /// Indicates a failure to find an [`InstrumentIndex`](crate::instrument::InstrumentIndex)
    /// for a given instrument identifier.
    ///
    /// Contains a description of the failed lookup attempt.
    #[error("InstrumentIndex: {0}")]
    InstrumentIndex(String),
}

// ---- source: barter-instrument/src/index/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/index/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Deserialize, Serialize)]
/// Indexed collection of exchanges, assets, and instruments.
/// 
/// Initialise incrementally via the [`IndexedInstrumentsBuilder`], or all at once via the
/// constructor.
/// 
/// The indexed collection is useful for creating efficient O(1) constant lookup state management
/// systems where the state is keyed on an instrument, asset, or exchange.
/// 
/// For example uses cases, see the central `barter` crate `EngineState` design.
/// 
/// # Index Relationships
/// - `ExchangeIndex`: Unique index for each [`ExchangeId`] added during initialisation.
/// - `InstrumentIndex`: Unique identifier for each [`Instrument`] added during initialisation.
/// - `AssetIndex`: Unique identifier for each [`ExchangeAsset`] added during initialisation.
pub struct IndexedInstruments {
    exchanges: Vec<Keyed<ExchangeIndex, ExchangeId>>,
    assets: Vec<Keyed<AssetIndex, ExchangeAsset<Asset>>>,
    instruments:
        Vec<Keyed<InstrumentIndex, Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl IndexedInstruments {
    /// Initialises a new `IndexedInstruments` from an iterator of [`Instrument`]s.
    /// 
    /// This method indexes all unique exchanges, assets, and instruments, creating efficient
    /// lookup tables for each entity type.
    /// 
    /// Note that once an `IndexedInstruments` has been constructed, it cannot be mutated (this
    /// could invalidate existing index lookup tables).
    /// 
    /// For incremental initialisation, see the [`IndexedInstrumentsBuilder`].
    pub fn new<Iter, I>(instruments: Iter) -> Self
        where
            Iter: IntoIterator<Item = I>,
            I: Into<Instrument<ExchangeId, Asset>>,
        { /* ... */ }
    /// Returns a new [`IndexedInstrumentsBuilder`] useful for incremental initialisation of
    /// `IndexedInstruments`.
    pub fn builder() -> IndexedInstrumentsBuilder { /* ... */ }
    /// Returns a reference to the [`ExchangeIndex`] <--> [`ExchangeId`] associations.
    pub fn exchanges(&self) -> &[Keyed<ExchangeIndex, ExchangeId>] { /* ... */ }
    /// Returns a reference to the [`AssetIndex`] <--> [`ExchangeAsset`] associations.
    pub fn assets(&self) -> &[Keyed<AssetIndex, ExchangeAsset<Asset>>] { /* ... */ }
    /// Returns a reference to the [`InstrumentIndex`] <--> [`Instrument`] associations.
    pub fn instruments(
            &self,
        ) -> &[Keyed<InstrumentIndex, Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>] { /* ... */ }
    /// Finds the [`ExchangeIndex`] associated with the provided [`ExchangeId`].
    /// 
    /// # Arguments
    /// * `exchange` - The exchange ID to look up
    /// 
    /// # Returns
    /// * `Ok(ExchangeIndex)` - exchange found.
    /// * `Err(IndexError)` - exchange not found.
    pub fn find_exchange_index(&self, exchange: ExchangeId) -> Result<ExchangeIndex, IndexError> { /* ... */ }
    pub fn find_exchange(&self, index: ExchangeIndex) -> Result<ExchangeId, IndexError> { /* ... */ }
    /// Finds the [`AssetIndex`] associated with the provided `ExchangeId` and `AssetNameInterval`.
    /// 
    /// # Arguments
    /// * `exchange` - The `ExchangeId` associated with the asset.
    /// * `name` - The `AssetNameInternal` associated with the asset (eg/ "btc", "usdt", etc).
    /// 
    /// # Returns
    /// * `Ok(AssetIndex)` - exchange asset found.
    /// * `Err(IndexError)` - exchange asset not found.
    pub fn find_asset_index(
            &self,
            exchange: ExchangeId,
            name: &AssetNameInternal,
        ) -> Result<AssetIndex, IndexError> { /* ... */ }
    pub fn find_asset(&self, index: AssetIndex) -> Result<&ExchangeAsset<Asset>, IndexError> { /* ... */ }
    /// Finds the [`InstrumentIndex`] associated with the provided `ExchangeId` and
    /// `InstrumentNameInternal`.
    /// 
    /// # Arguments
    /// * `exchange` - The `ExchangeId` associated with the instrument.
    /// * `name` - The `InstrumentNameInternal` associated with the instrument (eg/ binance_spot_btc_usdt).
    /// 
    /// # Returns
    /// * `Ok(AssetIndex)` - instrument found.
    /// * `Err(IndexError)` - instrument not found.
    pub fn find_instrument_index(
            &self,
            exchange: ExchangeId,
            name: &InstrumentNameInternal,
        ) -> Result<InstrumentIndex, IndexError> { /* ... */ }
    pub fn find_instrument(
            &self,
            index: InstrumentIndex,
        ) -> Result<&Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>, IndexError> { /* ... */ }
}

// ---- source: barter-instrument/src/instrument/kind/future.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/kind/future.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// `FutureContract` specification containing all the information needed to fully identify a
/// future instrument.
/// 
/// # Type Parameters
/// * `AssetKey` - Type used to identify the settlement asset for the option contract.
/// 
/// # Fields
/// * `contract_size` - Multiplier that determines how many of the underlying asset the contract represents.
/// * `settlement_asset` - Asset used for settlement when the future expires.
/// * `expiry` - The date and time when the future expires.
pub struct FutureContract<AssetKey> {
    pub contract_size: Decimal,
    pub settlement_asset: AssetKey,
    #[serde(with = "chrono::serde::ts_milliseconds")]
    pub expiry: DateTime<Utc>,
}

// ---- source: barter-instrument/src/instrument/kind/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/kind/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
/// [`Instrument`](super::Instrument) kind, one of `Spot`, `Perpetual`, `Future` and `Option`.
pub enum InstrumentKind<AssetKey> {
    Spot,
    Perpetual(PerpetualContract<AssetKey>),
    Future(FutureContract<AssetKey>),
    Option(OptionContract<AssetKey>),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl InstrumentKind {
    /// Returns the `contract_size` value for the `InstrumentKind`.
    /// 
    /// Note that `Spot` is always `Decimal::ONE`.
    pub fn contract_size(&self) -> Decimal { /* ... */ }
    /// For `Perpetual`, `Future` & `Option` variants of [`Self`], returns the settlement
    /// `AssetKey`, and `None` for Spot.
    pub fn settlement_asset(&self) -> Option<&AssetKey> { /* ... */ }
    /// Determines if the provided [`MarketDataInstrumentKind`] is equivalent to [`Self`] (ignores
    /// settlement asset).
    pub fn eq_market_data_instrument_kind(&self, other: &MarketDataInstrumentKind) -> bool { /* ... */ }
}

// ---- source: barter-instrument/src/instrument/kind/option.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/kind/option.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// `OptionContract` specification containing all the information needed to fully identify an
/// option instrument.
/// 
/// # Type Parameters
/// * `AssetKey` - Type used to identify the settlement asset for the option contract.
/// 
/// # Fields
/// * `contract_size` - Multiplier that determines how many of the underlying asset the contract represents.
/// * `settlement_asset` - Asset used for settlement when the option is exercised.
/// * `kind` - Call (right to buy) or Put (right to sell).
/// * `exercise` - Exercise style (American, European, or Bermudan) defining when the option
/// can be exercised.
/// * `expiry` - The date and time when the option expires.
/// * `strike` - The price at which the option holder can buy (for calls) or sell (for puts)
/// the underlying asset upon exercise.
pub struct OptionContract<AssetKey> {
    pub contract_size: Decimal,
    pub settlement_asset: AssetKey,
    pub kind: OptionKind,
    pub exercise: OptionExercise,
    #[serde(with = "chrono::serde::ts_milliseconds")]
    pub expiry: DateTime<Utc>,
    pub strike: Decimal,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
/// [`OptionContract`] kind - Put or Call.
pub enum OptionKind {
    #[serde(alias = "CALL", alias = "Call")]
    Call,
    #[serde(alias = "PUT", alias = "Put")]
    Put,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
/// [`OptionContract`] exercise style.
pub enum OptionExercise {
    #[serde(alias = "AMERICAN", alias = "American")]
    American,
    #[serde(alias = "BERMUDAN", alias = "Bermudan")]
    Bermudan,
    #[serde(alias = "EUROPEAN", alias = "European")]
    European,
}

// ---- source: barter-instrument/src/instrument/kind/perpetual.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/kind/perpetual.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// `PerpetualContract` specification containing all the information needed to fully identify a
/// perpetual instrument.
/// 
/// # Type Parameters
/// * `AssetKey` - Type used to identify the settlement asset for the option contract.
/// 
/// # Fields
/// * `contract_size` - Multiplier that determines how many of the underlying asset the contract represents.
/// * `settlement_asset` - Asset used for settlement.
pub struct PerpetualContract<AssetKey> {
    pub contract_size: Decimal,
    pub settlement_asset: AssetKey,
}

// ---- source: barter-instrument/src/instrument/market_data/kind.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/market_data/kind.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
/// Defines the type of [`MarketDataInstrument`](super::MarketDataInstrument) which is being
/// traded on a given `base_quote` market.
pub enum MarketDataInstrumentKind {
    #[default]
    Spot,
    Perpetual,
    Future(MarketDataFutureContract),
    Option(MarketDataOptionContract),
}

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
pub struct MarketDataFutureContract {
    #[serde(with = "chrono::serde::ts_milliseconds")]
    pub expiry: DateTime<Utc>,
}

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
pub struct MarketDataOptionContract {
    pub kind: OptionKind,
    pub exercise: OptionExercise,
    #[serde(with = "chrono::serde::ts_milliseconds")]
    pub expiry: DateTime<Utc>,
    pub strike: Decimal,
}

// ---- source: barter-instrument/src/instrument/market_data/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/market_data/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
/// Barter representation of an `MarketDataInstrument`. Used to uniquely identify a `base_quote`
/// pair, and it's associated instrument type.
/// 
/// eg/ MarketDataInstrument { base: "btc", quote: "usdt", kind: Spot }
pub struct MarketDataInstrument {
    pub base: AssetNameInternal,
    pub quote: AssetNameInternal,
    #[serde(rename = "instrument_kind")]
    pub kind: MarketDataInstrumentKind,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MarketDataInstrument {
    /// Constructs a new [`MarketDataInstrument`] using the provided configuration.
    pub fn new<S>(base: S, quote: S, kind: MarketDataInstrumentKind) -> Self
        where
            S: Into<AssetNameInternal>,
        { /* ... */ }
}

// ---- source: barter-instrument/src/instrument/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display,
)]
/// Unique identifier for an `Instrument` traded on an execution.
/// 
/// Used to key data events in a memory efficient way.
pub struct InstrumentId(pub u64);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentIndex(pub usize);

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// Comprehensive Instrument model, containing all the data required to subscribe to market data
/// and generate correct orders.
pub struct Instrument<ExchangeKey, AssetKey> {
    pub exchange: ExchangeKey,
    pub name_internal: InstrumentNameInternal,
    pub name_exchange: InstrumentNameExchange,
    pub underlying: Underlying<AssetKey>,
    pub quote: InstrumentQuoteAsset,
    #[serde(alias = "instrument_kind")]
    pub kind: InstrumentKind<AssetKey>,
    pub spec: Option<InstrumentSpec<AssetKey>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Instrument {
    /// Construct a new `Instrument` with the provided data.
    /// 
    /// This constructor assumes the [`InstrumentNameInternal`] can be constructed in the default
    /// style via the [`InstrumentNameInternal::new_from_exchange`] constructor.
    pub fn new<NameInternal, NameExchange>(
            exchange: ExchangeKey,
            name_internal: NameInternal,
            name_exchange: NameExchange,
            underlying: Underlying<AssetKey>,
            quote: InstrumentQuoteAsset,
            kind: InstrumentKind<AssetKey>,
            spec: Option<InstrumentSpec<AssetKey>>,
        ) -> Self
        where
            NameInternal: Into<InstrumentNameInternal>,
            NameExchange: Into<InstrumentNameExchange>,
        { /* ... */ }
    /// Construct a new `Spot` `Instrument` with the provided data.
    /// 
    /// This constructor assumes the [`InstrumentNameInternal`] can be constructed in the default
    /// style via the [`InstrumentNameInternal::new_from_exchange`] constructor.
    pub fn spot<NameInternal, NameExchange>(
            exchange: ExchangeKey,
            name_internal: NameInternal,
            name_exchange: NameExchange,
            underlying: Underlying<AssetKey>,
            spec: Option<InstrumentSpec<AssetKey>>,
        ) -> Self
        where
            NameInternal: Into<InstrumentNameInternal>,
            NameExchange: Into<InstrumentNameExchange>,
        { /* ... */ }
    /// Map this Instruments `ExchangeKey` to a new key.
    pub fn map_exchange_key<NewExchangeKey>(
            self,
            exchange: NewExchangeKey,
        ) -> Instrument<NewExchangeKey, AssetKey> { /* ... */ }
    /// Map this Instruments `AssetKey` to a new key, using the provided lookup closure.
    pub fn map_asset_key_with_lookup<FnFindAsset, NewAssetKey, Error>(
            self,
            find_asset: FnFindAsset,
        ) -> Result<Instrument<ExchangeKey, NewAssetKey>, Error>
        where
            FnFindAsset: Fn(&AssetKey) -> Result<NewAssetKey, Error>,
        { /* ... */ }
}

impl InstrumentIndex {
    pub fn index(&self) -> usize { /* ... */ }
}

// ---- source: barter-instrument/src/instrument/name.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/name.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Barter lowercase `SmolStr` representation for an [`Instrument`](super::Instrument) - unique
/// across all exchanges.
/// 
/// Note: Binance btc_usdt spot is not considered the same instrument as Bitfinex btc_usdt spot.
pub struct InstrumentNameInternal(pub SmolStr);

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Display)]
/// Exchange `SmolStr` representation for an [`Instrument`](super::Instrument) - most likely not
/// unique across all exchanges.
/// 
/// For example: `InstrumentNameExchange("XBT-USDT")`, which is distinct from the internal
/// representation of the instrument, such as `InstrumentIndex(1)` or
/// `InstrumentNameInternal("btc_usdt"`.
pub struct InstrumentNameExchange(SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl InstrumentNameExchange {
    /// Construct a new [`Self`] from the provided `Into<SmolStr>`.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Return the execution instrument `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

impl InstrumentNameInternal {
    /// Construct a new lowercase [`Self`] from the provided `Into<SmolStr>`.
    /// 
    /// Should be unique across exchanges.
    pub fn new<S>(name: S) -> Self
        where
            S: Into<SmolStr>,
        { /* ... */ }
    /// Construct a new lowercase [`Self`], combining the [`ExchangeId`] and
    /// base and quote [`AssetNameExchange`]s.
    /// 
    /// Generates an internal instrument identifier unique across exchanges.
    pub fn new_from_exchange_underlying<Ass>(exchange: ExchangeId, base: &Ass, quote: &Ass) -> Self
        where
            for<'a> &'a Ass: Into<&'a AssetNameExchange>,
        { /* ... */ }
    /// Construct a new lowercase [`Self`], combining the [`ExchangeId`] and
    /// [`InstrumentNameExchange`].
    /// 
    /// Generates an internal instrument identifier unique across exchanges.
    pub fn new_from_exchange<S>(exchange: ExchangeId, name_exchange: S) -> Self
        where
            S: Into<InstrumentNameExchange>,
        { /* ... */ }
    /// Return the internal instrument `SmolStr` name of [`Self`].
    pub fn name(&self) -> &SmolStr { /* ... */ }
}

// ---- source: barter-instrument/src/instrument/quote.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/quote.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// Instrument quote asset.
/// 
/// Note that all `Spot` instruments are quoted in the (underlying) quote asset.
pub enum InstrumentQuoteAsset {
    /// "In-kind" pricing (unusual) using the underlying base asset as the quote asset.
    ///
    /// For example, if some derivative for underlying=btc_usdt was quoted in btc.
    #[serde(alias = "underlying_base")]
    UnderlyingBase,

    /// Standard pricing using the underlying quote as the quote asset.
    ///
    /// For example, all spot instruments are quoted in the (underlying) quote asset.
    #[serde(alias = "underlying_quote")]
    UnderlyingQuote,
}

// ---- source: barter-instrument/src/instrument/spec.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/instrument/spec.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentSpec<AssetKey> {
    pub price: InstrumentSpecPrice,
    pub quantity: InstrumentSpecQuantity<AssetKey>,
    pub notional: InstrumentSpecNotional,
}

#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentSpecPrice {
    pub min: Decimal,
    pub tick_size: Decimal,
}

#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentSpecQuantity<AssetKey> {
    pub unit: OrderQuantityUnits<AssetKey>,
    pub min: Decimal,
    pub increment: Decimal,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub enum OrderQuantityUnits<AssetKey> {
    Asset(AssetKey),
    Contract,
    Quote,
}

#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentSpecNotional {
    pub min: Decimal,
}

// ---- source: barter-instrument/src/lib.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_instrument
// source: barter-instrument/src/lib.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
/// A keyed value.
/// 
/// eg/ Keyed<InstrumentIndex, Instrument>
pub struct Keyed<Key, Value> {
    pub key: Key,
    pub value: Value,
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
/// Instrument Underlying containing a base and quote asset.
/// 
/// eg/ Underlying { base: "btc", quote: "usdt" }
pub struct Underlying<AssetKey> {
    pub base: AssetKey,
    pub quote: AssetKey,
}

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Side`] of a trade or position - Buy or Sell.
pub enum Side {
    #[serde(alias = "buy", alias = "BUY", alias = "b")]
    Buy,
    #[serde(alias = "sell", alias = "SELL", alias = "s")]
    Sell,
}

pub fn exchange_asset(exchange: ExchangeId, symbol: &str) -> ExchangeAsset<Asset> { /* ... */ }

pub fn asset(symbol: &str) -> Asset { /* ... */ }

pub fn instrument(
        exchange: ExchangeId,
        base: &str,
        quote: &str,
    ) -> Instrument<ExchangeId, Asset> { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Underlying {
    pub fn new<A>(base: A, quote: A) -> Self
        where
            A: Into<AssetKey>,
        { /* ... */ }
}

