// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// aggregate: barter_execution.rs
// crates: barter_execution

// ---- source: barter-execution/src/balance.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/balance.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize, Constructor,
)]
pub struct AssetBalance<AssetKey> {
    pub asset: AssetKey,
    pub balance: Balance,
    pub time_exchange: DateTime<Utc>,
}

#[derive(
    Debug,
    Copy,
    Clone,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Default,
    Deserialize,
    Serialize,
    Constructor,
)]
pub struct Balance {
    pub total: Decimal,
    pub free: Decimal,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Balance {
    pub fn used(&self) -> Decimal { /* ... */ }
}

// ---- source: barter-execution/src/client/mock/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/client/mock/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct MockExecutionConfig {
    pub mocked_exchange: ExchangeId,
    pub initial_state: UnindexedAccountSnapshot,
    pub latency_ms: u64,
    pub fees_percent: Decimal,
}

#[derive(Debug, Constructor)]
pub struct MockExecutionClientConfig<FnTime> {
    pub mocked_exchange: ExchangeId,
    pub clock: FnTime,
    pub request_tx: mpsc::UnboundedSender<MockExchangeRequest>,
    pub event_rx: broadcast::Receiver<UnindexedAccountEvent>,
}

#[derive(Debug, Constructor)]
pub struct MockExecution<FnTime> {
    pub mocked_exchange: ExchangeId,
    pub clock: FnTime,
    pub request_tx: mpsc::UnboundedSender<MockExchangeRequest>,
    pub event_rx: broadcast::Receiver<UnindexedAccountEvent>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MockExecution {
    pub fn time_request(&self) -> DateTime<Utc> { /* ... */ }
}

// ---- source: barter-execution/src/client/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/client/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub trait ExecutionClient
where
    Self: Clone,
{
    const EXCHANGE: ExchangeId;

    type Config: Clone;
    type AccountStream: Stream<Item = UnindexedAccountEvent>;

    fn new(config: Self::Config) -> Self;

    fn account_snapshot(
        &self,
        assets: &[AssetNameExchange],
        instruments: &[InstrumentNameExchange],
    ) -> impl Future<Output = Result<UnindexedAccountSnapshot, UnindexedClientError>> + Send;

    fn account_stream(
        &self,
        assets: &[AssetNameExchange],
        instruments: &[InstrumentNameExchange],
    ) -> impl Future<Output = Result<Self::AccountStream, UnindexedClientError>> + Send;

    fn cancel_order(
        &self,
        request: OrderRequestCancel<ExchangeId, &InstrumentNameExchange>,
    ) -> impl Future<Output = Option<UnindexedOrderResponseCancel>> + Send;

    fn cancel_orders<'a>(
        &self,
        requests: impl IntoIterator<Item = OrderRequestCancel<ExchangeId, &'a InstrumentNameExchange>>,
    ) -> impl Stream<Item = Option<UnindexedOrderResponseCancel>> { /* ... */ }

    fn open_order(
        &self,
        request: OrderRequestOpen<ExchangeId, &InstrumentNameExchange>,
    ) -> impl Future<
        Output = Option<
            Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
        >,
    > + Send;

    fn open_orders<'a>(
        &self,
        requests: impl IntoIterator<Item = OrderRequestOpen<ExchangeId, &'a InstrumentNameExchange>>,
    ) -> impl Stream<
        Item = Option<Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>>,
    > { /* ... */ }

    fn fetch_balances(
        &self,
        assets: &[AssetNameExchange],
    ) -> impl Future<Output = Result<Vec<AssetBalance<AssetNameExchange>>, UnindexedClientError>>;

    fn fetch_open_orders(
        &self,
        instruments: &[InstrumentNameExchange],
    ) -> impl Future<
        Output = Result<Vec<Order<ExchangeId, InstrumentNameExchange, Open>>, UnindexedClientError>,
    >;

    fn fetch_trades(
        &self,
        time_since: DateTime<Utc>,
    ) -> impl Future<Output = Result<Vec<Trade<QuoteAsset, InstrumentNameExchange>>, UnindexedClientError>>;
}

// ---- source: barter-execution/src/error.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/error.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Type alias for a [`ClientError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedClientError = ClientError<AssetNameExchange, InstrumentNameExchange>;

/// Type alias for a [`ApiError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedApiError = ApiError<AssetNameExchange, InstrumentNameExchange>;

/// Type alias for a [`OrderError`] that is keyed on [`AssetNameExchange`] and
/// [`InstrumentNameExchange`] (yet to be indexed).
pub type UnindexedOrderError = OrderError<AssetNameExchange, InstrumentNameExchange>;

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all errors produced by an [`ExecutionClient`](super::client::ExecutionClient).
pub enum ClientError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Connectivity based error.
    ///
    /// eg/ Timeout.
    #[error("Connectivity: {0}")]
    Connectivity(#[from] ConnectivityError),

    /// API based error.
    ///
    /// eg/ RateLimit.
    #[error("API: {0}")]
    Api(#[from] ApiError<AssetKey, InstrumentKey>),

    /// Failed to fetch an AccountSnapshot.
    #[error("failed to fetch AccountSnapshot: {0}")]
    AccountSnapshot(String),

    /// Failed to initialise an AccountStream.
    #[error("failed to init AccountStream: {0}")]
    AccountStream(String),
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all connectivity-centric errors.
/// 
/// Connectivity errors are generally intermittent / non-deterministic (eg/ Timeout).
pub enum ConnectivityError {
    /// Indicates an exchange is offline, likely due to maintenance.
    #[error("Exchange offline: {0}")]
    ExchangeOffline(ExchangeId),

    /// Indicates an ExecutionRequest timed out before a response was received.
    #[error("ExecutionRequest timed out")]
    Timeout,

    /// Represents a [`SocketError`] generated by an execution integration.
    #[error("{0}")]
    Socket(String),
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all API errors generated by an exchange.
/// 
/// These typically indicate a request is invalid for some reason (eg/ BalanceInsufficient).
pub enum ApiError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Provided asset identifier is invalid or not supported.
    ///
    /// For example:
    /// - The [`AssetNameExchange`] was an invalid format.
    #[error("asset {0} invalid: {1}")]
    AssetInvalid(AssetKey, String),

    /// Provided instrument identifier is invalid or not supported.
    ///
    /// For example:
    /// - The exchange does not have a market for an instrument.
    /// - The [`InstrumentNameExchange`] was an invalid format.
    #[error("instrument {0} invalid: {1}")]
    InstrumentInvalid(InstrumentKey, String),

    #[error("rate limit exceeded")]
    RateLimit,
    #[error("asset {0} balance insufficient: {1}")]
    BalanceInsufficient(AssetKey, String),
    #[error("order rejected: {0}")]
    OrderRejected(String),
    #[error("order already cancelled")]
    OrderAlreadyCancelled,
    #[error("order already fully filled")]
    OrderAlreadyFullyFilled,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents all errors that can be generated when cancelling or opening orders.
pub enum OrderError<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    /// Connectivity based error.
    ///
    /// eg/ Timeout.
    #[error("connectivity: {0}")]
    Connectivity(#[from] ConnectivityError),

    /// API based error.
    ///
    /// eg/ RateLimit.
    #[error("order rejected: {0}")]
    Rejected(#[from] ApiError<AssetKey, InstrumentKey>),
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
/// Represents errors related to exchange, asset and instrument identifier key lookups.
pub enum KeyError {
    /// Indicates an [`ExchangeId`] was encountered that was not indexed, so does not have a
    /// corresponding `ExchangeIndex`.
    #[error("ExchangeId: {0}")]
    ExchangeId(String),

    /// Indicates an [`AssetNameExchange`] was encountered that was not indexed, so does not have a
    /// corresponding [`AssetIndex`].
    #[error("AssetKey: {0}")]
    AssetKey(String),

    /// Indicates an [`InstrumentNameExchange`] was encountered that was no indexed, so does
    /// not have a corresponding [`InstrumentIndex`].
    #[error("InstrumentKey: {0}")]
    InstrumentKey(String),
}

// ---- source: barter-execution/src/exchange/mock/account.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/exchange/mock/account.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Constructor)]
pub struct AccountState {
    balances: FnvHashMap<AssetNameExchange, AssetBalance<AssetNameExchange>>,
    orders_open: FnvHashMap<ClientOrderId, Order<ExchangeId, InstrumentNameExchange, Open>>,
    orders_cancelled:
        FnvHashMap<ClientOrderId, Order<ExchangeId, InstrumentNameExchange, Cancelled>>,
    trades: Vec<Trade<QuoteAsset, InstrumentNameExchange>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AccountState {
    pub fn update_time_exchange(&mut self, time_exchange: DateTime<Utc>) { /* ... */ }
    pub fn balances(&self) -> impl Iterator<Item = &AssetBalance<AssetNameExchange>> + '_ { /* ... */ }
    pub fn orders_open(
            &self,
        ) -> impl Iterator<Item = &Order<ExchangeId, InstrumentNameExchange, Open>> + '_ { /* ... */ }
    pub fn orders_cancelled(
            &self,
        ) -> impl Iterator<Item = &Order<ExchangeId, InstrumentNameExchange, Cancelled>> + '_ { /* ... */ }
    pub fn trades(
            &self,
            time_since: DateTime<Utc>,
        ) -> impl Iterator<Item = &Trade<QuoteAsset, InstrumentNameExchange>> + '_ { /* ... */ }
    pub fn balance_mut(
            &mut self,
            asset: &AssetNameExchange,
        ) -> Option<&mut AssetBalance<AssetNameExchange>> { /* ... */ }
    pub fn ack_trade(&mut self, trade: Trade<QuoteAsset, InstrumentNameExchange>) { /* ... */ }
}

// ---- source: barter-execution/src/exchange/mock/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/exchange/mock/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
pub struct MockExchange {
    pub exchange: ExchangeId,
    pub latency_ms: u64,
    pub fees_percent: Decimal,
    pub request_rx: mpsc::UnboundedReceiver<MockExchangeRequest>,
    pub event_tx: broadcast::Sender<UnindexedAccountEvent>,
    pub instruments: FnvHashMap<InstrumentNameExchange, Instrument<ExchangeId, AssetNameExchange>>,
    pub account: AccountState,
    pub order_sequence: u64,
    pub time_exchange_latest: DateTime<Utc>,
}

#[derive(Debug)]
pub struct OpenOrderNotifications {
    pub balance: Snapshot<AssetBalance<AssetNameExchange>>,
    pub trade: Trade<QuoteAsset, InstrumentNameExchange>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MockExchange {
    pub fn new(
            config: MockExecutionConfig,
            request_rx: mpsc::UnboundedReceiver<MockExchangeRequest>,
            event_tx: broadcast::Sender<UnindexedAccountEvent>,
            instruments: FnvHashMap<InstrumentNameExchange, Instrument<ExchangeId, AssetNameExchange>>,
        ) -> Self { /* ... */ }
    pub async fn run(mut self) { /* ... */ }
    fn update_time_exchange(&mut self, time_request: DateTime<Utc>) { /* ... */ }
    pub fn time_exchange(&self) -> DateTime<Utc> { /* ... */ }
    pub fn account_snapshot(&self) -> UnindexedAccountSnapshot { /* ... */ }
    /// Sends the provided `Response` via the [`oneshot::Sender`] after waiting for the latency
    /// [`Duration`].
    /// 
    /// Used to simulate network latency between the exchange and client.
    fn respond_with_latency<Response>(
            &self,
            response_tx: oneshot::Sender<Response>,
            response: Response,
        ) where
            Response: Send + 'static,
        { /* ... */ }
    /// Sends the provided `OpenOrderNotifications` via the `MockExchanges`
    /// `broadcast::Sender<UnindexedAccountEvent>` after waiting for the latency
    /// [`Duration`].
    /// 
    /// Used to simulate network latency between the exchange and client.
    fn send_notifications_with_latency(&self, notifications: OpenOrderNotifications) { /* ... */ }
    pub fn account_stream(&self) -> BoxStream<'static, UnindexedAccountEvent> { /* ... */ }
    pub fn cancel_order(
            &mut self,
            _: OrderRequestCancel<ExchangeId, InstrumentNameExchange>,
        ) -> Order<ExchangeId, InstrumentNameExchange, Result<Cancelled, UnindexedOrderError>> { /* ... */ }
    pub fn open_order(
            &mut self,
            request: OrderRequestOpen<ExchangeId, InstrumentNameExchange>,
        ) -> (
            Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
            Option<OpenOrderNotifications>,
        ) { /* ... */ }
    pub fn validate_order_kind_supported(
            &self,
            order_kind: OrderKind,
        ) -> Result<(), UnindexedOrderError> { /* ... */ }
    pub fn find_instrument_data(
            &self,
            instrument: &InstrumentNameExchange,
        ) -> Result<&Instrument<ExchangeId, AssetNameExchange>, UnindexedApiError> { /* ... */ }
    fn order_id_sequence_fetch_add(&mut self) -> OrderId { /* ... */ }
    fn build_account_event<Kind>(&self, kind: Kind) -> UnindexedAccountEvent
        where
            Kind: Into<AccountEventKind<ExchangeId, AssetNameExchange, InstrumentNameExchange>>,
        { /* ... */ }
}

// ---- source: barter-execution/src/exchange/mock/request.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/exchange/mock/request.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
pub struct MockExchangeRequest {
    pub time_request: DateTime<Utc>,
    pub kind: MockExchangeRequestKind,
}

#[derive(Debug)]
pub enum MockExchangeRequestKind {
    FetchAccountSnapshot {
        response_tx: oneshot::Sender<UnindexedAccountSnapshot>,
    },
    FetchBalances {
        assets: Vec<AssetNameExchange>,
        response_tx: oneshot::Sender<Vec<AssetBalance<AssetNameExchange>>>,
    },
    FetchOrdersOpen {
        instruments: Vec<InstrumentNameExchange>,
        response_tx: oneshot::Sender<Vec<Order<ExchangeId, InstrumentNameExchange, Open>>>,
    },
    FetchTrades {
        response_tx: oneshot::Sender<Vec<Trade<QuoteAsset, InstrumentNameExchange>>>,
        time_since: DateTime<Utc>,
    },
    CancelOrder {
        response_tx: oneshot::Sender<UnindexedOrderResponseCancel>,
        request: OrderRequestCancel<ExchangeId, InstrumentNameExchange>,
    },
    OpenOrder {
        response_tx: oneshot::Sender<
            Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
        >,
        request: OrderRequestOpen<ExchangeId, InstrumentNameExchange>,
    },
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MockExchangeRequest {
    pub fn new(time_request: DateTime<Utc>, kind: MockExchangeRequestKind) -> Self { /* ... */ }
    pub fn fetch_account_snapshot(
            time_request: DateTime<Utc>,
            response_tx: oneshot::Sender<UnindexedAccountSnapshot>,
        ) -> Self { /* ... */ }
    pub fn fetch_balances(
            time_request: DateTime<Utc>,
            assets: Vec<AssetNameExchange>,
            response_tx: oneshot::Sender<Vec<AssetBalance<AssetNameExchange>>>,
        ) -> Self { /* ... */ }
    pub fn fetch_orders_open(
            time_request: DateTime<Utc>,
            instruments: Vec<InstrumentNameExchange>,
            response_tx: oneshot::Sender<Vec<Order<ExchangeId, InstrumentNameExchange, Open>>>,
        ) -> Self { /* ... */ }
    pub fn fetch_trades(
            time_request: DateTime<Utc>,
            response_tx: oneshot::Sender<Vec<Trade<QuoteAsset, InstrumentNameExchange>>>,
            time_since: DateTime<Utc>,
        ) -> Self { /* ... */ }
    pub fn cancel_order(
            time_request: DateTime<Utc>,
            response_tx: oneshot::Sender<UnindexedOrderResponseCancel>,
            request: OrderRequestCancel<ExchangeId, InstrumentNameExchange>,
        ) -> Self { /* ... */ }
    pub fn open_order(
            time_request: DateTime<Utc>,
            response_tx: oneshot::Sender<
                Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
            >,
            request: OrderRequestOpen<ExchangeId, InstrumentNameExchange>,
        ) -> Self { /* ... */ }
}

// ---- source: barter-execution/src/indexer.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/indexer.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub type IndexedAccountStream<St> = IndexedStream<AccountEventIndexer, St>;

#[derive(Debug, Clone, Constructor)]
pub struct AccountEventIndexer {
    pub map: Arc<ExecutionInstrumentMap>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AccountEventIndexer {
    pub fn account_event(&self, event: UnindexedAccountEvent) -> Result<AccountEvent, IndexError> { /* ... */ }
    pub fn snapshot(
            &self,
            snapshot: UnindexedAccountSnapshot,
        ) -> Result<AccountSnapshot, IndexError> { /* ... */ }
    pub fn asset_balance(
            &self,
            balance: AssetBalance<AssetNameExchange>,
        ) -> Result<AssetBalance<AssetIndex>, IndexError> { /* ... */ }
    pub fn order_snapshot(
            &self,
            order: UnindexedOrderSnapshot,
        ) -> Result<OrderSnapshot, IndexError> { /* ... */ }
    pub fn order_response_cancel(
            &self,
            response: OrderResponseCancel<ExchangeId, AssetNameExchange, InstrumentNameExchange>,
        ) -> Result<OrderResponseCancel, IndexError> { /* ... */ }
    pub fn order_key(&self, key: UnindexedOrderKey) -> Result<OrderKey, IndexError> { /* ... */ }
    pub fn api_error(&self, error: UnindexedApiError) -> Result<ApiError, IndexError> { /* ... */ }
    pub fn order_request<Kind>(
            &self,
            order: &OrderEvent<Kind, ExchangeIndex, InstrumentIndex>,
        ) -> Result<OrderEvent<Kind, ExchangeId, &InstrumentNameExchange>, KeyError>
        where
            Kind: Clone,
        { /* ... */ }
    pub fn order_error(&self, error: UnindexedOrderError) -> Result<OrderError, IndexError> { /* ... */ }
    pub fn client_error(&self, error: UnindexedClientError) -> Result<ClientError, IndexError> { /* ... */ }
    pub fn trade(
            &self,
            trade: Trade<QuoteAsset, InstrumentNameExchange>,
        ) -> Result<Trade<QuoteAsset, InstrumentIndex>, IndexError> { /* ... */ }
}

// ---- source: barter-execution/src/lib.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/lib.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convenient type alias for an [`AccountEvent`] keyed with [`ExchangeId`],
/// [`AssetNameExchange`], and [`InstrumentNameExchange`].
pub type UnindexedAccountEvent =
    AccountEvent<ExchangeId, AssetNameExchange, InstrumentNameExchange>;

/// Convenient type alias for an [`AccountSnapshot`] keyed with [`ExchangeId`],
/// [`AssetNameExchange`], and [`InstrumentNameExchange`].
pub type UnindexedAccountSnapshot =
    AccountSnapshot<ExchangeId, AssetNameExchange, InstrumentNameExchange>;

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct AccountEvent<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> {
    pub exchange: ExchangeKey,
    pub kind: AccountEventKind<ExchangeKey, AssetKey, InstrumentKey>,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize, From)]
pub enum AccountEventKind<ExchangeKey, AssetKey, InstrumentKey> {
    /// Full [`AccountSnapshot`] - replaces all existing state.
    Snapshot(AccountSnapshot<ExchangeKey, AssetKey, InstrumentKey>),

    /// Single [`AssetBalance`] snapshot - replaces existing balance state.
    BalanceSnapshot(Snapshot<AssetBalance<AssetKey>>),

    /// Single [`Order`] snapshot - used to upsert existing order state if it's more recent.
    ///
    /// This variant covers general order updates, and open order responses.
    OrderSnapshot(Snapshot<Order<ExchangeKey, InstrumentKey, OrderState<AssetKey, InstrumentKey>>>),

    /// Response to an [`OrderRequestCancel<ExchangeKey, InstrumentKey>`](order::request::OrderRequestOpen).
    OrderCancelled(OrderResponseCancel<ExchangeKey, AssetKey, InstrumentKey>),

    /// [`Order<ExchangeKey, InstrumentKey, Open>`] partial or full-fill.
    Trade(Trade<QuoteAsset, InstrumentKey>),
}

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize, Constructor,
)]
pub struct AccountSnapshot<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> {
    pub exchange: ExchangeKey,
    pub balances: Vec<AssetBalance<AssetKey>>,
    pub instruments: Vec<InstrumentAccountSnapshot<ExchangeKey, AssetKey, InstrumentKey>>,
}

#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize, Constructor,
)]
pub struct InstrumentAccountSnapshot<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> {
    pub instrument: InstrumentKey,
    #[serde(default = "Vec::new")]
    pub orders: Vec<OrderSnapshot<ExchangeKey, AssetKey, InstrumentKey>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AccountSnapshot {
    pub fn time_most_recent(&self) -> Option<DateTime<Utc>> { /* ... */ }
    pub fn assets(&self) -> impl Iterator<Item = &AssetKey> { /* ... */ }
    pub fn instruments(&self) -> impl Iterator<Item = &InstrumentKey> { /* ... */ }
}

impl AccountEvent {
    pub fn new<K>(exchange: ExchangeKey, kind: K) -> Self
        where
            K: Into<AccountEventKind<ExchangeKey, AssetKey, InstrumentKey>>,
        { /* ... */ }
    pub fn snapshot(self) -> Option<AccountSnapshot<ExchangeKey, AssetKey, InstrumentKey>> { /* ... */ }
}

// ---- source: barter-execution/src/map.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/map.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq)]
/// Indexed instrument map used to associate the internal Barter representation of instruments and
/// assets with the [`ExecutionClient`](super::client::ExecutionClient) representation.
/// 
/// Similarly, when the execution manager received an [`AccountEvent`](super::AccountEvent)
/// from the execution API, it needs to determine the internal representation of the associated
/// assets and instruments.
/// 
/// eg/ `InstrumentNameExchange("XBT-USDT")` <--> `InstrumentIndex(1)` <br>
/// eg/ `AssetNameExchange("XBT")` <--> `AssetIndex(1)`
pub struct ExecutionInstrumentMap {
    /// The exchange associated with this execution map.
    pub exchange: Keyed<ExchangeIndex, ExchangeId>,
    /// Collection of assets available by the engine with their
    /// exchange-specific representations. This holds all indexed assets.
    pub assets: FnvIndexSet<ExchangeAsset<Asset>>,
    /// Collection of instruments available by the engine. This holds all
    /// indexed instruments.
    pub instruments: FnvIndexSet<Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>,
    /// Map from exchange-specific asset names to internal asset indices for
    /// fast lookups.
    pub asset_names: FnvHashMap<AssetNameExchange, AssetIndex>,
    /// Map from exchange-specific instrument names to internal instrument
    /// indices for fast lookups.
    pub instrument_names: FnvHashMap<InstrumentNameExchange, InstrumentIndex>,
}

pub fn generate_execution_instrument_map(
    instruments: &IndexedInstruments,
    exchange: ExchangeId,
) -> Result<ExecutionInstrumentMap, IndexError> { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ExecutionInstrumentMap {
    /// Construct a new [`Self`] using the provided indexed assets and instruments.
    pub fn new(
            exchange: Keyed<ExchangeIndex, ExchangeId>,
            instruments: &IndexedInstruments,
        ) -> Self { /* ... */ }
    pub fn exchange_assets(&self) -> impl Iterator<Item = &AssetNameExchange> { /* ... */ }
    pub fn exchange_instruments(&self) -> impl Iterator<Item = &InstrumentNameExchange> { /* ... */ }
    pub fn find_exchange_id(&self, exchange: ExchangeIndex) -> Result<ExchangeId, KeyError> { /* ... */ }
    pub fn find_exchange_index(&self, exchange: ExchangeId) -> Result<ExchangeIndex, IndexError> { /* ... */ }
    pub fn find_asset_name_exchange(
            &self,
            asset: AssetIndex,
        ) -> Result<&AssetNameExchange, KeyError> { /* ... */ }
    pub fn find_asset_index(&self, asset: &AssetNameExchange) -> Result<AssetIndex, IndexError> { /* ... */ }
    pub fn find_instrument_name_exchange(
            &self,
            instrument: InstrumentIndex,
        ) -> Result<&InstrumentNameExchange, KeyError> { /* ... */ }
    pub fn find_instrument_index(
            &self,
            instrument: &InstrumentNameExchange,
        ) -> Result<InstrumentIndex, IndexError> { /* ... */ }
}

// ---- source: barter-execution/src/order/id.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/order/id.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct ClientOrderId<T = SmolStr>(pub T);

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct OrderId<T = SmolStr>(pub T);

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display, From,
)]
pub struct StrategyId(pub SmolStr);

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl ClientOrderId {
    /// Construct a `ClientOrderId` from the specified string.
    /// 
    /// Use [`Self::random`] to generate a random stack-allocated `ClientOrderId`.
    pub fn new<S: Into<SmolStr>>(id: S) -> Self { /* ... */ }
    /// Construct a stack-allocated `ClientOrderId` backed by a 23 byte [`SmolStr`].
    pub fn random() -> Self { /* ... */ }
}

impl StrategyId {
    pub fn new<S: AsRef<str>>(id: S) -> Self { /* ... */ }
    pub fn unknown() -> Self { /* ... */ }
}

impl OrderId {
    pub fn new<S: AsRef<str>>(id: S) -> Self { /* ... */ }
}

// ---- source: barter-execution/src/order/mod.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/order/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convenient type alias for an [`Order`] keyed with [`ExchangeId`] and [`InstrumentNameExchange`].
pub type UnindexedOrder = Order<ExchangeId, InstrumentNameExchange, UnindexedOrderState>;

/// Convenient type alias for an [`OrderKey`] keyed with [`ExchangeId`]
/// and [`InstrumentNameExchange`].
pub type UnindexedOrderKey = OrderKey<ExchangeId, InstrumentNameExchange>;

/// Convenient type alias for an [`OrderSnapshot`] keyed with [`ExchangeId`], [`AssetNameExchange`],
/// and [`InstrumentNameExchange`].
pub type UnindexedOrderSnapshot = Order<
    ExchangeId,
    InstrumentNameExchange,
    OrderState<AssetNameExchange, InstrumentNameExchange>,
>;

/// Convenient type alias for an [`Order`] [`OrderState`] snapshot.
pub type OrderSnapshot<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> = Order<ExchangeKey, InstrumentKey, OrderState<AssetKey, InstrumentKey>>;

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct OrderEvent<State, ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex> {
    pub key: OrderKey<ExchangeKey, InstrumentKey>,
    pub state: State,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct OrderKey<ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex> {
    pub exchange: ExchangeKey,
    pub instrument: InstrumentKey,
    pub strategy: StrategyId,
    pub cid: ClientOrderId,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct Order<ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex, State = OrderState> {
    pub key: OrderKey<ExchangeKey, InstrumentKey>,
    pub side: Side,
    pub price: Decimal,
    pub quantity: Decimal,
    pub kind: OrderKind,
    pub time_in_force: TimeInForce,
    pub state: State,
}

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display,
)]
pub enum OrderKind {
    Market,
    Limit,
}

#[derive(
    Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Display,
)]
pub enum TimeInForce {
    GoodUntilCancelled { post_only: bool },
    GoodUntilEndOfDay,
    FillOrKill,
    ImmediateOrCancel,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Order {
    pub fn to_active(&self) -> Option<Order<ExchangeKey, InstrumentKey, ActiveOrderState>>
        where
            ExchangeKey: Clone,
            InstrumentKey: Clone,
        { /* ... */ }
    pub fn to_inactive(
            &self,
        ) -> Option<Order<ExchangeKey, InstrumentKey, InactiveOrderState<AssetKey, InstrumentKey>>>
        where
            ExchangeKey: Clone,
            AssetKey: Clone,
            InstrumentKey: Clone,
        { /* ... */ }
    pub fn to_request_cancel(&self) -> Option<OrderRequestCancel<ExchangeKey, InstrumentKey>> { /* ... */ }
}

// ---- source: barter-execution/src/order/request.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/order/request.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

pub type OrderRequestOpen<ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex> =
    OrderEvent<RequestOpen, ExchangeKey, InstrumentKey>;

pub type OrderRequestCancel<ExchangeKey = ExchangeIndex, InstrumentKey = InstrumentIndex> =
    OrderEvent<RequestCancel, ExchangeKey, InstrumentKey>;

pub type OrderResponseCancel<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> = OrderEvent<Result<Cancelled, OrderError<AssetKey, InstrumentKey>>, ExchangeKey, InstrumentKey>;

pub type UnindexedOrderResponseCancel =
    OrderResponseCancel<ExchangeId, AssetNameExchange, InstrumentNameExchange>;

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct RequestOpen {
    pub side: Side,
    pub price: Decimal,
    pub quantity: Decimal,
    pub kind: OrderKind,
    pub time_in_force: TimeInForce,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Default, Deserialize, Serialize, Constructor,
)]
pub struct RequestCancel {
    pub id: Option<OrderId>,
}

// ---- source: barter-execution/src/order/state.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/order/state.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convenient type alias for an [`OrderState`] keyed with [`AssetNameExchange`]
/// and [`InstrumentNameExchange`].
pub type UnindexedOrderState = OrderState<AssetNameExchange, InstrumentNameExchange>;

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, From)]
pub enum OrderState<AssetKey = AssetIndex, InstrumentKey = InstrumentIndex> {
    Active(ActiveOrderState),
    Inactive(InactiveOrderState<AssetKey, InstrumentKey>),
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, From)]
pub enum ActiveOrderState {
    OpenInFlight(OpenInFlight),
    Open(Open),
    CancelInFlight(CancelInFlight),
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub struct OpenInFlight;

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct Open {
    pub id: OrderId,
    pub time_exchange: DateTime<Utc>,
    pub filled_quantity: Decimal,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Default, Deserialize, Serialize, Constructor,
)]
pub struct CancelInFlight {
    pub order: Option<Open>,
}

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, From)]
pub enum InactiveOrderState<AssetKey, InstrumentKey> {
    Cancelled(Cancelled),
    FullyFilled,
    OpenFailed(OrderError<AssetKey, InstrumentKey>),
    Expired,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct Cancelled {
    pub id: OrderId,
    pub time_exchange: DateTime<Utc>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Open {
    pub fn quantity_remaining(&self, initial_quantity: Decimal) -> Decimal { /* ... */ }
}

impl ActiveOrderState {
    pub fn open_meta(&self) -> Option<&Open> { /* ... */ }
}

impl OrderState {
    pub fn active<S>(state: S) -> Self
        where
            S: Into<ActiveOrderState>,
        { /* ... */ }
    pub fn inactive<S>(state: S) -> Self
        where
            S: Into<InactiveOrderState<AssetKey, InstrumentKey>>,
        { /* ... */ }
    pub fn fully_filled() -> Self { /* ... */ }
    pub fn expired() -> Self { /* ... */ }
    pub fn time_exchange(&self) -> Option<DateTime<Utc>> { /* ... */ }
}

// ---- source: barter-execution/src/trade.rs ----
// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, From)]
pub struct TradeId<T = SmolStr>(pub T);

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct Trade<AssetKey, InstrumentKey> {
    pub id: TradeId,
    pub order_id: OrderId,
    pub instrument: InstrumentKey,
    pub strategy: StrategyId,
    pub time_exchange: DateTime<Utc>,
    pub side: Side,
    pub price: Decimal,
    pub quantity: Decimal,
    pub fees: AssetFees<AssetKey>,
}

#[derive(
    Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Constructor,
)]
pub struct AssetFees<AssetKey> {
    pub asset: AssetKey,
    pub fees: Decimal,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl Trade {
    pub fn value_quote(&self) -> Decimal { /* ... */ }
}

impl AssetFees {
    pub fn quote_fees(fees: Decimal) -> Self { /* ... */ }
}

impl TradeId {
    pub fn new<S: AsRef<str>>(id: S) -> Self { /* ... */ }
}

