// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_integration
// source: barter-integration/src/collection/one_or_many.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize)]
pub enum OneOrMany<T> {
    One(T),
    Many(Vec<T>),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl OneOrMany {
    pub fn map<U, F>(self, f: F) -> OneOrMany<U>
        where
            F: Fn(T) -> U,
        { /* ... */ }
    pub fn extend<Iter>(self, other: Iter) -> Self
        where
            Iter: IntoIterator<Item = T>,
        { /* ... */ }
    pub fn contains(&self, item: &T) -> bool
        where
            T: PartialEq,
        { /* ... */ }
    #[allow(clippy::len_without_is_empty)]
    pub fn len(&self) -> usize { /* ... */ }
    pub fn is_one(&self) -> bool { /* ... */ }
    pub fn is_many(&self) -> bool { /* ... */ }
    pub fn into_vec(self) -> Vec<T> { /* ... */ }
    pub fn iter(&self) -> std::slice::Iter<'_, T> { /* ... */ }
}

