// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/books/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, PartialEq, Eq, Debug, Default, Deserialize, Serialize)]
/// Normalised Barter [`OrderBook`] snapshot.
pub struct OrderBook {
    sequence: u64,
    time_engine: Option<DateTime<Utc>>,
    bids: OrderBookSide<Bids>,
    asks: OrderBookSide<Asks>,
}

#[derive(Clone, PartialEq, Eq, Debug, Deserialize, Serialize)]
/// Normalised Barter [`Level`]s for one `Side` of the [`OrderBook`].
pub struct OrderBookSide<Side> {
    #[serde(skip_serializing)]
    pub side: Side,
    levels: Vec<Level>,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Display)]
/// Unit type to tag an [`OrderBookSide`] as the bid Side (ie/ buyers) of an [`OrderBook`].
pub struct Bids;

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Display)]
/// Unit type to tag an [`OrderBookSide`] as the ask Side (ie/ sellers) of an [`OrderBook`].
pub struct Asks;

#[derive(Debug, Copy, Clone, PartialEq, Ord, PartialOrd, Hash, Default, Deserialize, Serialize)]
/// Normalised Barter OrderBook [`Level`].
pub struct Level {
    pub price: Decimal,
    pub amount: Decimal,
}

/// Calculate the mid-price by taking the average of the best bid and ask prices.
/// 
/// See Docs: <https://www.quantstart.com/articles/high-frequency-trading-ii-limit-order-book>
pub fn mid_price(best_bid_price: Decimal, best_ask_price: Decimal) -> Decimal { /* ... */ }

/// Calculate the volume weighted mid-price (micro-price), weighing the best bid and ask prices
/// with their associated amount.
/// 
/// See Docs: <https://www.quantstart.com/articles/high-frequency-trading-ii-limit-order-book>
pub fn volume_weighted_mid_price(best_bid: Level, best_ask: Level) -> Decimal { /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl OrderBook {
    /// Construct a new sorted [`OrderBook`].
    /// 
    /// Note that the passed bid and asks levels do not need to be pre-sorted.
    pub fn new<IterBids, IterAsks, L>(
            sequence: u64,
            time_engine: Option<DateTime<Utc>>,
            bids: IterBids,
            asks: IterAsks,
        ) -> Self
        where
            IterBids: IntoIterator<Item = L>,
            IterAsks: IntoIterator<Item = L>,
            L: Into<Level>,
        { /* ... */ }
    /// Current `u64` sequence number associated with the [`OrderBook`].
    pub fn sequence(&self) -> u64 { /* ... */ }
    /// Current engine time associated with the [`OrderBook`].
    pub fn time_engine(&self) -> Option<DateTime<Utc>> { /* ... */ }
    /// Generate a sorted [`OrderBook`] snapshot with a maximum depth.
    pub fn snapshot(&self, depth: usize) -> Self { /* ... */ }
    /// Update the local [`OrderBook`] from a new [`OrderBookEvent`].
    pub fn update(&mut self, event: &OrderBookEvent) { /* ... */ }
    /// Update the local [`OrderBook`] by upserting the levels in an [`OrderBookSide`].
    fn upsert_bids(&mut self, update: &OrderBookSide<Bids>) { /* ... */ }
    /// Update the local [`OrderBook`] by upserting the levels in an [`OrderBookSide`].
    fn upsert_asks(&mut self, update: &OrderBookSide<Asks>) { /* ... */ }
    /// Return a reference to this [`OrderBook`]s bids.
    pub fn bids(&self) -> &OrderBookSide<Bids> { /* ... */ }
    /// Return a reference to this [`OrderBook`]s asks.
    pub fn asks(&self) -> &OrderBookSide<Asks> { /* ... */ }
    /// Calculate the mid-price by taking the average of the best bid and ask prices.
    /// 
    /// See Docs: <https://www.quantstart.com/articles/high-frequency-trading-ii-limit-order-book>
    pub fn mid_price(&self) -> Option<Decimal> { /* ... */ }
    /// Calculate the volume weighted mid-price (micro-price), weighing the best bid and ask prices
    /// with their associated amount.
    /// 
    /// See Docs: <https://www.quantstart.com/articles/high-frequency-trading-ii-limit-order-book>
    pub fn volume_weighed_mid_price(&self) -> Option<Decimal> { /* ... */ }
}

impl Level {
    pub fn new<T>(price: T, amount: T) -> Self
        where
            T: Into<Decimal>,
        { /* ... */ }
}

impl OrderBookSide {
    /// Construct a new [`OrderBookSide<Bids>`] from the provided [`Level`]s.
    pub fn bids<Iter, L>(levels: Iter) -> Self
        where
            Iter: IntoIterator<Item = L>,
            L: Into<Level>,
        { /* ... */ }
    /// Upsert bid [`Level`]s into this [`OrderBookSide<Bids>`].
    pub fn upsert<L>(&mut self, levels: &[L])
        where
            L: Into<Level> + Copy,
        { /* ... */ }
    /// Construct a new [`OrderBookSide<Asks>`] from the provided [`Level`]s.
    pub fn asks<Iter, L>(levels: Iter) -> Self
        where
            Iter: IntoIterator<Item = L>,
            L: Into<Level>,
        { /* ... */ }
    /// Upsert ask [`Level`]s into this [`OrderBookSide<Asks>`].
    pub fn upsert<L>(&mut self, levels: &[L])
        where
            L: Into<Level> + Copy,
        { /* ... */ }
    /// Get best [`Level`] on the [`OrderBookSide`].
    pub fn best(&self) -> Option<&Level> { /* ... */ }
    /// Return a reference to the [`OrderBookSide`] levels.
    pub fn levels(&self) -> &[Level] { /* ... */ }
    /// Upsert a single [`Level`] into this [`OrderBookSide`].
    /// 
    /// ### Upsert Scenarios
    /// #### 1 Level Already Exists
    /// 1a) New value is 0, remove the level
    /// 1b) New value is > 0, replace the level
    /// 
    /// #### 2 Level Does Not Exist
    /// 2a) New value is 0, log warn and continue
    /// 2b) New value is > 0, insert new level
    pub fn upsert_single<FnOrd>(&mut self, new_level: Level, fn_ord: FnOrd)
        where
            FnOrd: Fn(&Level) -> Ordering,
        { /* ... */ }
}

