// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/okx/book/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Terse type alias for an OKX `books5` WebSocket message (legacy stateless).
pub type OkxOrderBookMessage = OkxMessage<OkxOrderBookSnapshot>;

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// OKX `books` channel WebSocket message with action field.
/// 
/// Used for stateful channels (`books`, `books50-l2-tbt`) that send
/// snapshot + incremental updates with sequence validation.
/// 
/// ### Raw Payload Example
/// ```json
/// {
/// "arg": {"channel": "books", "instId": "BTC-USDT"},
/// "action": "snapshot",
/// "data": [{
/// "asks": [["67756","0.0441","0","3"]],
/// "bids": [["67755.9","2.4429","0","27"]],
/// "ts": "1774607207558",
/// "checksum": -1839238657,
/// "seqId": 74318423271,
/// "prevSeqId": -1
/// }]
/// }
/// ```
pub struct OkxBookMessage {
    #[serde(
        rename = "arg",
        deserialize_with = "super::trade::de_okx_message_arg_as_subscription_id"
    )]
    pub subscription_id: SubscriptionId,
    pub action: OkxBookAction,
    pub data: Vec<OkxOrderBookUpdate>,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
/// OKX book channel action type.
pub enum OkxBookAction {
    Snapshot,
    Update,
}

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// OKX orderbook update/snapshot data payload (used by `books` channel).
/// 
/// Contains `prevSeqId` for gap detection (absent in `books5`).
pub struct OkxOrderBookUpdate {
    pub asks: Vec<OkxLevel>,
    pub bids: Vec<OkxLevel>,
    #[serde(
        rename = "ts",
        deserialize_with = "barter_integration::de::de_str_u64_epoch_ms_as_datetime_utc"
    )]
    pub time: chrono::DateTime<Utc>,
    #[serde(rename = "seqId", default)]
    pub seq_id: u64,
    #[serde(rename = "prevSeqId", default)]
    pub prev_seq_id: i64,
    #[serde(default)]
    pub checksum: i32,
}

#[derive(Clone, PartialEq, Debug, Deserialize, Serialize)]
/// A single `books5` snapshot payload from OKX (legacy).
/// 
/// ### Raw Payload Example
/// ```json
/// {
/// "asks": [["41006.8", "0.60038921", "0", "1"]],
/// "bids": [["41006.3", "0.30178218", "0", "2"]],
/// "ts": "1630048897897",
/// "seqId": 1234567890
/// }
/// ```
pub struct OkxOrderBookSnapshot {
    pub asks: Vec<OkxLevel>,
    pub bids: Vec<OkxLevel>,
    #[serde(
        rename = "ts",
        deserialize_with = "barter_integration::de::de_str_u64_epoch_ms_as_datetime_utc"
    )]
    pub time: chrono::DateTime<Utc>,
    #[serde(rename = "seqId", default)]
    pub seq_id: u64,
}

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Serialize)]
/// OKX orderbook level: `["price", "size", "deprecated", "numOrders"]`.
/// 
/// OKX sends 4-element arrays but we only need price and size.
pub struct OkxLevel {
    pub price: Decimal,
    pub amount: Decimal,
}

