// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitfinex/candle.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Serialize)]
/// [`Bitfinex`](super::Bitfinex) candle data.
/// 
/// ### Raw Payload Examples
/// Format: \[MTS, OPEN, CLOSE, HIGH, LOW, VOLUME\]
/// 
/// Note: CLOSE comes before HIGH/LOW (different from standard OHLCV).
/// 
/// See docs: <https://docs.bitfinex.com/reference/ws-public-candles>
pub struct BitfinexCandle {
    pub time: DateTime<Utc>,
    pub open: f64,
    pub close: f64,
    pub high: f64,
    pub low: f64,
    pub volume: f64,
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Serialize)]
#[non_exhaustive]
/// [`Bitfinex`](super::Bitfinex) candle message payload variants.
/// 
/// See docs: <https://docs.bitfinex.com/reference/ws-public-candles>
pub enum BitfinexCandlePayload {
    Heartbeat,
    Candle(BitfinexCandle),
    Snapshot(Vec<BitfinexCandle>),
}

#[derive(Clone, PartialEq, PartialOrd, Debug, Serialize)]
/// [`Bitfinex`](super::Bitfinex) candle WebSocket message.
/// 
/// Format: \[CHANNEL_ID, \<payload\>\]
/// where payload is `"hb"`, `[candle_data]`, or `[[candle_data], ...]`.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.bitfinex.com/reference/ws-public-candles>
/// 
/// #### Heartbeat
/// ```json
/// [42, "hb"]
/// ```
/// 
/// #### Single Candle Update
/// ```json
/// [42, [1672502400000, 16850, 16855.5, 16860, 16845, 12.345]]
/// ```
/// 
/// #### Snapshot
/// ```json
/// [42, [[1672502400000, 16850, 16855.5, 16860, 16845, 12.345], [...]]]
/// ```
pub struct BitfinexCandleMessage {
    pub channel_id: u32,
    pub payload: BitfinexCandlePayload,
}

