// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitfinex/message.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Serialize)]
/// [`Bitfinex`](super::Bitfinex) message received over
/// [`WebSocket`](barter_integration::protocol::websocket::WebSocket) relating to an active
/// [`Subscription`](crate::Subscription).
/// 
/// The message is associated with the original [`Subscription`](crate::Subscription) using the
/// `channel_id` field as the [`SubscriptionId`].
/// 
/// ### Raw Payload Examples
/// #### Heartbeat
/// See docs: <https://docs.bitfinex.com/docs/ws-general#heartbeating>
/// ```json
/// [420191,"hb"]
/// ```
/// 
/// #### Side::Buy Trade
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
/// ```json
/// [420191,"te",[1225484398,1665452200022,0.08980641,19027.02807752]]
/// ```
/// 
/// #### Side::Sell Trade
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
/// ```json
/// [420191,"te",[1225484398,1665452200022,-0.08980641,19027.02807752]]
/// ```
pub struct BitfinexMessage {
    pub channel_id: u32,
    pub payload: BitfinexPayload,
}

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Serialize)]
#[non_exhaustive]
/// [`Bitfinex`](super::Bitfinex) market data variants associated with an
/// active [`Subscription`](crate::Subscription).
/// 
/// See [`BitfinexMessage`] for full raw payload examples.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
pub enum BitfinexPayload {
    Heartbeat,
    Trade(BitfinexTrade),
}

