// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitfinex/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

/// Convert a normalised [`Interval`] to the Bitfinex API interval string.
/// 
/// Bitfinex supports: 1m, 5m, 15m, 30m, 1h, 3h, 6h, 12h, 1D, 1W, 14D, 1M.
pub(crate) fn bitfinex_interval(interval: Interval) -> Result<&'static str, DataError> { /* ... */ }

/// [`Bitfinex`] server base url.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
pub const BASE_URL_BITFINEX: &str = todo!();

#[derive(
    Copy,
    Clone,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Debug,
    Default,
    Display,
    DeExchange,
    SerExchange,
)]
/// [`Bitfinex`] exchange.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
pub struct Bitfinex;

