// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitfinex/subscription.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
#[serde(tag = "event", rename_all = "lowercase")]
#[non_exhaustive]
/// [`Bitfinex`](super::Bitfinex) platform event detailing the variants expected to be received
/// while connecting and subscribing.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
/// #### Platform Status Online
/// ``` json
/// {
/// "event": "info",
/// "version": VERSION,
/// "platform": {
/// "status": 1
/// }
/// }
/// ```
/// 
/// #### Subscription Trades Success
/// ``` json
/// {
/// event: "subscribed",
/// channel: "trades",
/// chanId: CHANNEL_ID,
/// symbol: "tBTCUSD"
/// pair: "BTCUSD"
/// }
/// ```
/// 
/// #### Subscription Failure
/// ``` json
/// {
/// "event": "error",
/// "msg": ERROR_MSG,
/// "code": ERROR_CODE
/// }
pub enum BitfinexPlatformEvent {
    #[serde(rename = "info")]
    PlatformStatus(BitfinexPlatformStatus),
    Subscribed(BitfinexSubResponse),
    Error(BitfinexError),
}

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Bitfinex`](super::Bitfinex) platform status message containing the server we are connecting
/// to, the version of the API, and if it is in maintenance mode.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.bitfinex.com/docs/ws-general#info-messages>
/// #### Platform Status Operative
/// ``` json
/// {
/// "event": "info",
/// "version": 2,
/// "serverId": ""
/// "platform": {
/// "status": 1
/// }
/// }
/// ```
/// 
/// #### Platform Status In Maintenance
/// ``` json
/// {
/// "event": "info",
/// "version": 2,
/// "serverId": ""
/// "platform": {
/// "status": 0
/// }
/// }
/// ```
pub struct BitfinexPlatformStatus {
    #[serde(rename = "version")]
    api_version: u8,
    #[serde(rename = "serverId")]
    server_id: String,
    #[serde(rename = "platform")]
    status: Status,
}

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Serialize)]
#[non_exhaustive]
/// [`Bitfinex`](super::Bitfinex) platform [`Status`] indicating if the API is in maintenance mode.
/// 
/// See [`BitfinexPlatformStatus`] for full raw payload examples.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general#info-messages>
pub enum Status {
    Maintenance,
    Operative,
}

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Bitfinex`](super::Bitfinex) subscription success response variants for each channel.
/// 
/// ### Raw Payload Examples
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
/// #### Subscription Trades Success
/// ``` json
/// {
/// event: "subscribed",
/// channel: "trades",
/// chanId: CHANNEL_ID,
/// symbol: "tBTCUSD"
/// pair: "BTCUSD"
/// }
/// ```
/// 
/// #### Subscription Failure
/// ``` json
/// {
/// "event": "error",
/// "msg": ERROR_MSG,
/// "code": ERROR_CODE
/// }
pub struct BitfinexSubResponse {
    pub channel: String,
    #[serde(alias = "symbol", alias = "key")]
    pub market: String,
    #[serde(rename = "chanId")]
    pub channel_id: BitfinexChannelId,
}

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Bitfinex`](super::Bitfinex) channel identifier that is used to identify the subscription
/// associated with incoming events. See the module level "SubscriptionId" documentation notes
/// for more details.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general#subscribe-to-channels>
pub struct BitfinexChannelId(pub u32);

#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Deserialize, Serialize)]
/// [`Bitfinex`](super::Bitfinex) error message that is received if a [`BitfinexSubResponse`]
/// indicates a WebSocket subscription failure.
/// 
/// ### Subscription Error Codes:
/// 10300: Generic failure
/// 10301: Already subscribed
/// 10302: Unknown channel
/// 
/// See [`BitfinexPlatformStatus`] for full raw payload examples.
/// 
/// See docs: <https://docs.bitfinex.com/docs/ws-general>
pub struct BitfinexError {
    msg: String,
    code: u32,
}

