// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_data
// source: barter-data/src/exchange/bitfinex/trade.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Serialize)]
/// [`Bitfinex`](super::Bitfinex) real-time trade message.
/// 
/// ### Raw Payload Examples
/// Format: \[ID, TIME, AMOUNT, PRICE\], <br> where +/- of amount indicates Side
/// 
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
/// 
/// #### Side::Buy Trade
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
/// ```json
/// [420191,"te",[1225484398,1665452200022,0.08980641,19027.02807752]]
/// ```
/// 
/// #### Side::Sell Trade
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
/// ```json
/// [420191,"te",[1225484398,1665452200022,-0.08980641,19027.02807752]]
/// ```
/// 
/// ## Notes:
/// - [`Bitfinex`](super::Bitfinex) trades subscriptions results in receiving tag="te" & tag="tu"
/// trades, both of which are identical.
/// - "te" trades arrive marginally faster.
/// - Therefore, tag="tu" trades are filtered out and considered only as additional Heartbeats.
/// 
/// See docs: <https://docs.bitfinex.com/reference/ws-public-trades>
pub struct BitfinexTrade {
    pub id: u64,
    pub time: DateTime<Utc>,
    pub side: Side,
    pub price: f64,
    pub amount: f64,
}

