// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/exchange/mock/account.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Constructor)]
pub struct AccountState {
    balances: FnvHashMap<AssetNameExchange, AssetBalance<AssetNameExchange>>,
    orders_open: FnvHashMap<ClientOrderId, Order<ExchangeId, InstrumentNameExchange, Open>>,
    orders_cancelled:
        FnvHashMap<ClientOrderId, Order<ExchangeId, InstrumentNameExchange, Cancelled>>,
    trades: Vec<Trade<QuoteAsset, InstrumentNameExchange>>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl AccountState {
    pub fn update_time_exchange(&mut self, time_exchange: DateTime<Utc>) { /* ... */ }
    pub fn balances(&self) -> impl Iterator<Item = &AssetBalance<AssetNameExchange>> + '_ { /* ... */ }
    pub fn orders_open(
            &self,
        ) -> impl Iterator<Item = &Order<ExchangeId, InstrumentNameExchange, Open>> + '_ { /* ... */ }
    pub fn orders_cancelled(
            &self,
        ) -> impl Iterator<Item = &Order<ExchangeId, InstrumentNameExchange, Cancelled>> + '_ { /* ... */ }
    pub fn trades(
            &self,
            time_since: DateTime<Utc>,
        ) -> impl Iterator<Item = &Trade<QuoteAsset, InstrumentNameExchange>> + '_ { /* ... */ }
    pub fn balance_mut(
            &mut self,
            asset: &AssetNameExchange,
        ) -> Option<&mut AssetBalance<AssetNameExchange>> { /* ... */ }
    pub fn ack_trade(&mut self, trade: Trade<QuoteAsset, InstrumentNameExchange>) { /* ... */ }
}

