// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter_execution
// source: barter-execution/src/exchange/mock/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug)]
pub struct MockExchange {
    pub exchange: ExchangeId,
    pub latency_ms: u64,
    pub fees_percent: Decimal,
    pub request_rx: mpsc::UnboundedReceiver<MockExchangeRequest>,
    pub event_tx: broadcast::Sender<UnindexedAccountEvent>,
    pub instruments: FnvHashMap<InstrumentNameExchange, Instrument<ExchangeId, AssetNameExchange>>,
    pub account: AccountState,
    pub order_sequence: u64,
    pub time_exchange_latest: DateTime<Utc>,
}

#[derive(Debug)]
pub struct OpenOrderNotifications {
    pub balance: Snapshot<AssetBalance<AssetNameExchange>>,
    pub trade: Trade<QuoteAsset, InstrumentNameExchange>,
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl MockExchange {
    pub fn new(
            config: MockExecutionConfig,
            request_rx: mpsc::UnboundedReceiver<MockExchangeRequest>,
            event_tx: broadcast::Sender<UnindexedAccountEvent>,
            instruments: FnvHashMap<InstrumentNameExchange, Instrument<ExchangeId, AssetNameExchange>>,
        ) -> Self { /* ... */ }
    pub async fn run(mut self) { /* ... */ }
    fn update_time_exchange(&mut self, time_request: DateTime<Utc>) { /* ... */ }
    pub fn time_exchange(&self) -> DateTime<Utc> { /* ... */ }
    pub fn account_snapshot(&self) -> UnindexedAccountSnapshot { /* ... */ }
    /// Sends the provided `Response` via the [`oneshot::Sender`] after waiting for the latency
    /// [`Duration`].
    /// 
    /// Used to simulate network latency between the exchange and client.
    fn respond_with_latency<Response>(
            &self,
            response_tx: oneshot::Sender<Response>,
            response: Response,
        ) where
            Response: Send + 'static,
        { /* ... */ }
    /// Sends the provided `OpenOrderNotifications` via the `MockExchanges`
    /// `broadcast::Sender<UnindexedAccountEvent>` after waiting for the latency
    /// [`Duration`].
    /// 
    /// Used to simulate network latency between the exchange and client.
    fn send_notifications_with_latency(&self, notifications: OpenOrderNotifications) { /* ... */ }
    pub fn account_stream(&self) -> BoxStream<'static, UnindexedAccountEvent> { /* ... */ }
    pub fn cancel_order(
            &mut self,
            _: OrderRequestCancel<ExchangeId, InstrumentNameExchange>,
        ) -> Order<ExchangeId, InstrumentNameExchange, Result<Cancelled, UnindexedOrderError>> { /* ... */ }
    pub fn open_order(
            &mut self,
            request: OrderRequestOpen<ExchangeId, InstrumentNameExchange>,
        ) -> (
            Order<ExchangeId, InstrumentNameExchange, Result<Open, UnindexedOrderError>>,
            Option<OpenOrderNotifications>,
        ) { /* ... */ }
    pub fn validate_order_kind_supported(
            &self,
            order_kind: OrderKind,
        ) -> Result<(), UnindexedOrderError> { /* ... */ }
    pub fn find_instrument_data(
            &self,
            instrument: &InstrumentNameExchange,
        ) -> Result<&Instrument<ExchangeId, AssetNameExchange>, UnindexedApiError> { /* ... */ }
    fn order_id_sequence_fetch_add(&mut self) -> OrderId { /* ... */ }
    fn build_account_event<Kind>(&self, kind: Kind) -> UnindexedAccountEvent
        where
            Kind: Into<AccountEventKind<ExchangeId, AssetNameExchange, InstrumentNameExchange>>,
        { /* ... */ }
}

