// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/state/instrument/filter.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, PartialOrd, Deserialize, Serialize)]
/// Instrument filter.
/// 
/// Used to filter instrument-centric data structures such as `InstrumentStates`.
pub enum InstrumentFilter<
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> {
    None,
    Exchanges(OneOrMany<ExchangeKey>),
    Instruments(OneOrMany<InstrumentKey>),
    Underlyings(OneOrMany<Underlying<AssetKey>>),
}

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl InstrumentFilter {
    pub fn exchanges(exchanges: impl IntoIterator<Item = ExchangeKey>) -> Self { /* ... */ }
    pub fn instruments(instruments: impl IntoIterator<Item = InstrumentKey>) -> Self { /* ... */ }
    pub fn underlyings(exchanges: impl IntoIterator<Item = Underlying<AssetKey>>) -> Self { /* ... */ }
}

