// @generated by rust-code-mcp crate_skeleton
// snapshot: edb921b2e8ad5bb860faf9bb8f88fd0b
// crate: barter
// source: barter/src/engine/state/instrument/mod.rs
// include: pub,pub(crate)
// include_docs: true; include_attrs: true; include_impls: true; skip_test_items: true; exclude_vendor: true

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
/// Collection of [`InstrumentState`]s indexed by [`InstrumentIndex`].
/// 
/// Note that the same instruments with the same [`InstrumentNameExchange`] (eg/ "btc_usdt") but
/// on different exchanges will have their own [`InstrumentState`].
pub struct InstrumentStates<
    InstrumentData,
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
>(
    pub  FnvIndexMap<
        InstrumentNameInternal,
        InstrumentState<InstrumentData, ExchangeKey, AssetKey, InstrumentKey>,
    >,
);

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize, Constructor)]
/// Represents the current state of an instrument, including its [`Position`](super::position::Position), [`Orders`], and
/// user provided instrument data.
/// 
/// This aggregates all the state and data for a single instrument, providing a comprehensive
/// view of the instrument.
pub struct InstrumentState<
    InstrumentData,
    ExchangeKey = ExchangeIndex,
    AssetKey = AssetIndex,
    InstrumentKey = InstrumentIndex,
> {
    /// Unique `InstrumentKey` identifier for the instrument this state is associated with.
    pub key: InstrumentKey,

    /// Complete instrument definition.
    pub instrument: Instrument<ExchangeKey, AssetKey>,

    /// TearSheet generator for summarising the trading performance associated with an Instrument.
    pub tear_sheet: TearSheetGenerator,

    /// Current `PositionManager`.
    pub position: PositionManager<InstrumentKey>,

    /// Active orders and associated order management.
    pub orders: Orders<ExchangeKey, InstrumentKey>,

    /// User provided instrument level data state. This can include market data, strategy data,
    /// risk data, option pricing data, or any other instrument-specific information.
    pub data: InstrumentData,
}

pub fn generate_unindexed_instrument_account_snapshot<
    InstrumentData,
    ExchangeKey,
    AssetKey,
    InstrumentKey,
>(
    exchange: ExchangeId,
    state: &InstrumentState<InstrumentData, ExchangeKey, AssetKey, InstrumentKey>,
) -> InstrumentAccountSnapshot<ExchangeId, AssetNameExchange, InstrumentNameExchange>
where
    ExchangeKey: Debug + Clone,
    InstrumentKey: Debug + Clone,
{ /* ... */ }

/// Generates an indexed [`InstrumentStates`]. Uses default values for
pub fn generate_indexed_instrument_states<'a, FnPosMan, FnOrders, FnInsData, InstrumentData>(
    instruments: &'a IndexedInstruments,
    time_engine_start: DateTime<Utc>,
    position_manager_init: FnPosMan,
    orders_init: FnOrders,
    instrument_data_init: FnInsData,
) -> InstrumentStates<InstrumentData>
where
    FnPosMan: Fn() -> PositionManager,
    FnOrders: Fn() -> Orders,
    FnInsData: Fn(
        &'a Keyed<InstrumentIndex, Instrument<Keyed<ExchangeIndex, ExchangeId>, AssetIndex>>,
    ) -> InstrumentData,
{ /* ... */ }

// inherent impl facades; original impl generics/where clauses are not reconstructed
impl InstrumentStates {
    /// Return a reference to the `InstrumentState` associated with an `InstrumentIndex`.
    /// 
    /// Panics if `InstrumentState` associated with the `InstrumentIndex` does not exist.
    pub fn instrument_index(&self, key: &InstrumentIndex) -> &InstrumentState<InstrumentData> { /* ... */ }
    /// Return a mutable reference to the `InstrumentState` associated with an `InstrumentIndex`.
    /// 
    /// Panics if `InstrumentState` associated with the `InstrumentIndex` does not exist.
    pub fn instrument_index_mut(
            &mut self,
            key: &InstrumentIndex,
        ) -> &mut InstrumentState<InstrumentData> { /* ... */ }
    /// Return a reference to the `InstrumentState` associated with an `InstrumentNameInternal`.
    /// 
    /// Panics if `InstrumentState` associated with the `InstrumentNameInternal` does not exist.
    pub fn instrument(&self, key: &InstrumentNameInternal) -> &InstrumentState<InstrumentData> { /* ... */ }
    /// Return a mutable reference to the `InstrumentState` associated with an
    /// `InstrumentNameInternal`.
    /// 
    /// Panics if `InstrumentState` associated with the `InstrumentNameInternal` does not exist.
    pub fn instrument_mut(
            &mut self,
            key: &InstrumentNameInternal,
        ) -> &mut InstrumentState<InstrumentData> { /* ... */ }
    /// Return an `Iterator` of references to `InstrumentState`s being tracked, optionally filtered
    /// by the provided `InstrumentFilter`.
    pub fn instruments<'a>(
            &'a self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a InstrumentState<InstrumentData>> { /* ... */ }
    /// Return an `Iterator` of mutable references to `InstrumentState`s being tracked, optionally
    /// filtered by the provided `InstrumentFilter`.
    pub fn instruments_mut<'a>(
            &'a mut self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a mut InstrumentState<InstrumentData>> { /* ... */ }
    /// Return an `Iterator` of references to instrument `TearSheetGenerator`s, optionally
    /// filtered by the provided `InstrumentFilter`.
    pub fn tear_sheets<'a>(
            &'a self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a TearSheetGenerator>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return an `Iterator` of references to instrument `PositionManager`s, optionally
    /// filtered by the provided `InstrumentFilter`.
    pub fn positions<'a>(
            &'a self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a PositionManager>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return an `Iterator` of references to instrument `Orders`, optionally filtered by the
    /// provided `InstrumentFilter`.
    pub fn orders<'a>(&'a self, filter: &'a InstrumentFilter) -> impl Iterator<Item = &'a Orders>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return an `Iterator` of references to custom instrument level data state, optionally
    /// filtered by the provided `InstrumentFilter`.
    pub fn instrument_datas<'a>(
            &'a self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a InstrumentData>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return an `Iterator` of mutable references to custom instrument level data state,
    /// optionally filtered by the provided `InstrumentFilter`.
    pub fn instrument_datas_mut<'a>(
            &'a mut self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a mut InstrumentData>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return a filtered `Iterator` of `InstrumentState`s based on the provided `InstrumentFilter`.
    fn filtered<'a>(
            &'a self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a InstrumentState<InstrumentData>>
        where
            InstrumentData: 'a,
        { /* ... */ }
    /// Return a filtered `Iterator` of mutable `InstrumentState`s based on the
    /// provided `InstrumentFilter`.
    fn filtered_mut<'a>(
            &'a mut self,
            filter: &'a InstrumentFilter,
        ) -> impl Iterator<Item = &'a mut InstrumentState<InstrumentData>>
        where
            InstrumentData: 'a,
        { /* ... */ }
}

impl InstrumentState {
    /// Updates the instrument state using an account snapshot from the exchange.
    /// 
    /// This updates active orders for the instrument, using timestamps where relevant to ensure
    /// the most recent order state is applied.
    pub fn update_from_account_snapshot(
            &mut self,
            snapshot: &InstrumentAccountSnapshot<ExchangeKey, AssetKey, InstrumentKey>,
        ) where
            ExchangeKey: Debug + Clone,
            InstrumentKey: Debug + Clone,
            AssetKey: Debug + Clone,
        { /* ... */ }
    /// Updates the instrument state from an [`Order`] snapshot.
    pub fn update_from_order_snapshot(
            &mut self,
            order: Snapshot<&Order<ExchangeKey, InstrumentKey, OrderState<AssetKey, InstrumentKey>>>,
        ) where
            ExchangeKey: Debug + Clone,
            AssetKey: Debug + Clone,
            InstrumentKey: Debug + Clone,
        { /* ... */ }
    /// Updates the instrument state from an
    /// [`OrderRequestCancel`](barter_execution::order::request::OrderRequestCancel) response.
    pub fn update_from_cancel_response(
            &mut self,
            response: &OrderResponseCancel<ExchangeKey, AssetKey, InstrumentKey>,
        ) where
            ExchangeKey: Debug + Clone,
            AssetKey: Debug + Clone,
            InstrumentKey: Debug + Clone,
        { /* ... */ }
    /// Updates the instrument state based on a new trade.
    /// 
    /// This method handles:
    /// - Opening/updating the current position state based on a new trade.
    /// - Updating the internal [`TearSheetGenerator`] if a position is exited.
    pub fn update_from_trade(
            &mut self,
            trade: &Trade<QuoteAsset, InstrumentKey>,
        ) -> Option<PositionExited<QuoteAsset, InstrumentKey>>
        where
            InstrumentKey: Debug + Clone + PartialEq,
        { /* ... */ }
    /// Updates the instrument state based on a new market event.
    /// 
    /// If the market event has a price associated with it (eg/ `PublicTrade`, `OrderBookL1`), any
    /// open [`Position`](super::position::Position) `pnl_unrealised` is re-calculated.
    pub fn update_from_market(
            &mut self,
            event: &MarketEvent<InstrumentKey, InstrumentData::MarketEventKind>,
        ) where
            InstrumentData: InstrumentDataState<ExchangeKey, AssetKey, InstrumentKey>,
        { /* ... */ }
}

